### ISSUE TITLE
npm i -g automation

### ISSUE THREAD

**Issue by crapthings** [highcharts/node-export-server#102]
will this work ? seems not, it only show step 2
echo y | echo latest | echo y | echo y | npm i -g highcharts-export-server

```
Highcharts Export Server

https://github.com/highcharts/node-export-server

In order to use this application, Highcharts needs to be downloaded and
embedded. A license is required to use Highcharts if you're a
for-profit, commercial, outfit.

The license can be viewed here: https://shop.highsoft.com/media/highsoft/Standard-License-Agreement-6.0.pdf

Agree to the license terms? y/n:  (no) y
Select your Highcharts version (e.g. 4.2.2)::  (latest) highcharts-export-server@2.0.4 /home/cube/.nvm/versions/node/v4.8.6/lib/node_modules/highcharts-export-server
├── uuid@3.1.0
├── colors@1.1.2
├── cors@2.8.1 (vary@1.1.2)
├── express-rate-limit@2.6.0 (defaults@1.0.3)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── body-parser@1.16.0 (content-type@1.0.4, bytes@2.4.0, depd@1.1.1, qs@6.2.1, on-finished@2.3.0, raw-body@2.2.0, http-errors@1.5.1, debug@2.6.0, iconv-lite@0.4.15, type-is@1.6.15)
├── express@4.14.1 (escape-html@1.0.3, array-flatten@1.1.1, cookie-signature@1.0.6, utils-merge@1.0.0, content-type@1.0.4, encodeurl@1.0.1, methods@1.1.2, merge-descriptors@1.0.1, vary@1.1.2, cookie@0.3.1, etag@1.7.0, range-parser@1.2.0, parseurl@1.3.2, path-to-regexp@0.1.7, serve-static@1.11.2, content-disposition@0.5.2, fresh@0.3.0, depd@1.1.1, qs@6.2.0, on-finished@2.3.0, finalhandler@0.5.1, debug@2.2.0, proxy-addr@1.1.5, send@0.14.2, type-is@1.6.15, accepts@1.3.4)
├── express-form-data@2.0.0 (connect-multiparty@2.1.0)
├── prompt@1.0.0 (revalidator@0.1.8, pkginfo@0.4.1, read@1.0.7, winston@2.1.1, utile@0.3.0)
├── request@2.83.0 (aws-sign2@0.7.0, forever-agent@0.6.1, oauth-sign@0.8.2, tunnel-agent@0.6.0, is-typedarray@1.0.0, caseless@0.12.0, safe-buffer@5.1.1, stringstream@0.0.5, aws4@1.6.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.1, performance-now@2.1.0, qs@6.5.1, combined-stream@1.0.5, mime-types@2.1.17, tough-cookie@2.3.3, form-data@2.3.1, hawk@6.0.2, http-signature@1.2.0, har-validator@5.0.3)
├── async@2.1.4 (lodash@4.17.4)
└── phantomjs-prebuilt@2.1.14 (progress@1.1.8, kew@0.7.0, which@1.2.14, es6-promise@4.0.5, request-progress@2.0.1, hasha@2.2.0, fs-extra@1.0.0, extract-zip@1.5.0, request@2.79.0)
```

**Comment by cvasseng** [comment]
If you want it to be non-interactive, you can set the environment variables described here:
https://github.com/highcharts/node-export-server#using-in-automated-deployments

**Comment by jarrettj** [comment]
Hi.

Does that option work? I've just tried it and it does not accept the license. Using AWS elastic beanstalk. Maybe another way you set the env var? I used the console. 

Even running the command on the command line and it still prompts.

```
[ec2-user@ip-10-0-15-12 ~]$ echo $ACCEPT_HIGHCHARTS_LICENSE
YES
[ec2-user@ip-10-0-15-12 ~]$ sudo npm install highcharts-export-server -g --unsafe-perm
/usr/bin/highcharts-export-server -> /usr/lib/node_modules/highcharts-export-server/bin/cli.js

> highcharts-export-server@2.0.7 install /usr/lib/node_modules/highcharts-export-server
> node ./build.js


Highcharts Export Server

https://github.com/highcharts/node-export-server

In order to use this application, Highcharts needs to be downloaded and 
embedded. A license is required to use Highcharts if you're a 
for-profit, commercial, outfit. 

The license can be viewed here: https://shop.highsoft.com/media/highsoft/Standard-License-Agreement-6.0.pdf

Agree to the license terms? y/n:  (no) 
```

**Comment by cvasseng** [comment]
If you're using Elastic Beanstalk, you should set the variables in your configuration.

- Choose "Configuration" in your environment
- Click the gear next to "Software Configuration"
- Under "Environment Properties" add an entry called "ACCEPT_HIGHCHARTS_LICENSE" with the value "1"

This is how we run the official export server at export.highcharts.com, so the option definitely works.

**Comment by jarrettj** [comment]
So why does the docs say to set it to YES? I'll try 1 (Which is true I know:)

**Comment by cvasseng** [comment]
Either should work - it doesn't actually check the contents of ACCEPT_HIGHCHARTS_LICENSE, it only checks if it's set. So it can be anything.

**Comment by jarrettj** [comment]
I use the .ebextensions folder to add the a phantomjs.config file with:
```
commands:
  01_install:
    command: sudo npm install highcharts-export-server -g --unsafe-perm
```

I think I know what it is, been using commands instead of container_commands. 

Thanks for the help dude, I'm sure it will work now :)

Regards.
JJ

**Comment by cvasseng** [comment]
No problem!

You might get some additional issues using npm in .ebextensions like that, depending on which ami versions you're on, as it may not be in your path variable.

It might be easier if you create a small shim app that uses the export server as a module. That way you don't have to mess with container commands. 

Something like: 

```
const exp = require('highcharts-export-server');

// Create a pool of exporting workers
exp.initPool({
  maxWorkers: 8,
  initialWorkers: 8,
  workLimit: 80
});

// Enable verbose logging for debugging
exp.logLevel(4);

// Start the export server
exp.server.start(<port number>);
```

and then setting `main` in your `package.json` to point to the above script.

Doing that should allow you to just zip it up, and upload it straight to a node Elastic Beanstalk environment.

**Comment by jarrettj** [comment]
Ah no this is a ZF2 PHP application, we previously used phantomjs to generate graphs but it is giving issues. And I was looking at using the export server instead. 

But issues installing it on EB will probably have us stuck on the old way. Even if I use container_commands the install just sits there and hangs because it's obviously waiting on a prompt. 

I'll park this for today and have a look tomorrow as clearly I've missed something simple.
