### ISSUE TITLE
Exported chart with empty series. Please help

### ISSUE THREAD

**Issue by mkoczorowski** [highcharts/node-export-server#103]
Hi guys. Awesome work on this.. I am encountering a big problem though.
For some reason when I export my chart (which works perfectly as js on the page) I get an empty chart. with no series on it. So strange. I cant figure out why. 
They both share the same config, listed below.

I have tried stripping out config for export but no luck at all. Maybe there is a limit of data points on the server or something? **constr: 'StockChart'**

<img width="854" alt="app2_0____sites_stockopedia_app2_0__-_____src_app_debug_minefield_minefield_component_ts__app2_0__and_stockopedia___stockopedia" src="https://user-images.githubusercontent.com/8155896/33692222-0aef20ec-dae4-11e7-8132-9d8b81d16920.png">

[chartConfig.json.zip](https://github.com/highcharts/node-export-server/files/1537336/chartConfig.json.zip)

I would appreciate any help in this matter. Thanks!

**Comment by TorsteinHonsi** [comment]
Apparently it's not a problem with the export server per se. If we render your chart in a 600px container, it also fails to show in a regular page: http://jsfiddle.net/highcharts/wjqnkx2c/. Now if we set `dataGrouping.enabled` to `false`, it renders correctly. So I'd recommend that you take a look at your dataGrouping config.

Closing this now, as it is not specific to the export server. Please reopen if new information appears.
