### ISSUE TITLE
Hichcharts Technical indicators plugin / external file/ - question

### ISSUE THREAD

**Issue by mkoczorowski** [highcharts/node-export-server#104]
Hi guys,
I would like to add technical indicators to a chart
https://www.highcharts.com/docs/chart-and-series-types/technical-indicator-series
this requires me to load an external file before rendering the chart ' indicators/indicators.js'

How can I do that ? Can anyone help ?
Thank you

**Comment by pawelfus** [comment]
Hi @mkoczorowski 

Take a look at our [official demos](https://www.highcharts.com/stock/demo/macd-pivot-points), for example [this one](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/macd-pivot-points/). In short, load script like any other:

```

<script src="https://code.highcharts.com/stock/highstock.js"></script>
<!-- Load indicators: -->
<script src="https://code.highcharts.com/stock/indicators/indicators.js"></script>
<script src="https://code.highcharts.com/stock/indicators/macd.js"></script>
```

**Comment by cvasseng** [comment]
If you want to add additional modules or includes to the export server, you need to add them to the `cdnScriptsCommon` array in`build.js`. Run `npm install` afterwards, and you should be good to go. You can start the server with `node bin/cli.js --enableServer 1` afterwards, or run `npm link` to link the global `highcharts-export-server` to your local repository.
