### ISSUE TITLE
xrange charts are not rendered

### ISSUE THREAD

**Issue by jarregui** [highcharts/node-export-server#106]
Server doesn't render xrange charts.  It gives a Highcharts error 17  www.highcharts.com/errors/17

**Comment by TorsteinHonsi** [comment]
Missing `modules/xrange.js` @cvasseng?

**Comment by jarregui** [comment]
I see there is a pending pull request to also add sunburst module... shouldn't all available modules be included by default?   Thanks!

**Comment by jarregui** [comment]
Oops... sorry, clicked wrong button

**Comment by cvasseng** [comment]
Added in 36430e8fd73e53fe341a8ac330ead21f8c932b35.
