### ISSUE TITLE
Example Code - No Title 

### ISSUE THREAD

**Issue by CopaceticVT** [highcharts/node-export-server#108]
Installed highcharts node export server.
node v6.9.4
npm 3.10.10

Using php curl to get image hitting the server and the image is created however, there is no title, or categories listed.  

```
curl_setopt($ch, CURLOPT_URL, "servername:port");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"infile\":{\"title\": {\"text\": \"Steep Chart\"}, \"xAxis\": {\"categories\": [\"Jan\", \"Feb\", \"Mar\"]}, \"series\": [{\"data\": [29.9, 71.5, 106.4]}]}}");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = "Content-Type: application/json";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

$fp = fopen('image.png', 'w'); 
fwrite($fp, $result);
fclose($fp);
```

![image](https://user-images.githubusercontent.com/34892703/34393078-fb868c90-eb1d-11e7-9311-b2f22bfe9091.png)

**Error seen on export server:**

```
SyntaxError: Unexpected token S in JSON at position 27
    at Object.parse (native)
    at parse (/usr/lib/node_modules/highcharts-export-server/node_modules/body-parser/lib/types/json.js:88:17)
    at /usr/lib/node_modules/highcharts-export-server/node_modules/body-parser/lib/read.js:116:18
    at invokeCallback (/usr/lib/node_modules/highcharts-export-server/node_modules/raw-body/index.js:262:16)
    at done (/usr/lib/node_modules/highcharts-export-server/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/usr/lib/node_modules/highcharts-export-server/node_modules/raw-body/index.js:307:7)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
```

Thanks!

**Comment by cvasseng** [comment]
Judging from the syntax error, kt looks like it may be related to escaping in the curl PHP module.

I tried running your data with: 
```curl -H "Content-Type: application/json" -X POST -d "{\"infile\":{\"title\": {\"text\": \"Steep Chart\"}, \"xAxis\": {\"categories\": [\"Jan\", \"Feb\", \"Mar\"]}, \"series\": [{\"data\": [29.9, 71.5, 106.4]}]}}" localhost:7801 --output test.png``` from the terminal, which works as expected. 

Could you try running the above so we can isolate the problem a bit more?

**Comment by cvasseng** [comment]
Given the almost three months without a reply, I'm assuming the issue has been fixed. If you're still having issues, please contact us through one of the support channels listed here https://www.highcharts.com/support, and someone will try to assist you.
