### ISSUE TITLE
why i can not install

### ISSUE THREAD

**Issue by tlhe** [highcharts/node-export-server#109]
npm install highcharts-export-server

> highcharts-export-server@2.0.4 install /data/v_tlonghe/gamer-data-export/node_modules/highcharts-export-server
> node ./build.js

Highcharts Export Server

https://github.com/highcharts/node-export-server

In order to use this application, Highcharts needs to be downloaded and 
embedded. A license is required to use Highcharts if you're a 
for-profit, commercial, outfit. 

The license can be viewed here: https://shop.highsoft.com/media/highsoft/Standard-License-Agreement-6.0.pdf

Agree to the license terms? y/n:  (no) y
Select your Highcharts version (e.g. 4.2.2)::  (latest) 
Include Maps? (requires Maps license):  (no) no
Enable styled mode? (requires Highcharts/Highstock 5 license):  (no) no
Pulling Highcharts from CDN (latest)..
latest
   https://code.highcharts.com/stock/highstock.js
   https://code.highcharts.com/highcharts-more.js
   https://code.highcharts.com/modules/exporting.js
   https://code.highcharts.com/highcharts-3d.js
   https://code.highcharts.com/modules/data.js
   https://code.highcharts.com/modules/funnel.js
   https://code.highcharts.com/modules/solid-gauge.js
   https://code.highcharts.com/modules/heatmap.js
   https://code.highcharts.com/modules/treemap.js
error fetching Highcharts: { Error: connect ETIMEDOUT 104.24.31.113:443
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.24.31.113',
  port: 443 }
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN co-mocha@1.2.0 requires a peer of mocha@>=1.18 <4 but none was installed.

+ highcharts-export-server@2.0.4
updated 1 package in 33.254s

**Comment by cvasseng** [comment]
Are you behind a proxy server?

If so, you need to set a few environment variables as explained [here](https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables).

**Comment by cvasseng** [comment]
If you're still having issues with this, feel free to reopen this ticket, or submit a new one.
