### ISSUE TITLE
PNG image export adds {{js}} tag

### ISSUE THREAD

**Issue by sushilthe** [highcharts/node-export-server#11]
I am using node-export-server in my node js app to export highchart graphs to png. But, there is a slight bug that writes {{js}} on top of image.

One thing that I have found out is, while exporting svg this problem does not occur and highcaharts.com link gets placed at bottom, but in png the link disappears and {{js}} tag gets written.

Example:
![chart](https://cloud.githubusercontent.com/assets/2399519/21254448/95eb2de0-c38d-11e6-8f34-bb0fdf7e782d.png)

**Comment by cvasseng** [comment]
Hi, this was fixed in a push yesterday, and was just published on NPM as well. 
Re-installing (or git pull if you're not using NPM) should fix the issue.
