### ISSUE TITLE
Export server not working as expected

### ISSUE THREAD

**Issue by marcelcaferati** [highcharts/node-export-server#116]
I am trying to make the following config work on export server.
https://pastebin.com/SM9kgxm0

Pasting it on your official fiddle the chart renders just fine.
http://jsfiddle.net/LLExL/8928/

Trying to retrieve a PNG throught export server running locally it will just give me a PNG with error 18.

I have checked the yAxis, there is only one and all the series are pointing to yAxis 0.

This is the ajax call:
https://pastebin.com/EtSAjf9C

More info:
I am runing the server out of the box. 
`git clone https://github.com/highcharts/node-export-server
npm install
npm link`

Using this to run.
`highcharts-export-server --enableServer 1 --host 127.0.0.1 --port 3003`

**Comment by KacperMadej** [comment]
Hi @marcelcaferati 

If the xAxis or yAxis for series is set to 0 then you can remove this from code because the settings are like this by default.

In options `type: 'line'` does nothing. Default series type is `line`, but if you want to set it in `options` use `chart:{type:'line'}`.

I have just tested the case and it works fine - I have inserted your options into [the test file](https://github.com/highcharts/node-export-server/blob/master/tests/module/module_test.js) and run it using `node tests/module/module_test.js`. Exported image is correct, no errors.

**Comment by marcelcaferati** [comment]
Hello @KacperMadej 
We followed your instructions and we made some progress.

By removing the type and the "yAxis:0" from our series, the error 18 was gone but we got to an error 14.

So we removed everything inside our data and just left plain numbers, and it sort of worked, it rendered the chart but not the values. 

We narrowed down the problem to our data object.

` data: [
                        {
                            y: 10,
                            marker: {
                                symbol: 'circle',
                                lineColor: '#ffffff',
                                lineWidth: 1,
                                radius: 3,
                                states: {
                                    hover: {
                                        radius: 3,
                                        lineWidth: 2
                                    }
                                }
                            },
                            dataLabels: {
                                enabled: false,
                                style: {
                                    fontSize: '18px'
                                }
                            }
                        },
                        {
                            y: 20,
                            marker: {
                                symbol: 'circle',
                                lineColor: '#ffffff',
                                lineWidth: 1,
                                radius: 3,
                                states: {
                                    hover: {
                                        radius: 3,
                                        lineWidth: 2
                                    }
                                }
                            },
                            dataLabels: {
                                enabled: false,
                                style: {
                                    fontSize: '18px'
                                }
                            }
                        }
                    ]`

It looks like the only think that this object accepts on node-export-server is plain numbers? we can't use a regular data object?

**Comment by KacperMadej** [comment]
@marcelcaferati 

The export responds to `application/json`, `multipart/form-data`, and URL encoded requests.
This demo works fine - http://jsfiddle.net/BlackLabel/LLExL/8964/

The `contentType` can be set to `'application/json',` and `data` of the request should be stringified e.g. using `JSON.stringify`.

**Comment by marcelcaferati** [comment]
@KacperMadej 
That worked, thanks! The problem was the JSON.Stringfy
