### ISSUE TITLE
Exception: no input given

### ISSUE THREAD

**Issue by shobhitsharma** [highcharts/node-export-server#12]
Its seems even trying the example as node.js client, with all necessary options passed, the returned callback returns `no input given`

Some debugging logs:

Payload:

<img width="617" alt="screen shot 2016-12-16 at 12 58 15 pm" src="https://cloud.githubusercontent.com/assets/772855/21262106/c315155e-c38f-11e6-97d5-5bb68772ca2f.png">

Response:

<img width="636" alt="screen shot 2016-12-16 at 12 58 27 pm" src="https://cloud.githubusercontent.com/assets/772855/21262109/c6577482-c38f-11e6-82e3-2423536391a9.png">

This goes through https://github.com/highcharts/node-export-server/blob/6c90318f93731fee2e5ad86dc32a6917fadedcd9/lib/chart.js#L277.

**Comment by cvasseng** [comment]
Thanks for reporting.

The node module only supported chart options in the `infile` attribute. This was fixed in f861128.

NPM has been updated (now at v0.2.53), so a reinstall of the module should fix the problem.
