### ISSUE TITLE
Not able to get SVG output as text/b64

### ISSUE THREAD

**Issue by nitishSa** [highcharts/node-export-server#120]
While trying to get the svg output from export server, i am getting an output as i file.
But i wanted an svg text output. can you guys please suggest some way in which i can get the output.

//Include the exporter module
const exporter = require('highcharts-export-server');

//Export settings 
var exportSettings = {
    type: 'svg',
    options: {
        title: {
            text: 'My Chart'
        },
        xAxis: {
            categories: ["Jan", "Feb", "Mar", "Apr", "Mar", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
        },
        series: [
            {
                type: 'line',
                data: [1, 3, 2, 4]
            },
            {
                type: 'line',
                data: [5, 3, 4, 2]
            }
        ]
    }
};

//Set up a pool of PhantomJS workers
exporter.initPool();

//Perform an export
/*
    Export settings corresponds to the available CLI arguments described
    above.
*/
exporter.export(exportSettings, function (err, res) {
    //The export result is now in res.
    //If the output is not PDF or SVG, it will be base64 encoded (res.data).
    //If the output is a PDF or SVG, it will contain a filename (res.filename).

    //Kill the pool when we're done with it, and exit the application
    exporter.killPool();
    process.exit(1);
});
Here the res is returning me a file as o/p

**Comment by cvasseng** [comment]
It's not possible to get the raw string directly out of the export. You need to read the file returned by the export callback.

```
const fs = require('fs');

<other code here>

exporter.export(exportSettings, function (err, res) {
  if (res.filename) {
     let svgString = fs.readfileSync(res.filename, 'utf8');
     // Do something with the svgString here..
  }
  exporter.killPool();
  process.exit(1);
});
```

**Comment by nitishSa** [comment]
Thanks followed the same step.

But in my application, we would be generating lots for highchart svg outputs. This will cause lots of files to be created. 

I have added fs.unlinkSync(res.filename); to delete the file once i get the svg.

It would be great to get a option which returns the svg in text format similar to png & jpeg

**Comment by cvasseng** [comment]
It's unlikely that we'll add support for that in the short term as we're planning a switch away from phantom. 

The reason it uses files is simply because it didn't work very well to pass it as b64 as is it does  for png/jpg due to encoding issues. It's also faster to use the filesystem than it is to use stdio.

**Comment by nitishSa** [comment]
Thanks for the help!

**Comment by azizj1** [comment]
For png/jpg, how do I get it to output as a file instead of base64?
