### ISSUE TITLE
highcharts-export-server, Using as a Node.js Module,  multiple requests at once

### ISSUE THREAD

**Issue by SaurabhKumarr** [highcharts/node-export-server#123]
I have a secniro where have to get more than one chart one by one using highcharts-export-server using node js.

var chart1 = {
    type: 'svg',
    options: {        
        chart: {
            backgroundColor: {
                linearGradient: [0, 0, 500, 500],
                stops: [
                    [0, 'rgb(255, 255, 255)'],
                    [1, 'rgb(240, 240, 255)']
                    ]
            },
            borderWidth: 2,
            plotBackgroundColor: 'rgba(255, 255, 255, .9)',
            plotShadow: true,
            plotBorderWidth: 1
        },
    
        xAxis: {
            type: 'datetime'
        },

        series: [{
            data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
            pointStart: Date.UTC(2010, 0, 1),
            pointInterval: 3600 * 1000 // one hour
        }]
        
    }
};

var chart2 = {
    type: 'svg',
    options: {
        title: {
            text: 'My Chart'
        },
        xAxis: {
            categories: ["Jan", "Feb", "Mar", "Apr", "Mar", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
        },
        series: [
            {
                type: 'line',
                data: [1, 3, 2, 4]
            },
            {
                type: 'line',
                data: [5, 3, 4, 2]
            }
        ]
    }
};
var graphLen = [chart1, chart2];
    exporter.initPool();
    for(var i=0; i<graphLen.length; i++) {
        exporter.export(graphLen[i], function (err, res) {
            console.log(res.filename);	
        });        
    }
  exporter.killPool();

I want both chart1 and chart2 svg one by one. but for first chart(chart1) res is undefined.
_output_
**error:**     at Object.postWork (d:\dev\izo_node\node_modules\highcharts-export-server\lib\phantompool.js:343:25)
    at exec (d:\dev\izo_node\node_modules\highcharts-export-server\lib\chart.js:145:15)
    at doExport (d:\dev\izo_node\node_modules\highcharts-export-server\lib\chart.js:189:9)
    at Object.module.exports [as export] (d:\dev\izo_node\node_modules\highcharts-export-server\lib\chart.js:305:20)
    at createGraphArr (d:\dev\izo_node\app.js:76:24)
please help. thanks in advance.

**Comment by cvasseng** [comment]
You are killing the pool before you're done exporting. The export call is async. Remove `exporter.killPool()`, and either maintain a counter in the export callback and call it in there when the counter is equal to `graphLen.length`, or switch to using [promises](https://github.com/highcharts/node-export-server/blob/master/tests/module/promises.js) or an async waterfall. 

If you need more help, please feel free to contact support through one of the channels listed here: www.highcharts.com/support as we're trying to keep the issue tracker to bug reports rather than general questions.
