### ISSUE TITLE
globalOptions doesn't work for CLI

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/node-export-server#124]
I tried multiple ways of setting the `globalOptions` in CLI as a string. After debugging it looks like the options are parsed into a string and doesn't work at all.

I tried with:
`highcharts-export-server -infile ./tests/basic.json -outfile ./result.png -globalOptions {"lang":{"thousandsSep":','}}`

To see that this doesn't work I changed the `basic.json` to:
`{"xAxis":[{"labels":{"format":"{value:,2f}"}}],"series":[{"data":[[15000, 5000], [17000, 7000]]}]}`

The chart should look like: http://jsfiddle.net/BlackLabel/f3by0oxe/

and it looks like:
![result](https://user-images.githubusercontent.com/8960408/37781888-f1dc53f2-2df1-11e8-9033-25b1e71f3d91.png)

so no `thousandsSep`.

**Comment by cvasseng** [comment]
@KacperMadej this is fixed now. But you need to send in a valid JSON string - you have some singlequotes in there, and the json is not wrapped in quotes. ;)

Should be sent in like this: `-globalOptions '{"lang":{"thousandsSep":","}}'`

I think @PaulDalek's issue is fixed also in the last commit.

**Comment by cvasseng** [comment]
I've also published the update to NPM now under 2.0.11.

**Comment by KacperMadej** [comment]
Looks like `globalOptions` are working. On Windows in CLI `-globalOptions {"lang":{"thousandsSep":\",\"}}` should be used. Otherwise `"` will be stripped. I would call this a feature - if you use `-globalOptions {"lang":{"thousandsSep":"x"}}` then the `x` will be treated as a variable.

**Comment by cvasseng** [comment]
Oh, sorry I didn't know that Windows did it like that. :) Great that it's working now.

**Comment by PaulDalek** [comment]
Running module_test.js works as expected too. Also, adding callback in a string form inside exportSettings, which did not work before, now works without a problem.

**Comment by cvasseng** [comment]
Excellent. Thanks guys!
