### ISSUE TITLE
Images added in callback are not visible on exported chart

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/node-export-server#129]
#### Expected behaviour
Server waits for images from the callback to load.

#### Actual behaviour
Images added in the callback are not visible on exported chart.

Probably related with: https://github.com/highcharts/node-export-server/issues/43

Internal note:
Commenting out the window.isDoneLoadingImages = true; from the load event inside worker.js file results in waiting for a time specified in pollTimeout variable and exporting chart with an image added with renderer.

**Comment by cvasseng** [comment]
#43 is about images referenced in the config itself, where we can rely on Highcharts to figure out when things are loaded.

This one is a bit different. The "right" way of doing it is to set `asyncRendering` to true in the POST request, and call `highexp.done()` in the callback when the image is done loading (by attaching to e.g. `onload` or a similar event). 

`isDoneLoadingImages` is used to signal the phantom worker that all the declarative images have been loaded. Removing it or forcing it to false always will basically cause the max timeout to always kick in at 2s (so all the exports will always create the chart then wait for 2 seconds), which is probably why it appears to be working when doing that (as 2 seconds is likely enough for the image added in the callback to load).

**Comment by cvasseng** [comment]
There's another issue on this too (https://github.com/highcharts/node-export-server/issues/137), I've added an example there for how to use `asyncRendering` to wait for images added in the callback to load. The other one uses resources, but the approach is the same when using callbacks too.
