### ISSUE TITLE
Weird comma character in the top of the generated chart image

### ISSUE THREAD

**Issue by vincentwongso** [highcharts/node-export-server#130]
After the latest update when I generated an image, it produces weird `,` character in the top of image. I have attached an example.

#### Expected behaviour
Produce image without the comma in the beginning of the image.

#### Actual behaviour
![issue](https://user-images.githubusercontent.com/1300030/38340569-829d900c-38b7-11e8-868c-6cb20f675ed2.png)

#### Reproduction steps
highcharts-export-server --instr '{"credits":{"enabled":false},"title":{"text":""},"xAxis":{"type":"datetime"},"yAxis":{"title":{"text":"Total"}},"legend":{"enabled":true},"series":[{"type":"spline","name":"Infringements","data":[[1519862400000,24211],[1519948800000,35252],[1520035200000,26803],[1520121600000,28169],[1520208000000,25300],[1520294400000,34831],[1520380800000,39004],[1520467200000,32088],[1520553600000,33513],[1520640000000,24922],[1520726400000,24774],[1520812800000,19530],[1520899200000,30096],[1520985600000,31502],[1521072000000,28116],[1521158400000,26716],[1521244800000,23972],[1521331200000,24330],[1521417600000,20992],[1521504000000,23006],[1521590400000,23054],[1521676800000,19514],[1521763200000,22200],[1521849600000,21267],[1521936000000,20249],[1522022400000,18935],[1522108800000,21724],[1522195200000,18760],[1522281600000,16090],[1522368000000,19610],[1522454400000,17738]]},{"type":"spline","name":"Notices","data":[[1519862400000,24428],[1519948800000,35755],[1520035200000,25623],[1520121600000,26913],[1520208000000,23986],[1520294400000,32534],[1520380800000,36936],[1520467200000,31372],[1520553600000,32162],[1520640000000,23772],[1520726400000,23601],[1520812800000,18306],[1520899200000,28061],[1520985600000,29540],[1521072000000,27470],[1521158400000,25457],[1521244800000,22843],[1521331200000,23168],[1521417600000,19902],[1521504000000,21801],[1521590400000,20606],[1521676800000,19611],[1521763200000,20843],[1521849600000,20381],[1521936000000,18332],[1522022400000,16224],[1522108800000,21590],[1522195200000,17914],[1522281600000,15501],[1522368000000,18665],[1522454400000,16707]]}]}' --outfile 'chart/test.png'

#### Environment Details
OS: Ubuntu 14.04.5
node-export-server: 2.0.12
phantomJS: 2.1.1

**Comment by TorsteinHonsi** [comment]
_Internal note:_
This does not happen when pasting the options into https://export.highcharts.com.

**Comment by qwe900** [comment]
highcharts-export-server\phantom its in the template html had this issue too last week, found there was a comma after </script> or simimlar

**Comment by cvasseng** [comment]
FIxed in master, thanks for reporting!

Will be pushed to npm later today, hoping to get a fix for something else into the next version also.

**Comment by cvasseng** [comment]
I just published 2.0.13 to NPM which includes the fix for this.
