### ISSUE TITLE
Heatmap Axis Label Formatter function is not called

### ISSUE THREAD

**Issue by remoteservice** [highcharts/node-export-server#131]
I am trying to manipulate axis label. For example, the original data at x axis is from 0 to 23, I want to show it as from 0 to 4 with tickInterval as 6. so I implemented as below,
xAxis: {
      	  startOnTick: false,
	endOnTick: false,
            min: 0,
            max: 23,
            tickInterval: 6,
            tickLength: 5,
             labels: {
               formatter: function () {
                //let label = this.axis.defaultLabelFormatter.call(this);
              //  return Math.floor(this.value/6);
                	return this.value;
              } 
            }  
  },
This works fine in Highchart, https://jsfiddle.net/4aqhB/1729/
But it is not working in highcharts export server.

Below is how I set up exportSettings,
exportSettings = {
			type: 'png',
			options: {
				chart: {
					type: 'heatmap',
					height: 150,
					width: 2500,
				},
				xAxis: {
					min: 0,
					max: 23,
					startOnTick: false,
					endOnTick: false,
					tickLength: 5,
					tickWidth: 1,
					tickInterval: 6,
					labels: {
						formatter: function () {
							//let label = this.axis.defaultLabelFormatter.call(this);
							return this.value / 6;
							// return this.value;
						},
						align: 'left',
						x: 30,
						y: 10
					}
				},
    others including data .................
}

#### Expected behaviour
Formatter function called to manipulate this.value in order to change the scale of axis

#### Actual behaviour
I tested many different ways and found that formatter function was not called in node export server but it was called in Highcharts. 

Please help on this. Thanks much.

#### Reproduction steps
 

https://jsfiddle.net/4aqhB/1729/

**Comment by cvasseng** [comment]
How are you doing the export? Are you using `highcharts-export-server` as a module, or as an HTTP server? Functions are not supported when running as a module unless you stringify the input to the the export function without quotes.

**Comment by simon-tannai** [comment]
Hi ! 
I have the same issue on `highcharts-export-server` used as HTTP server:

```js
    plotOptions: {
      series: {
        dataLabels: {
          enabled: true,
          formatter: () => 'test',
        },
      },
    },
```

It's seems the formatter is not executed.

**Comment by KacperMadej** [comment]
Hi @simon-tannai 

How are you passing the chart's configuration? Are you exporting chart using export module with export server URL pointing to your HTTP server? If the latter than, is it possible for you to recreate the problem using this demo (with exporting options change): http://jsfiddle.net/BlackLabel/zpf2e71v/

**Comment by simon-tannai** [comment]
Hi @KacperMadej 

I'm using my own `node-export-server` (into Docker's container) and I'm doing the export with a simple HTTP POST to my export server.
It's for a full back-end solution, I cannot use the export module :S

**Comment by KacperMadej** [comment]
I tested with cURL and on Windows the problem is when trying to pass `>` or `<`. The cURL error says: "The system cannot find the file specified.".

Connected to #94 

Doesn't work (has '<' in formatter function):
```
curl -H "Content-Type: application/json" -X POST -d "{\"infile\":\"{plotOptions:{series:{dataLabels:{enabled:true,formatter:function() { if (4 < 5) { return 'dl'; } else { return 'not'; } }}}}, series:[{data:[3,2,2,4]}]}\"}" 127.0.0.1:7801 -o mychart64.png
```

Works fine (no '>'):
```
curl -H "Content-Type: application/json" -X POST -d "{\"infile\":\"{plotOptions:{series:{dataLabels:{enabled:true,formatter:function() { if (4 - 5) { return 'dl'; } else { return 'not'; } }}}}, series:[{data:[3,2,2,4]}]}\"}" 127.0.0.1:7801 -o mychart64.png
```

 @cvasseng ?

**Comment by gam0ny** [comment]
Hello everyone!
@cvasseng @KacperMadej @simon-tannai @grzegorziwacz  is there any workaround for this issue? Experiencing the same behaviour and am just curious if there is a way to bypass it. 

Thanks in advance!

"highcharts-export-server": "^2.1.0",

`const chartOptions = (xFirstData, yFirstData, ySecondData) => ({
  chart: {
    type: 'area',
  },
  credits: {
    enabled: false,
  },
  colors: ['#30527a', '#d1d9e8'],
  title: {
    text: 'Accumulating Annual Needs vs. Escalating Funding',
  },
  legend: {
    align: 'center',
    verticalAlign: 'top',
    layout: 'horizontal',
    margin: 20,
    borderWidth: 1,
  },
  xAxis: {
    categories: xFirstData,
  },
  plotOptions: {
    area: {
      marker: {
        enabled: false,
      },
    },
  },
  yAxis: {
    title: {
      enabled: false,
    },
    allowDecimals: false,
    min: 0,
    tickPixelInterval: 50,
    labels: {
      formatter: function () {
        return `$ ${this.value}`;
      }
    },
  },
  series: [
    {
      name: 'Accumulating Identified Needs',
      data: yFirstData,
    },
    {
      name: 'Escalating Funding',
      data: ySecondData,
    },
  ],
});

export default chartOptions;



labels: {
      formatter: function () {
        return `$ ${this.value}`;
      }
    },`

**Comment by KacperMadej** [comment]
A workaround could be to avoid the problematic characters - here it might be $.
Anything we could do or add here? @PaulDalek @madepiet

**Comment by PaulDalek** [comment]
Closing this as it is fixed in the newest version.

Usage:
- CLI and Node module exports allow functions in the options object.
- HTTP export requires functions to be stringified.

For the above to work the `allowCodeExecution` option must be set to true in order to allow code execution.
