### ISSUE TITLE
CLI documentation

### ISSUE THREAD

**Issue by MonteShaffer** [highcharts/node-export-server#14]
Hi,

I setup the npm globally

`npm install highcharts-export-server -g`

Now, I want to call from the CLI the code...
`
highcharts-export-server --logLevel 4 --logDest  '/path/to/CLI/highcharts.log' --width 1200 --type 'png' --constr 'Chart' --instr '{"internal-key":"freeHighChart","credits":{"enabled":false},"chart":{"type":"bubble","plotBorderWidth":1,"zoomType":"xy","resetZoomButton":{"theme":{"display":"none"},"position":{"align":"left","verticalAlign":"bottom","x":-50,"y":25},"relativeTo":"plot"}},"plotOptions":{"bubble":{"minSize":25,"maxSize":50},"series":{"allowPointSelect":true,"dataLabels":{"format":"{point.name}","enabled":true},"marker":{"states":{"select":{"fillColor":"red","lineWidth":0}}},"point":{"events":{"click":"function(e){ var obj = e.point; doZoom(subsetHighChart, obj.x-1, obj.x+1, obj.y-1, obj.y+1, obj.index, obj.name, obj.nonstopstem.ideafreq);}","select":"function(e){ doZoom(subsetHighChart, e.target.x-1, e.target.x+1, e.target.y-1, e.target.y+1, e.target.index, e.target.name, e.target.nonstopstem.ideafreq); $(\"#idea-tab-free-highchart-search-box\").combobox(\"setText\",e.name); }"}}}},"title":{"text":""},"subtitle":{"text":""},"xAxis":{"min":0,"max":100,"startOnTick":false,"endOnTick":false,"gridLineWidth":1,"maxPadding":0.2,"title":{"text":"Commonality (Percentile) based on document occurrencee"},"labels":{"format":""}},"yAxis":{"min":0,"max":100,"startOnTick":false,"endOnTick":false,"gridLineWidth":1,"maxPadding":0.2,"title":{"text":"Commonality (Percentile) based on total occurrence"},"labels":{"format":""}},"tooltip":{"useHTML":true,"followPointer":true,"headerFormat":"<table border=0 cellpadding=5 cellspacing=0>","pointFormat":"<tr><th colspan=\"2\" align=\"center\"><h3 style=\"margin: 0; padding: 2;\">{point.title}<\/h3><\/th><\/tr><tr><th colspan=\"2\" align=\"center\" style=\"font-size: 50%;\">{point.variants}<\/th><\/tr><tr><th title=\"Based on How Many Documents This Appeared In\">Commonality (Document Occurrence):<\/th><td align=\"center\">{point.nonstopstem.docquantile} %ile<\/td><\/tr><tr><th title=\"Based on How Many Times This Appeared In All Documents\">Commonality (Total Occurrence):<\/th><td align=\"center\">{point.nonstopstem.totalquantile} %ile<\/td><\/tr><tr><th>Within-Idea Occurrence:<\/th><td align=\"center\">{point.nonstopstem.ideafreq} times<\/td><\/tr>","footerFormat":"<\/table>"},"series":[{"name":"words in idea (1-grams)","data":[{"x":25,"y":35,"z":24,"name":"w-3...","title":"word-3","variants":"[word-3, word-3a]","nonstopstem":{"docquantile":25,"totalquantile":35,"ideafreq":24}}]}],"colors":["#7cb5ec","#f15c80","#B789B6","#7cb5ec","#f15c80","#B789B6","#7cb5ec","#f15c80","#B789B6","#f7a35c","#8085e9","#f15c80","#e4d354","#2b908f","#f45b5b","#91e8e1"],"legend":{"enabled":true},"exporting":{"buttons":{"contextButton":{"align":"left","x":80,"y":0}}}}' --outfile '/path/to/CLI/test.png'  2>&1 
`

When I copy and paste to the CLI, it works as expected... with the same user that did the global install of the server...

`npm install highcharts-export-server -g`

When I try to run via "www-data" as a shell script, I get the error:

`sh: 1: highcharts-export-server: not found`

I don't get it... why can my user run it, but www-data cannot?

**Comment by MonteShaffer** [comment]
`whereis highcharts-export-server`

`~/.nvm/versions/node/v6.9.4/bin/highcharts-export-server`

The full path works for www-data ... I guess "global" doesn't set global envirnoment variables.

STILL NOT LOGGING! ...




`~/.nvm/versions/node/v6.9.4/bin/highcharts-export-server --logLevel 4 --logDest '/path/to/CLI/highcharts.log' --width 1200 --type 'png' --constr 'Chart' --instr '{"internal-key":"freeHighChart","credits":{"enabled":false},"chart":{"type":"bubble","plotBorderWidth":1,"zoomType":"xy","resetZoomButton":{"theme":{"display":"none"},"position":{"align":"left","verticalAlign":"bottom","x":-50,"y":25},"relativeTo":"plot"}},"plotOptions":{"bubble":{"minSize":25,"maxSize":50},"series":{"allowPointSelect":true,"dataLabels":{"format":"{point.name}","enabled":true},"marker":{"states":{"select":{"fillColor":"red","lineWidth":0}}},"point":{"events":{"click":"function(e){ var obj = e.point; doZoom(subsetHighChart, obj.x-1, obj.x+1, obj.y-1, obj.y+1, obj.index, obj.name, obj.nonstopstem.ideafreq);}","select":"function(e){ doZoom(subsetHighChart, e.target.x-1, e.target.x+1, e.target.y-1, e.target.y+1, e.target.index, e.target.name, e.target.nonstopstem.ideafreq); $(\"#idea-tab-free-highchart-search-box\").combobox(\"setText\",e.name); }"}}}},"title":{"text":""},"subtitle":{"text":""},"xAxis":{"min":0,"max":100,"startOnTick":false,"endOnTick":false,"gridLineWidth":1,"maxPadding":0.2,"title":{"text":"Commonality (Percentile) based on document occurrencee"},"labels":{"format":""}},"yAxis":{"min":0,"max":100,"startOnTick":false,"endOnTick":false,"gridLineWidth":1,"maxPadding":0.2,"title":{"text":"Commonality (Percentile) based on total occurrence"},"labels":{"format":""}},"tooltip":{"useHTML":true,"followPointer":true,"headerFormat":"<table border=0 cellpadding=5 cellspacing=0>","pointFormat":"<tr><th colspan=\"2\" align=\"center\"><h3 style=\"margin: 0; padding: 2;\">{point.title}<\/h3><\/th><\/tr><tr><th colspan=\"2\" align=\"center\" style=\"font-size: 50%;\">{point.variants}<\/th><\/tr><tr><th title=\"Based on How Many Documents This Appeared In\">Commonality (Document Occurrence):<\/th><td align=\"center\">{point.nonstopstem.docquantile} %ile<\/td><\/tr><tr><th title=\"Based on How Many Times This Appeared In All Documents\">Commonality (Total Occurrence):<\/th><td align=\"center\">{point.nonstopstem.totalquantile} %ile<\/td><\/tr><tr><th>Within-Idea Occurrence:<\/th><td align=\"center\">{point.nonstopstem.ideafreq} times<\/td><\/tr>","footerFormat":"<\/table>"},"series":[{"name":"words in idea (1-grams)","data":[{"x":25,"y":35,"z":24,"name":"w-3...","title":"word-3","variants":"[word-3, word-3a]","nonstopstem":{"docquantile":25,"totalquantile":35,"ideafreq":24}}]}],"colors":["#7cb5ec","#f15c80","#B789B6","#7cb5ec","#f15c80","#B789B6","#7cb5ec","#f15c80","#B789B6","#f7a35c","#8085e9","#f15c80","#e4d354","#2b908f","#f45b5b","#91e8e1"],"legend":{"enabled":true},"exporting":{"buttons":{"contextButton":{"align":"left","x":80,"y":0}}}}' --outfile '/path/to/CLI/test.png' 2>&1`

**Comment by cvasseng** [comment]
Hi, as you said, `npm install -g` only adds links for the user running the command.

For this particular use case, I'd recommend you clone the repository and run `node bin/cli.js` instead of running `hichcharts-export-server` from the `.nvm` folder, which could have side effects in the form of permission errors when not running it as the user who did the npm install.

For the logging: I'm assuming what you have issues with is the file logging? Does the user you're running it as have write permissions to the path you're supplying to `--logDest`?

**Comment by MonteShaffer** [comment]
I currently have it working via the full "bin" path for user "www-data" with my -g install.  I will revert to node bin/cli.js if need be, but currently, it appears to be working as expected.

The logging is just strange... apparently logDest is a folder, not a file... and in that folder, it creates another folder "logs" and places a file [with mispelling] higcharts-export-server.log in the new folder.  This is probably why I am getting my "write permissions" all messed up.  I created the folder, and even touched a file for the log, and I want highchartst to log to the specified full path-log file, and the system is doing its own arbitrary thing.

In addition, even though I specify logLevel 4, which includes verbose, this logging does not include [verbose] messages that appear on the CLI.

**Comment by cvasseng** [comment]
Gotcha.

`-logDest` is a path as you say, and should not include the filename. 

There was a race condition for output - it tried outputting log lines before the log file had been created, and the path had been verified. This is what caused the verbose output to disappear, as they were all coincidentally outputted before the file was ready. Fixed in 485564d. 

The filename can be set separately using the `-logFile` option (added in 485564d, defaults to `highcharts-export-server.log`).  

Changes have also been pushed to NPM (version 1.0.5).

Feel free to re-open this if you experience further issues with logging.
