### ISSUE TITLE
ACCEPT_HIGHCHARTS_LICENSE and Optionals (Worldcloud, Annotations)

### ISSUE THREAD

**Issue by aNieto2k** [highcharts/node-export-server#142]
#### Expected behaviour
Hi, 

When I use the **ACCEPT_HIGHCHARTS_LICENSE** in a Heroku, the `build.js` doesn't include the optionals scripts (_wordcloud_ and _annotations_).

#### Actual behaviour
![image](https://user-images.githubusercontent.com/44778/40611261-e2d20d1c-6275-11e8-8979-3328aefd53fb.png)

I see the "problem" was there, when the environment variable is setted it never call the getOptionals() function as startPrompt() way.

![image](https://user-images.githubusercontent.com/44778/40611447-a079bb80-6276-11e8-95c9-dd06a94f41a4.png)

I made a fork with this solution to solve the problem until the "problem" is solved

![image](https://user-images.githubusercontent.com/44778/40611410-821a203a-6276-11e8-9090-97f428db88c1.png)

Sorry for my English 😔

Thanks!

**Comment by PaulDalek** [comment]
This issue refers to the old version of PhantomJS based export server. In the new version, based on Puppeteer, this issue doesn't occur and creating a chart with a `wordcloud` series is not a problem.
