### ISSUE TITLE
Missing lines in charts with patterns

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/node-export-server#143]
It appears that internal URL references as stroke values are not always applied successfully by the server.

This manifests as missing lines in charts for certain datasets when pattern fills are used. Example using official server: http://jsfiddle.net/7e9we1hh/.

The SVG sent to the server seems to be correct, and using the [offline-exporting module](https://www.highcharts.com/docs/export-module/client-side-export) works.

**Comment by PaulDalek** [comment]
It looks like it works when exporting using Puppeteer based server:
![chart](https://user-images.githubusercontent.com/19933566/170554105-7a94e065-c92c-47bc-bea7-546ae96558b1.png)
