### ISSUE TITLE
error HPE_INVALID_METHOD,

### ISSUE THREAD

**Issue by shivajain** [highcharts/node-export-server#145]
I have installed highchart export server successfully, and tried to run the command to enable http server.

I've started the node server by command: highcharts-export-server --enableServer 1 --host localhost --port 3003--logLevel 4 -  server started successfully.

When I sent request through postman application, I am getting this error:
`Thu Jun 07 2018 15:01:10 GMT+0530 (India Standard Time) [error] socket error: { Error: Parse Error, bytesParsed: 0, code: 'HPE_INVALID_METHOD', Packet:<Buffer 16 03 01 02 00 01 00 01 fc 03 03 74 3d ad 38 d0 cb 27 88 ec 95 9b c7 4c 87 9a 09 ed 26 7e ad 74 5d 90 50 7c ba ec 7d 26 28 c1 b1 20 3d f3 80 05 92 54 .. > }`

My Postman request is : 
URL: https://localhost:3003 
Content-Type:application/json
Body: `{
    "xAxis": {
        "categories": [
            "Jan",
            "Feb",
            "Mar",
            "Apr",
            "May",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
            "Oct",
            "Nov",
            "Dec"
        ]x
    },
    "series": [
        {
            "data": [1,3,2,4],
            "type": "line"
        },
        {
            "data": [5,3,4,2],
            "type":"line"
        }
    ]
}
`

I am struggling with this error, it seems I am missing something in request, dont know how to proceed.

Any help would be appreciated.

**Comment by cvasseng** [comment]
Your JSON is malformed - you have an `x` character between the end of the category array, and the end of the `xAxis` body ("Sep", "Oct", "Nov", "Dec" ]**x** }, "series"). 

You also need to put the chart options into the `options` attribute:

e.g:
```
{
  "type": "png",
  "options": {
    "xAxis": {
      "categories": [
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec"
      ]
    },
    "series": [
      {
        "data": [
          1,
          3,
          2,
          4
        ],
        "type": "line"
      },
      {
        "data": [
          5,
          3,
          4,
          2
        ],
        "type": "line"
      }
    ]
  }
}
```
