### ISSUE TITLE
Forever command documentation slightly incorrect

### ISSUE THREAD

**Issue by Chris-Pratt-Clystnet** [highcharts/node-export-server#147]
#### Expected behaviour
When you run "forever stopall" the main process and all workers should stop.

#### Actual behaviour
The main process stops but the workers do not and the workers start using larger amounts of CPU

#### Reproduction steps
Run "forever start ./bin/cli.js --enableServer 1 --killSignal SIGINT"
Then run "forever stopall"

#### Solution
Change the start command to "forever start --killSignal SIGINT ./bin/cli.js --enableServer 1".

This is because having the "--killSignal SIGINT" at the end made that option get included in the command for forever to run instead of setting the kill signal for forever to attach to each process.

**Comment by cvasseng** [comment]
Thanks for letting us know!

I've updated the readme.
