### ISSUE TITLE
Any SVG render example available?

### ISSUE THREAD

**Issue by bfang711** [highcharts/node-export-server#149]
in HTTP server mode, I see there is parameter svg: A string containing SVG to render. 
However is there any example for that you can share with us?

Basically, in browser, I am using the following code to draw a path.
`var renderer = new Highcharts.Renderer();
var group = renderer.g().add();
renderer.path(xxxx).add(group);`

Is there anyway to let server to render this SVG, and use it in browser? The reason I want to do this is that 1. the SVG is pretty complicated, 2. since I need to reuse this SVG multiple times, I would server to generate it once and be used multiple times by browser.

thank you.

**Comment by cvasseng** [comment]
The SVG parameter accepts regular SVG, i.e. XML, so to use it to convert to SVG would be redundant as you need the SVG to begin with to use it.

If you need to reuse the result of using the raw renderer interface, it's better to create a function for it that you can call to apply it to wherever you need to apply it. If you just need the raw SVG and not a converted, rasterized, image, you can copy it from the page itself using the inspector in the browser dev tools.
