### ISSUE TITLE
Export Server Connection Error

### ISSUE THREAD

**Issue by sharadkejriwal** [highcharts/node-export-server#150]
#### Actual behaviour

I am using Node Export Server. But, on sending request to the server with same input data, I am getting frequent connection error with the below error. The below error **does not occur always** but is very frequent and succeeds on retrying.

The error that I am getting with Inner Exception: 

**The underlying connection was closed: An unexpected error occurred on a receive.

Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

An existing connection was forcibly closed by the remote host

ErrorCode: 10054
Nativeerrorcode : 10054
SocketErrorCode : ConnectionReset**

**Comment by sharadkejriwal** [comment]
Can you please tell the possible causes? I am running Node Server on localhost without ssl cert (http).

**Comment by sharadkejriwal** [comment]
This has been solved. I removed RedirectStandardInput,RedirectStandaradOutput,RedirectStandardError from Process startinfo and it is working perfectly now.

**Comment by KacperMadej** [comment]
Thank you for sharing your solution.
