### ISSUE TITLE
"no data to display" module not work

### ISSUE THREAD

**Issue by iceking2001** [highcharts/node-export-server#151]
When i send a json string with null data to export server this:
curl -H "Content-Type: application/json" -X POST -d '{"resources":{"files":"no-data-to-display.js"}, "infile":{"title": {"text": "Steep Chart"}, "xAxis": {"categories": ["Jan", "Feb", "Mar"]}, "series": [{**"data": []**}]}}' 127.0.0.1:7801 -o mychart.png
And I have add the no-data-to-display.js in resource, but the png did not show the default no data string in the image.

**Comment by iceking2001** [comment]
I have solve this issue by replace send "files" with "js", but it looks ugly: 

curl -H "Content-Type: application/json" -X POST -d '{"resources":{"js":"(function(d){\"object\"===typeof module&&module.exports?module.exports=d:d(Highcharts)})(function(d){(function(c){var d=c.seriesTypes,e=c.Chart.prototype,f=c.getOptions(),g=c.extend,h=c.each;g(f.lang,{noData:\"No data to display\"});f.noData={position:{x:0,y:0,align:\"center\",verticalAlign:\"middle\"}};f.noData.style={fontWeight:\"bold\",fontSize:\"12px\",color:\"#666666\"};h(\"bubble gauge heatmap pie sankey treemap waterfall\".split(\" \"),function(b){d[b]&&(d[b].prototype.hasData=function(){return!!this.points.length})}); c.Series.prototype.hasData=function(){return this.visible&&void 0!==this.dataMax&&void 0!==this.dataMin};e.showNoData=function(b){var a=this.options;b=b||a&&a.lang.noData;a=a&&a.noData;!this.noDataLabel&&this.renderer&&(this.noDataLabel=this.renderer.label(b,0,0,null,null,null,a.useHTML,null,\"no-data\"),this.noDataLabel.attr(a.attr).css(a.style),this.noDataLabel.add(),this.noDataLabel.align(g(this.noDataLabel.getBBox(),a.position),!1,\"plotBox\"))};e.hideNoData=function(){this.noDataLabel&&(this.noDataLabel= this.noDataLabel.destroy())};e.hasData=function(){for(var b=this.series||[],a=b.length;a--;)if(b[a].hasData()&&!b[a].options.isInternal)return!0;return this.loadingShown};c.addEvent(c.Chart,\"render\",function(){this.hasData()?this.hideNoData():this.showNoData()})})(d)});"}, "infile":{"title": {"text": "Steep Chart"}, "xAxis": {"categories": ["Jan", "Feb", "Mar"]}, "series": [{"data": []}]}}' 127.0.0.1:7801 -o mychart.png

**Comment by DmitryRibalka** [comment]
This helped me:
... -X POST -d '{"resources": {"files": "node_modules/highcharts-no-data-to-display/no-data-to-display.js"}}' ....

**Comment by KacperMadej** [comment]
Here's a related issue: https://github.com/highcharts/node-export-server/issues/156
That one is bigger, so let's keep this one closed.
