### ISSUE TITLE
Server is not able to export a 'bullet' chart type.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/node-export-server#157]
#### Expected behaviour

Server should export the expected chart.

#### Actual behaviour

Server returns **Error: Highcharts error #17**, because it doesn't recognize `bullet` chart type.

#### Reproduction steps
Try to provide the `node-export-server` with chart configuration below:
```js
{
    chart: {
        type: 'bullet',
    },
    series: [{
        data: [{
            y: 275,
            target: 250
        }]
    }],
    plotOptions: {
        series: {
            targetOptions: {
                width: '200%'
            }
        }
    }
}
```

**Comment by ifree92** [comment]
Great!
Could you please merge it with master and push it into npm repository.. to be able to use that.
Thank you.

**Comment by ifree92** [comment]
I'll be waiting for merging this changes into master branch and push it to npm repository

**Comment by KacperMadej** [comment]
_Internal note:_ Bullet is not the only module missing - see https://github.com/highcharts/node-export-server/issues/156#issuecomment-410988680
