### ISSUE TITLE
Server doesn't export data - 'wordcloud' chart type.

### ISSUE THREAD

**Issue by wchmiel** [highcharts/node-export-server#162]
#### Expected behaviour
Server should export chart properly.

#### Actual behaviour
Server exports empty chart (data is not exported).

#### Reproduction steps
`curl -H "Content-"ype: application/json" -X POST"-d '{"infile":{"series":[{"data": [["Aenean",1],["Curabitur",2],["Donec",1]],"type":"wordcloud"}],"title":{"text":"Wordcloud of Lorem Ipsum"}}}' 127.0.0.1:7801 -o mychart1.png`

**Comment by eydreeyawn** [comment]
I'm having the same problem.

**Comment by PaulDalek** [comment]
With a Puppeteer version it is possible now to create the `wordcloud` chart.
