### ISSUE TITLE
highcharts-export-server not working on live server in nodejs

### ISSUE THREAD

**Issue by apurv195** [highcharts/node-export-server#174]
1. i am using highcharts-export-server for Export the report from node side.

2. it's working fine in my Local Machine, but got Error on Live Server, "ERROR: error when performing chart generation: please check your input data"

3. node-version (Local) => v8.9.3, node-version (Server) => v8.12.0
npm-version (Local) => 5.5.1, npm-version (Local) => 6.4.1

4. i'm using "highcharts-export-server": "https://github.com/dhyey35/highcharts-export-server"

**is there anything missing to install on Live Server??**

**Comment by lukos** [comment]
There is nothing different running in production. The obvious issue is that you are not sending the same content to both places. Another possibility is that some cache or proxy has modified the request in some way.

Best way to test will be to exec into the production container and run your curl command directly against the local host. This way you can remove all of the external variables and see whether the container itself is working.
