### ISSUE TITLE
Support JavaScript as an input

### ISSUE THREAD

**Issue by dsu-inf** [highcharts/node-export-server#177]
Can you confirm that node export server still doesn't support JavaScript as an input?

I have a very simple JSON input file (`highcharts-test.json`) with the content:
```json
{"infile":{"title": {"text": "Steep Chart"}, "xAxis": {"categories": ["Jan", "Feb", "Mar"], "labels": {"formatter": "function(){return 'test';}"}}, "series": [{"data": [29.9, 71.5, 106.4]}]}}
```

To generate the image of chart I use `curl`:
```bash
curl -H "Content-Type: application/json" -X POST -d @highcharts-test.json export.highcharts.com -o chart123.png
```

The response returned by `export.highcharts.com` is a image with an error:
![image](https://user-images.githubusercontent.com/45175580/48718299-c650e180-ec23-11e8-8a5f-8b09793fe770.png)

I verified that JSON is valid using https://jsonlint.com:
![image](https://user-images.githubusercontent.com/45175580/48718407-fe582480-ec23-11e8-86f6-b5999d920ee1.png)

The JSON fragment that generates the problem is the JavaScript function from `labels` field:
```
"labels": {"formatter": "function(){return 'test';}"}}
```

In other test use case, I verified that I can pass a JavaScript function for `tooltip` (formatter) field. Everything was OK.
So my question is:
Does Node Export Server support JavaScript (function) as an input?

**Comment by dsu-inf** [comment]
I come with another observation.
If I copy/paste the JSON (without "infile" field and **WITHOUT** quotes around function) on `export.highcharts.com` and press "Preview" button, then the chart is generated correct:
![image](https://user-images.githubusercontent.com/45175580/48769232-c7395000-ecc3-11e8-9524-a350aae102d0.png)
```
{"title": {"text": "Steep Chart"}, "xAxis": {"categories": ["Jan", "Feb", "Mar"], "labels": {"formatter": function(){return 'test';}}}, "series": [{"data": [29.9, 71.5, 106.4]}]}
```

But, if I remove the quotes around function and run my test via curl then the image is not generated.
The result is a JSON parser exception:
![image](https://user-images.githubusercontent.com/45175580/48769481-72e2a000-ecc4-11e8-95c9-26e2fcb78ea9.png)
```
{"infile":{"title": {"text": "Steep Chart"}, "xAxis": {"categories": ["Jan", "Feb", "Mar"], "labels": {"formatter": function(){return 'test';}}}, "series": [{"data": [29.9, 71.5, 106.4]}]}}
```

**Comment by KacperMadej** [comment]
Hi @dsu-inf 

If you are working on Windows then you could try request in a format like the one below (it worked for me on Win10):
`curl -H "Content-Type: application/json" -X POST -d "{\"infile\":\"{plotOptions:{series:{dataLabels:{enabled:true,formatter:function() { if (4 - 5) { return 'dl'; } else { return 'not'; } }}}}, series:[{data:[3,2,2,4]}]}\"}" 127.0.0.1:7801 -o mychart64.png`

**Comment by dsu-inf** [comment]
Hi @KacperMadej 

I can confirm that after I modified a little bit my initial example, it works an an image is generated:
```
curl -H "Content-Type: application/json" -X POST -d "{\"infile\":\"{title: {text: 'Steep Chart'}, xAxis: {categories: ['Jan', 'Feb', 'Mar'], labels: {formatter: function(){return 'test';}}}, series: [{data: [29.9, 71.5, 106.4]}]}\"}" 127.0.0.1:7801 -o mychart64.png
```

So, now, the content of `highcharts-test.json` (the input file) is:
```
{"infile":"{title: {text: 'Steep Chart'}, xAxis: {categories: ['Jan', 'Feb', 'Mar'], labels: {formatter: function(){return 'test';}}}, series: [{data: [29.9, 71.5, 106.4]}]}"}
```

It's a problem that my JSON is generated automatically using a Java library (JSON.org), in the standard JSON format (with `"`). I will take a look to see how I can convert the output JSON in the format agreed by Highcharts export server as input file.

**Comment by dsu-inf** [comment]
In the end I succeeded, but it was a lot of work. My request was for a generic case (a web dashboard with charts that is saved as PDF). I solved with regular expressions. I am not happy that I must to process the JSON before to send it as input to Highcharts export server.
