### ISSUE TITLE
highcharts-export-server server mode does not work

### ISSUE THREAD

**Issue by falcon123** [highcharts/node-export-server#19]
Steps followed:
`> sudo npm install highcharts-export-server -g`
`> highcharts-export-server --enableServer 1`
`> curl -H "Content-Type: application/json" -X POST -d '{"infile":{"title": {"text": "Steep Chart"}, "xAxis": {"categories": ["Jan", "Feb", "Mar"]}, "series": [{"data": [29.9, 71.5, 106.4]}]}}' 127.0.0.1:7801 -o mychart.png`

Now I get the following error in the highcharts export server and it quits immediately:

`uncaughtException: [TypeError: undefined is not a function]`

Also the phantomjs instances created are not killed.

**Comment by cvasseng** [comment]
Hi,

I'm unable to reproduce this locally.

Which OS are you running? Could you try starting the server with `highcharts-export-server --enableServer 1 --logLevel 4` and see if you get a more detailed error?

**Comment by falcon123** [comment]
I am running OS X Yosemite(10.10.5). I tried with loglevel 4 and this is what I got:

`Mon Jan 30 2017 19:39:33 GMT+0530 (IST) [verbose] Pool started:
    maxWorkers: 4
    initialWorkers: 4
    workLimit: 60
Mon Jan 30 2017 19:39:33 GMT+0530 (IST) [verbose] phantom 1 - spawning worker
Mon Jan 30 2017 19:39:33 GMT+0530 (IST) [verbose] phantom 2 - spawning worker
Mon Jan 30 2017 19:39:33 GMT+0530 (IST) [verbose] phantom 3 - spawning worker
Mon Jan 30 2017 19:39:33 GMT+0530 (IST) [verbose] phantom 4 - spawning worker
Mon Jan 30 2017 19:39:33 GMT+0530 (IST) [notice] http server started on port 7801
Mon Jan 30 2017 19:39:36 GMT+0530 (IST) [verbose] reaper checking for timed out phantom processes
Mon Jan 30 2017 19:39:38 GMT+0530 (IST) [verbose] reaper checking for timed out phantom processes
Mon Jan 30 2017 19:40:09 GMT+0530 (IST) [verbose] reaper checking for timed out phantom processes
Mon Jan 30 2017 19:40:11 GMT+0530 (IST) [verbose] reaper checking for timed out phantom processes
Mon Jan 30 2017 19:40:14 GMT+0530 (IST) [verbose] reaper checking for timed out phantom processes
Mon Jan 30 2017 19:40:15 GMT+0530 (IST) [verbose] got incoming HTTP request 4d7789358db4409099433f2cf74ed5b7
Mon Jan 30 2017 19:40:15 GMT+0530 (IST) [verbose] starting export
Mon Jan 30 2017 19:40:15 GMT+0530 (IST) [verbose] attempting to export from raw input
Mon Jan 30 2017 19:40:15 GMT+0530 (IST) [verbose] phantom - received work, finding available worker
Mon Jan 30 2017 19:40:15 GMT+0530 (IST) [verbose] phantom - found available worker
Mon Jan 30 2017 19:40:15 GMT+0530 (IST) [verbose] phantom 2 - starting work
Mon Jan 30 2017 19:40:15 GMT+0530 (IST) [notice] phantom worker 2 finished work 4d7789358db4409099433f2cf74ed5b7 in 208 ms
uncaughtException: [TypeError: undefined is not a function]
Mon Jan 30 2017 19:40:15 GMT+0530 (IST) [notice] terminating, killing all running phantom processes`

**Comment by cvasseng** [comment]
Which version of node are you running?

I'm still not able to reproduce on OSX 10.11.5. Unfortunately, I don't have access to a machine running 10.10.5, so I can't check if it has something to do with that.

**Comment by falcon123** [comment]
I am not sure what the issue is. It works in Ubuntu but not my OS X
