### ISSUE TITLE
Server ignores css files when rendering a chart to a picture

### ISSUE THREAD

**Issue by ClemensSchwarz** [highcharts/node-export-server#193]
#### Expected behaviour
the charts are formatted (e.g. the colors from the css instead "standard colors")

#### Actual behaviour
css seems to be ignored

#### Reproduction steps
 
we use the node-export-server to create a picture of the chart
example:
{"options":"{       chart: {    styledMode: false  },  title: {    text: 'Highcharts pie chart'  },  xAxis: {    categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov','Dec']  },  series: [{    type: 'pie',    allowPointSelect: true,    keys: ['name', 'y', 'selected', 'sliced'],    data: [      ['Apples', 29.9, false],      ['Pears', 71.5,false],      ['Oranges', 106.4, false],      ['Plums', 129.2, false],      ['Bananas', 144.0, false],      ['Peaches', 176.0, false],      ['Prunes', 135.6, true, true],     ['Avocados', 148.5, false]    ],    showInLegend: true  }] }","resource": {"css":"@import 'http://localhost:8080/css/test.css' "},"constr":"Chart"}

the css-file test.css seems to be ignored from the server when creating the output.png

Is the parameter wrong ?
I also found the "resource" : "files" : "test.css" option - in which folder of the server do I have to put the file ?

**Comment by KacperMadej** [comment]
Hi @ClemensSchwarz 

There might be a docs typo, please try with `resources` (plural).
Please try increasing the log level (--logLevel) to track if everything goes as is should.

P.S. I have send you similar message by e-mail regarding our e-mail exchange through Highcharts technical support.

**Comment by ClemensSchwarz** [comment]
thank you for your feedback - I changed the parameter to:
"resources": {"files":"test.css" } and put the file in the phantom-folder
now the server seems to read the file but I receicve the error: an error occured when rendering the chart: SyntaxError: Unexpected token S in JSON at position 0

Is a parameter missing ? or do I have to change the css (are there special tags for the node-server in a css file)   ?

[test.zip](https://github.com/highcharts/node-export-server/files/3053494/test.zip)

**Comment by KacperMadej** [comment]
The file is not a correct CSS file. It doesn't work in a demo too - http://jsfiddle.net/BlackLabel/j7kt0a3b/

**Comment by ClemensSchwarz** [comment]
I created a very simple css file (test2.css) which works on the jsfiddle.net site
I put it in the phantom-folder and changed to parameter "resources": {"files":"test2.css" }

when running the file on the node-export-server there is still the error "SyntaxError: Unexpected token S in JSON at position 0"

[test2.zip](https://github.com/highcharts/node-export-server/files/3054086/test2.zip)

**Comment by KacperMadej** [comment]
@cvasseng Is there a change in the export server since style mode in Highcharts doesn't require different core? Is there any docs about styled mode usage?

**Comment by ClemensSchwarz** [comment]
[example.txt](https://github.com/highcharts/node-export-server/files/3117503/example.txt)
I created another simple example (example.txt with css-definition directly in the css-tag "resources": {"css": ...} 
![example](https://user-images.githubusercontent.com/49311885/56745527-d04eb180-677a-11e9-9e82-2c6995bdee3c.png)

when running on the server I was able to create a picture - but the axis and the line have different colors (e.g. blue vs. dark blue)

Do you have an idea to solve the problem ?

**Comment by ClemensSchwarz** [comment]
To clarify the problem:
![pic2](https://user-images.githubusercontent.com/49311885/56805459-6d682380-6829-11e9-87da-7c4a0d7f9bee.PNG)
the value-lines and the axis-label line have different colors (dark blue vs. light blue)

**Comment by KacperMadej** [comment]
@kai2468 Could you take a look at this problem about the export server?

**Comment by cvasseng** [comment]
@KacperMadej it has not been updated to use the new styled mode setup (i.e. config instead of separate bundle). This issue however, seems to be related to not enabling styled mode by setting `styledMode` to `true`:

```
{
  "options": "{ chart: { styledMode: false }, title: { text: 'Highcharts pie chart' }, xAxis: { categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov','Dec'] }, series: [{ type: 'pie', allowPointSelect: true, keys: ['name', 'y', 'selected', 'sliced'], data: [ ['Apples', 29.9, false], ['Pears', 71.5,false], ['Oranges', 106.4, false], ['Plums', 129.2, false], ['Bananas', 144.0, false], ['Peaches', 176.0, false], ['Prunes', 135.6, true, true], ['Avocados', 148.5, false] ], showInLegend: true }] }",
  "resource": { "css": "@import 'http://localhost:8080/css/test.css' " },
  "constr": "Chart",
  "styledMode": true
}
```

**Comment by ClemensSchwarz** [comment]
Is it a bug in the highcharts-server or a parameter-problem? Can I try something else? The error (wrong colors or different colors in axis labels and lines) also occurs in our production environment - we need a solution very quickly.

**Comment by cvasseng** [comment]
Hi, did you try setting `styledMode` to `true`?

If that doesn't help, please try the latest version which was just published (`2.0.19`) as it contains a fix for an issue that may have impacted you.

**Comment by ClemensSchwarz** [comment]
Hi, I installed the latest Version v2.0.24 and tried the setting `styledMode` `true` which raises the error "SyntaxError: Unexpected token T in JSON at position 0" - please find the log attached

I installed the server via
`npm install highcharts-export-server -g `
and started it via
[styledmode-json.txt](https://github.com/highcharts/node-export-server/files/3161057/styledmode-json.txt)
[error_styledMode.log](https://github.com/highcharts/node-export-server/files/3161058/error_styledMode.log)


`highcharts-export-server --enableServer 1`

do I have to change a parameter ? maybe there is something missing via Installation ?

**Comment by DavidLea99** [comment]
@ClemensSchwarz maybe you should escape your single quotes in json file. eg: ' -> \"

**Comment by DavidLea99** [comment]
['Apr. 15', 'Mai 15', 'Juni 15', 'Juli 15', 'Aug. 15', 'Sep. 15', 'Okt. 15', 'Nov. 15', 'Dez. 15', ] the last comma should be removed, and the last comma in a json object is also same.

**Comment by ClemensSchwarz** [comment]
I checked the commas etc. and changed the css folder

**Comment by ClemensSchwarz** [comment]
thank you for your assistance
