### ISSUE TITLE
Server seems not to be able to export a 'pareto' chart type

### ISSUE THREAD

**Issue by giordy** [highcharts/node-export-server#196]
#### Expected behaviour
The server should export the Pareto chart

#### Actual behaviour
I'm obtaining the error https://www.highcharts.com/errors/17/

#### Reproduction steps
I was trying to generate a chart roughly similar to the one presented in demo: https://www.highcharts.com/demo/pareto

However I'm getting the error and I cannot get the chart.
You can try yourself on https://export.highcharts.com/ and paste the configuration taken from the demo page:

```
{
    chart: {
        renderTo: 'container',
        type: 'column'
    },
    title: {
        text: 'Restaurants Complaints'
    },
    tooltip: {
        shared: true
    },
    xAxis: {
        categories: [
            'Overpriced',
            'Small portions',
            'Wait time',
            'Food is tasteless',
            'No atmosphere',
            'Not clean',
            'Too noisy',
            'Unfriendly staff'
        ],
        crosshair: true
    },
    yAxis: [{
        title: {
            text: ''
        }
    }, {
        title: {
            text: ''
        },
        minPadding: 0,
        maxPadding: 0,
        max: 100,
        min: 0,
        opposite: true,
        labels: {
            format: "{value}%"
        }
    }],
    series: [{
        type: 'pareto',
        name: 'Pareto',
        yAxis: 1,
        zIndex: 10,
        baseSeries: 1
    }, {
        name: 'Complaints',
        type: 'column',
        zIndex: 2,
        data: [755, 222, 151, 86, 72, 51, 36, 10]
    }]
}
```

**Comment by pawelfus** [comment]
Hi @giordy 

Thanks for reporting this issue! You are right, `pareto` series is missing from exporting.

*Internal note:*
It's not listed here:
https://github.com/highcharts/node-export-server/blob/master/build.js#L41-L55

**Comment by cvasseng** [comment]
`pareto` series support added in `2.0.19` which was just published. Sorry for the delay!
