### ISSUE TITLE
Custom node export server setup with github node-export-server cloned repo not working as expected

### ISSUE THREAD

**Issue by sathyarajagopal** [highcharts/node-export-server#198]
#### Expected behaviour
After deploying my custom node export server, I should be able to do GET on "/health" and POST requests on "/".

#### Actual behaviour
I am able to do GET request but POST requests are not working. POST request runs for a long time and eventually responds with Internal Server Error.

#### Reproduction steps
Setup method 1:

1. Ran npm install highcharts-export-server -g command.
2. Ran highcharts-export-server --enableServer 1 --port 8080

I am able to make successful POST request with chart option json using postman. The POST URL is https://mydomain.myorg.net

Setup method 2:

1. Cloned highcharts node export server repo from GitHub.
2. Ran npm install && npm link commands.
3. Ran highcharts-export-server --enableServer 1 --port 8080

I am unable to make successful POST requests. The POST URL is https://mydomain.myorg.net. The requests runs for a long time and eventually throws Internal Server Error. In the highcharts log, I am seeing the error as the client closed the connection before the chart was done processing. But the http request in postman is still pending. The deployed app is running in a docker container on our internal cloud behind load balancer.

curl -H "Content-Type: application/json" -X POST -d "{\"infile\":{\"title\": {\"text\": \"Steep Chart\"}, \"xAxis\": {\"categories\": [\"Jan\", \"Feb\", \"Mar\"]}, \"series\": [{\"data\": [29.9, 71.5, 106.4]}]},\"constr\": \"Chart\", \"type\": \"svg\"}" -k https://mydomain.myorg.net -o c:\temp\mychart.svg

**Comment by sathyarajagopal** [comment]
Is this forum active? Can someone look into this issue that I am facing?

**Comment by nic96t** [comment]
I just ran into the same problem. It was working for a while, but now all of a sudden it's broken. Possibly after installing a few updates.

**Comment by PaulDalek** [comment]
Hi @nic96t

Thank you for contacting us and reporting this issue. Could you please provide me with more information such as how you install and configure your server along with the method of exporting charts. Also, please send a chart configuration and the command that you use to send the POST request. Finally, provide me with the error that you receive. Thanks.

**Comment by nic96t** [comment]
Installing the latest nodejs lts version for my distro fixed it.  Which is currently version 14.15.4 instead of the latest which is 15.5.1

**Comment by PaulDalek** [comment]
Ok, thanks for the information.

**Comment by koushers767** [comment]
@PaulDalek I am running into same issue with the version 16.14.0, The last version i could run the export server is 15.14.0 will there be a fix in the latest version or could you help us to find the most recent version other than 15.x which is running export server.

**Comment by chrisunl** [comment]
I have the same issue, using node 15.14.0 as a work around. Is this ticket closed as in will not fix?
