### ISSUE TITLE
Maps module

### ISSUE THREAD

**Issue by jb3-2** [highcharts/node-export-server#2]
Hi,

This project looks very promising! I don't see all modules loaded, for our project we need the maps module. Will this also be included?

Thanks and keep up the great work!
J.

**Comment by cvasseng** [comment]
Hi!

Thanks for the kind words! 

And yes - the map module will definitely be an (optional) part of it in the not so distant future. 

If you want to use it with maps right away, you clone the repository and add it to build.js in the cdnScriptsCommon array [here](https://github.com/highcharts/node-export-server/blob/master/build.js#L38), and then run "node build.js". You should then be able to use it by setting the constr attribute to "Maps" when converting. 

I'm leaving this open as a note to self and so I can notify you when it's included.

**Comment by cvasseng** [comment]
Maps is now supported. 

When running npm install (or node build.js) it will prompt if it should include maps, so if the server has already been installed it either needs to be re-installed (if installed with NPM), or `node build.js` needs to be ran in the project root.
