### ISSUE TITLE
Node highcharts export server mappoint is not rendering in png

### ISSUE THREAD

**Issue by dharmarajan** [highcharts/node-export-server#205]
I'm trying to export map as PNG using node-export-server. The map is rendering properly. But the mappoint is not rendering in png.  The same code is working as expeced in web.

Code Snippets:
`"marker": {"enabled":true,"radius":2,"symbol":"triangle","width":40,"height":40}`

![result](https://user-images.githubusercontent.com/11973262/60429395-9d141d00-9c18-11e9-882e-75daf718bf01.png)

Whole Series data which I used: 
[series_data.txt](https://github.com/highcharts/node-export-server/files/3345132/series_data.txt)

**Comment by PaulDalek** [comment]
Tested on the https://github.com/highcharts/node-export-server/tree/enhancement/puppeteer branch and it works as expected.
![chart](https://user-images.githubusercontent.com/19933566/170724118-c73cb34d-207e-45dd-aa18-f37468cafeb0.png)
