### ISSUE TITLE
Export by Node module / CLI returns black images

### ISSUE THREAD

**Issue by spyx08** [highcharts/node-export-server#207]
I'm facing issues with generating image via highcharts-export-server. I'm always getting blank/black images by using the example json data. 

#### Expected behaviour
Chart preview image on CLI/Node module

#### Actual behaviour
Blank/Black images

#### Reproduction steps
 

A basic NodeJS server with highcharts-export-server and express as dependencies.
I tried with latest version of highcharts and specific (5.0.14) and get always the same behaviour. (with CLI too). 

Example of what I have: 

package.json

```
"dependencies": {
    "express": "^4.17.1",
    "highcharts-export-server": "^2.0.24"
  }
```

index.js
```
const express = require('express')
const app = express();
const fs = require('fs')
const path = require('path');

const chartDir = path.join(__dirname,"ChartData")

const chartExporter = require("highcharts-export-server");
// Initialize the exporter
chartExporter.initPool();

app.get("/",(req,resp) => {
    const chartDetails = {
    type: 'png',
    options: {
        title: {
            text: 'My Chart'
        },
        xAxis: {
            categories: ["Jan", "Feb", "Mar", "Apr", "Mar", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
        },
        series: [
            {
                type: 'line',
                data: [1, 3, 2, 4]
            },
            {
                type: 'line',
                data: [5, 3, 4, 2]
            }
        ]
       }
     };
    chartExporter.export(chartDetails, (err, res) => {
        // Get the image data (base64)
        let imageb64 = res.data;
        // Filename of the output
        let outputFile = "bar.png";
        // Save the image to file
        fs.writeFileSync(outputFile, imageb64, "base64", function(err) {
            if (err) console.log(err);
        });
        console.log("Saved image!");
        chartExporter.killPool();
        resp.status(200).send();
     });
}) 
```

I was wondering a bad injection of highcharts but get no errors/logs and I saw in the documentation that it was automatic 

**UPDATE**

I tried same code on Mac and it works. Both are new projects without other dependencies. 
Tested on 2 different windows, same issue

**Comment by raf18seb** [comment]
+1
Same issue on Windows 10

**Comment by Carlospow** [comment]
+1 Got the same issue on Ubuntu 18.04 with version 2.0.24. As @raf18seb said, installing with default options fixes the problem

**Comment by iamonlysaiful** [comment]
Thanks raf18seb  save my day.
