### ISSUE TITLE
XSS vulnerability when exporting SVG

### ISSUE THREAD

**Issue by jurruh** [highcharts/node-export-server#209]
In exported SVG files script tags are not escaped, this can lead to potential XSS attacks.

#### Expected behaviour
Script tags are escaped.

#### Actual behaviour
![image](https://user-images.githubusercontent.com/7419259/61224708-5d245e00-a71f-11e9-8d20-2aa8dc577db2.png)

#### Reproduction steps
curl -X POST \
  http://localhost:7801 \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'cache-control: no-cache' \
  -d 'content=svg&svg=%3Csvg%20xmlns%3Axlink%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxlink%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20version%3D%221.1%22%20width%3D%22837%22%20height%3D%22300%22%3E%0A%20%20%3Cscript%3Ealert(1)%3C%2Fscript%3E%0A%3C%2Fsvg%3E&type=image%2Fsvg%2Bxml&constr=Chart&undefined=' \
  -o out.svg

**Comment by jakubSzuminski** [comment]
I've run this request and, unfortunately, it still seems to be an issue in the latest puppeteer version. I believe we should escape the `<script>` tags just like you described.

What do you think @cvasseng? If this is a serious issue then maybe we should prioritize it?
