### ISSUE TITLE
In newer versions !=2.14 , two plot lines cannot be rendered

### ISSUE THREAD

**Issue by johnpeterdev** [highcharts/node-export-server#213]
#### Expected behaviour
Two plot lines should be rendered 
![image](https://user-images.githubusercontent.com/15850434/62220580-df469080-b375-11e9-9820-f03ad61308c8.png)
#### Actual behaviour
only one is rendered

![image](https://user-images.githubusercontent.com/15850434/62220627-f7b6ab00-b375-11e9-8280-1072d6caf74f.png)

#### Reproduction steps
```json
{"infile":{
  "chart" : {
    "backgroundColor" : "#ffffff",
    "width" : 900
  },
  "series" : [ {
    "name" : "var1",
    "type" : "column",
    "data" : [ [1563994800000, null], [1564081200000, 69570.31], [1564167600000, 46820.31], [1564254000000, 36460.93], [1564340400000, 65406.25], [1564426800000, null], [1564513200000, null] ],
    "yAxis" : 0,
    "color" : "#008080"
  }, {
    "name" : "var2",
    "type" : "column",
    "data" : [ [1563994800000, null], [1564081200000, 34328.12], [1564167600000, 79726.56], [1564254000000, 37578.12], [1564340400000, 38085.93], [1564426800000, 0], [1564513200000, null] ],
    "yAxis" : 1,
    "color" : "#000000"
  } ],
  "title" : {
    "text" : ""
  },
  "subtitle" : {
    "text" : ""
  },
  "xAxis" : [ {
    "type" : "datetime",
    "title" : {
      "text" : "Date"
    },
    "labels" : {
      "rotation" : 0
    },
    "tickInterval" : 6.048E8
  } ],
  "yAxis" : [ {
    "title" : { },
    "lineColor" : "#008080",
    "lineWidth" : 2,
    "plotLines" : [ {
      "color" : "#fc546f",
      "dashStyle" : "dash",
      "label" : {
        "style" : {"color": "#FC546F","fontSize": "9","textOutline": "2px contrast" },
        "x" : 0,
        "text" : "target"
      },
      "value" : 40000.0,
      "width" : 2,
      "zIndex" : 10
    } ]
  }, {
    "title" : { },
    "lineColor" : "#000000",
    "lineWidth" : 2,
    "plotLines" : [ {
      "color" : "#7d6be4",
      "dashStyle" : "dash",
      "label" : {
        "style" : {"color": "#7d6be4","fontSize": "9","textOutline": "2px contrast" },
        "x" : 0,
        "text" : "target"
      },
      "value" : 50000.0,
      "width" : 2,
      "zIndex" : 10
    } ]
  } ],
  "legend" : {
    "itemStyle" : {"color": "#2D3141" },
    "itemHoverStyle" : {"color": "#2D3141" },
    "itemHiddenStyle" : {"color": "#2D3141" },
    "labelFormat" : "<span style=\"color:{color}\">{name}</span>",
    "useHTML" : false
  },
  "credits" : {
    "enabled" : false
  },
  "plotOptions" : {
    "column" : {
      "borderWidth" : 0,
      "pointPadding" : 0.2
    }
  },
  "creditOptions" : {
    "enabled" : false
  }
}}
```

**Comment by pawelfus** [comment]
Hi @johnpeterdev 

Thanks for reporting the issue. For me it seems that both plotLines are rendered in the same place. Did you try simply increasing/decreasing height of the chart? In the first image both values on yAxes are exactly in the middle: 40k and 50k, and those are the values you use to render plotLines.

**Comment by johnpeterdev** [comment]
you are right , strange thing is that same json on dif servers is diferent scale

**Comment by pawelfus** [comment]
Are you sure that configs are exactly the same? And chart heights? From the screenshots: top image has plotting area's height ~284px, bottom image has ~297px. That suggests different configs, Highcharts version etc.

**Comment by johnpeterdev** [comment]
It is the same json , on both servers. Not sure if highchart version is diferent from 2.14 release to 2.25

**Comment by pawelfus** [comment]
v2.0.14 is about one year old, so most probably uses v6.1.x  (assuming that you never updated Highcharts on the server).

Just realized: your fonts are different on images. Make you you have [fonts installed](https://github.com/highcharts/node-export-server#installing-fonts) on both servers (`Lucida Grande` seems to be missing in the top screen). Different fonts can change the available space for plotting area resulting in different results.
