### ISSUE TITLE
Exporting with setted -callback parameter throws an error

### ISSUE THREAD

**Issue by NormenSchwettmann** [highcharts/node-export-server#22]
Hi,
if I add a callback-file I get folllowing error with the cli:
`phantom worker 1 unexpected data - SyntaxError: Unexpected token ':'`
`  undefined:1 in appendChild`
`  :15`
`  :16`

**Command:**
`highcharts-export-server  -infile 'c:\temp\input.js' -outfile 'c:\temp\test.png' -callback 'c:\temp\callback.js`

**input.js:**
```javascript
{
    "xAxis": {
        "categories": [
            "Jan",
            "Feb"
        ]
    },
    "series": [
        {
            "data": [1,3],
            "type": "line"
        }
    ]
}
```

**callback.js:**
```javascript
function(chart) {
    chart.renderer.label('This label is added in the callback', 100, 100)
    .attr({
        fill : '#90ed7d',
        padding: 10,
        r: 10,
        zIndex: 10
    })
    .css({
        color: 'black',
        width: '100px'
    })
    .add();
}
```

**OS:** Windows 10

Let me know, if you need further information.

**Comment by rafael-trevisan** [comment]
Hey @NormenSchwettmann ,

Did you get this working?

I'm trying to use a callback file. I don't get any error during the export but I get a "Chart input data error" png chart.

Could you figure a way out to get this done?

**Comment by lisonok** [comment]
I have a similar problem
