### ISSUE TITLE
Package is generating blank images on windows 10 and in docker container.

### ISSUE THREAD

**Issue by c0decharlie** [highcharts/node-export-server#237]
What I already figured out is that I'm behind company proxy which is messing something in package installation process. What's interesting there's no error displayed during installation. 

How do I know it's proxy problem? I installed package on my private computers and everything works fine (on windows 10 and macOS). What I did further? I took installed package from my private computer and I copied it to my company computer and it started working... 

I know this issue is similar to #207 but solution from comments doesn't work for me.

#### Expected behaviour
Nodejs module generating images with charts

#### Actual behaviour
Nodejs module generating blank images

#### Reproduction steps
Be behind proxy and install package via npm. Setup export server like in README.md - https://github.com/highcharts/node-export-server#using-as-a-nodejs-module

**Comment by c0decharlie** [comment]
Ok, I found solution for that case. There must be a problem with fetching dependencies from `CDN` in `build.js`, becouse if we choose `npm` insted of `CDN` everything works fine.

Steps you need to take to make it work: 
1. Install `highcharts.js` from `npm` in your project. Installation process will start and you're gonna be ask `Which CDN would you like to use?` and you should choose `npm`
2 Install `highcharts-export-server`. Again you will be asked to choose `CDN` and you need to type `npm`, so dependencies for export server will be linked form `highcharts` which were installed before.

Hope it will help someone.

**Comment by PeteAtkins** [comment]
> Ok, I found solution for that case. There must be a problem with fetching dependencies from `CDN` in `build.js`, becouse if we choose `npm` insted of `CDN` everything works fine.
> 
> Steps you need to take to make it work:
> 
> 1. Install `highcharts.js` from `npm` in your project. Installation process will start and you're gonna be ask `Which CDN would you like to use?` and you should choose `npm`
> 2. Install `highcharts-export-server`. Again you will be asked to choose `CDN` and you need to type `npm`, so dependencies for export server will be linked form `highcharts` which were installed before.
> 
> Hope it will help someone.

Thanks, this solved it for me on Win 10
