### ISSUE TITLE
Problem to load image into my highchart exported

### ISSUE THREAD

**Issue by OrianB** [highcharts/node-export-server#238]
First of all sorry for my english.
I have a problem with the export of highchart.

i have this chart : 
`{
	  "chart":{
	    "type":"column",
	    "spacingBottom":25,
	    "spacingTop":25,
	    "spacingRight":30
	  },
	  "xAxis":{
	    "categories":["D\u00e9tail nb.(%)"],
	    "crosshair":true,
	    "title":{
	      "text":""
	    }
	  },
	  "series":[
	    {
	      "name":"<div style=\"width: 80px;position: relative;top: -3px;display:inline-block\"><\/div>",
	      "data":[
	        {
	          "y":30.77,
	          "name":"D\u00e9tail nb.(%)"
	        }
	      ]
	    },
	    {
	      "name":"<div style=\"width: 80px;position: relative;top: -3px;display:inline-block\"><\/div>",
	      "data":[
	        {
	          "y":19.23,
	          "name":"D\u00e9tail nb.(%)"
	        }
	      ]
	    },
	    {
	      "name":"<div style=\"width: 80px;position: relative;top: -3px;display:inline-block\"><\/div>",
	      "data":[
	        {
	          "y":11.54,
	          "name":"D\u00e9tail nb.(%)"
	        }
	      ]
	    },
	    {
	      "name":"<div style=\"width: 80px;position: relative;top: -3px;display:inline-block\"><\/div>",
	      "data":[
	        {
	          "y":19.23,
	          "name":"D\u00e9tail nb.(%)"
	        }
	      ]
	    },
	    {
	      "name":"<div style=\"width: 80px;position: relative;top: -3px;display:inline-block\"><\/div>",
	      "data":[
	        {
	          "y":19.23,
	          "name":"D\u00e9tail nb.(%)"
	        }
	      ]
	    }
	  ],
	  "title":{
	    "text":null
	  },
	  "subtitle":{
	    "text":null
	  },
	  "credits":{
	    "enabled":false
	  },
	  "legend":{
	    "useHTML":true,
	    "align":"center"
	  },
	  "plotOptions":{
	    "series":{
	      "dataLabels":{
	        "enabled":true
	      }
	    },
	    "column":{
	      "pointPadding":0.2,
	      "borderWidth":0
	    }
	  },
	  "yAxis":{
	    "title":{
	      "text":""
	    },
	    "min":0,
	    "lineWidth":1
	  }
	}`

he return me something like that : 
![image](https://user-images.githubusercontent.com/26029287/75049904-402ce600-54cb-11ea-8b40-34c867a4cc13.png)

My problem is that i want image in my legend, a different rating with star.

I try to add them with renderer.image in my callback and that's work sometimes but not everytime.

I try to add an asyncrendering and if the image is load to return an highexp.done() but it's same that's not work everytime. (in the callback again)
`"callback": "function(chart) {chart.renderer.image('https://randomimage.png','70',chart.chartHeight-75,'85','15').on('load',function(){highexp.done()}).add();}",`
I try into a .js and call a ressource + files into my json but all the option into my json work but not the renderer.image with this solution.

I really don't understand why that's not work everytime and i search a stable solution to do what i want. Actually i try to find a solution for 1 image but i have 5 images to load into this chart exported.

Thanks.

**Comment by 100phel** [comment]
Have you found the solution? I'm facing the same problem. And the method described in the issue below doesn't work either: https://github.com/highcharts/node-export-server/issues/137

**Comment by OrianB** [comment]
Yes, the images that's I try to load are simple (smiley, star etc ...) so i stoped to try to load them and i created them in svg with SVGrenderer include with highcharts.
https://api.highcharts.com/class-reference/Highcharts.SVGRenderer

It's a little fix for simple image so that's couldn't help you maybe.

**Comment by pawelfus** [comment]
Check #186 - it seems to be a bug in server, that awaits only images that are loaded as markers. You can try my workaround: create a dummy series with tiny (less than 0.5px) markers, each marker is a reference to the image. Server will wait for images, that you can use later in `load` event. I haven't tried that, but should work.

**Comment by 100phel** [comment]
Instead of using the callback or asyncRendering I decided to use markers like that: 
```
"series": [
    {
      "type": "line",
      "lineWidth": 0,
      "data": [
        {
          "x": 1592586000000,
          "y": 86,
          "marker": {
            "symbol": "url(https://dots.dataontouchdev.com/images/weather/yr_weather_symbols/svg/01d.svg)",
            "width": 40,
            "height": 40
          }
        },
...
```
However, the svg images are still loaded sometimes and not loaded other times... I'm using https://export.highcharts.com/ web service to test.

**Comment by 100phel** [comment]
When using the Postman - I get the same results: my SVGs are loaded like 2 times out of 10...

**Comment by OrianB** [comment]
@100phel Care, i dont "load" an images in .svg, i created them with the api, so yes they load every Time. But if i try to load a file in .svg it doesnt work

**Comment by 100phel** [comment]
@OrianB Oh, I see. So, you still use the callback parameter to create them dynamically, right?

**Comment by OrianB** [comment]
@100phel Yes, I create my svg into array + the "option" of my svg in another array (like color, positionnement etc) and i create my image with 
`function(chart){
var starFill = ['M',12,0.587,'l' etc ....];
var optionStarFill= [fill:'#000000', zIndex:10 etc ...];
chart.renderer.path(startFill).attr(optionStarFill).add()`
