### ISSUE TITLE
Clipped output on Amazon Linux/4.13.1 vs Ubuntu 18.04 

### ISSUE THREAD

**Issue by nickcotter** [highcharts/node-export-server#240]
We are finding some differences in output in all formats between these two environments. Ubuntu is producing the correct output whereas Amazon Linux is producing strangely clipped output.

Note that this issue was originally raised on the [Highcharts forum](https://www.highcharts.com/forum/viewtopic.php?f=9&t=43401).

In the steps below I refer to a [gist](https://gist.github.com/nickcotter/c4223aaa2c3b81890e08c6a646c56da0) I created to illustrate the problem on the forum.

NB the sample chart in the gist is a deliberately empty plot - I see the same issue whether or not there's data.

#### Expected behaviour

The output SVG files should be the same in both environments.

#### Actual behaviour

They aren't. The gist includes both outputs (ok-chart.svg and bad-chart.svg). The broken output as different clipping rect widths and visually seems enlarged with the x-axis title half dragged offscreen.

[OK](https://gist.githubusercontent.com/nickcotter/c4223aaa2c3b81890e08c6a646c56da0/raw/a0933e3a90225408c0679ae169d8a60537fd21cf/ok-chart.svg)

[Bad](https://gist.githubusercontent.com/nickcotter/c4223aaa2c3b81890e08c6a646c56da0/raw/a0933e3a90225408c0679ae169d8a60537fd21cf/bad-chart.svg)

#### Reproduction steps
Run the command:

> highcharts-export-server --infile infile.json --type svg

using the infile.json sample in the gist on both environments and compare the output.

----

I am using node 10.18.1 & highcharts-export-server 2.0.24. I have been through the dependencies on both environemtns and the same version of all npm packages is installed.

The problem occurs whether I'm exporting SVG, PNG, JPEG or PDF.

I'm at a loss as how to diagnose this further - even tips on other differences to look for would be helpful!

**Comment by gustavocampos** [comment]
Same problem here, also changing the dpiCorrection factor in highcharts-convert.js gives the same result.

**Comment by nickcotter** [comment]
> Same problem here, also changing the dpiCorrection factor in highcharts-convert.js gives the same result.

Sorry what is highcharts-convert.js? I don't have such a file in my export server.

**Comment by nickcotter** [comment]
This was resolved by upgrading to 6.2.0
