### ISSUE TITLE
When posting multipart/form-data to the server, async=false is misinterpreted

### ISSUE THREAD

**Issue by blalasaadri** [highcharts/node-export-server#244]
#### Expected behaviour
When calling the export server with the content type `multipart/form-data` and the option `async=false`, the server should return an image file.

#### Actual behaviour
It returns the path to an image file, as it would when `async == true`.

#### Reproduction steps
Start this project in server mode and run the following curl command against it:
```
curl --location --request POST '127.0.0.1:7801' \
--form 'async=false' \
--form 'content=options' \
--form 'options={"yAxis":{"allowDecimals":false,"min":0,"max":100,"title":{"text":""},"labels":{"overflow":"justify"}},"xAxis":{"title":{"text":""},"labels":{"enabled":false}},"legend":{"enabled":false},"series":[{"data":[42],"name":"a"}],"title":{"text":""},"chart":{"width":"350","defaultSeriesType":"bar","height":"80"}}' \
--form 'type=image/png' \
--form 'width=' \
--form 'scale=1' \
--form 'constr=Chart' \
--form 'callback='
-o mychart.png
```
This will act as though `async == true` and return the path to a file. If you remove the option `--form 'async=false'` however, it returns the image (as is to be expected when using `async == false` - which is the default).

#### Explanation

In the call
https://github.com/highcharts/node-export-server/blob/0d2dcbbe027456723e3562109842944bf7bbc484/lib/server.js#L206-L225
some body parameters (including `async`) are interpreted as booleans. This works fine if the body is JSON, which has a boolean type. However, if it's `multipart/form-data` all values seem to interpreted as strings.
So, the line
```js
async: req.body.async || false,
```
is interpreted as
```js
async: "false" || false,
```
in this case - and `"false"` is a truthy value. I would expect similar problems to exist for other fields as well.

**Comment by Domy976** [comment]
At the moment, the only workaround is to remove the parameter, so that it is set by default to "False" and the server returns the image

**Comment by blalasaadri** [comment]
Since it's been over a year now since I reported the issue, any chance of it being addressed some time soon?

**Comment by PaulDalek** [comment]
Closing this as the `async` option is deprecated and using the above multipart/form-data POST example works correctly with the newest version.
