### ISSUE TITLE
parameter scale is unnecessarily limited to a minimum of 1

### ISSUE THREAD

**Issue by level420** [highcharts/node-export-server#250]
For some reason the parameter scale was limited to a minimum of 1, which therefore does not allow to shrink the generated output.
See https://github.com/highcharts/node-export-server/blob/master/lib/chart.js#L120-L122

#### Expected behaviour
It should be possible to set the scale parameter to values greater than 0 but also lower than 1, eg. 0.25, which should lead to a smaller image with a fourth of the dimension.

#### Actual behaviour
If you specify scale being lower then 1 it is secretly set to 1 without any notice.

#### Reproduction steps
<pre>
 curl -H "Content-Type: application/json" -X POST -d '{"scale": 0.25, "infile":{"title": {"text": "Steep Chart"}, "xAxis": {"categories": ["Jan", "Feb", "Mar"]}, "series": [{"data": [29.9, 71.5, 106.4]}]}' 127.0.0.1:7801 -o mychart.png
</pre>

The resulting image should have a width of 600px * 0.25 = 150px but it has 600px.

**Comment by level420** [comment]
@cvasseng I'd like to ask if this is still the current export server implementation for highcharts as it seems that there is low activity on this repo. And of course I'd like to know if a PR would be welcome to implement what I've suggested in this issue.

**Comment by jakubSzuminski** [comment]
I've labeled it as an ehnacement. We will consider adding it to the latest puppeteer version after all the prioritized issues are fixed.

**Comment by jakubSzuminski** [comment]
Fixed via https://github.com/highcharts/node-export-server/pull/449.
