### ISSUE TITLE
Unicode Special characters

### ISSUE THREAD

**Issue by wkungu** [highcharts/node-export-server#254]
#### Expected behaviour
![Expected](https://uc4e66a7dcaa76d178a3fec83448.previews.dropboxusercontent.com/p/thumb/AA64fMy-lpwFtgmXStOIpli-1VFYmvwqlW9I5keoqrrSf26Zg-H81LUAOm8x-YVBZBnT7shzCffU_douyvhivBjKBfjiItJfJKITMyZlSxex5gPzs_zn14P1PsC8yxQFrBeUAnAF1EENtFnmcGojp8RRpUog68aLZdKceLK3q1OsfOy6VJU-UMbV8FTCaBzj8Vwe37aQo7DXlm5l97uoAib-2vQOxvstWK923HKOvbI4fRU2sHSrg4RY5-Mhgy8n-9IUbsNt2sMfwLdNfkwM8fOx5trECCxWVMjIT11zoeXXNJmfeNKPhtdtbLbssMDt6NEDQXd4B0F31I3kpm2WfqAZlY0wuMHvphj4znp7LP3lvNf7GFCRasaR3veRFg4q_rxcKF3DZf-lvjGsQrmtmEmx/p.png?fv_content=true&size_mode=5)

#### Actual behaviour
![Behavior](https://uc00aa4e8476c04f5ef11475c639.previews.dropboxusercontent.com/p/thumb/AA4INMqzob6oofDT5QaXdP5dIGcRHw0Vm3XTqlKwtCMUMllgv0Hpj4D9KrgnUBCx0HV-bbpPyGQW3_Yu7fxvMMmoB5AmJWUW36OCrIUgtE2FzwSdNoG-cLyZFays0WYRn51fj7eU04ZMQvVbLrxYr8i2oalsmyo9C7R649uzxMo8SCo9Hr8MZ7FBWd1R53gwkb-yXiwXL5c3MpDZ8hzz-rMhSynFlMkafOojyooWqLRPg-s3YUF-Gn9VnyqtXdxFb7KZwqi-w-FkkmJd_PtBgs7DUAFaRAksFTT4dhGGHuzCgmbfNj2ZBFtj-qHlLQMgJB03m4Fq32pNKv7n3hkbRn_309JIPnF49B98zluTj4YtvIVYAkhvGH_TZW5JqZ8CKuMesliWD021_olgmoKyzFko/p.png?fv_content=true&size_mode=5)

#### Reproduction steps
I have web app producing the expected behaviour on the currency symbols. However this doesn't seem to work on the export-server. I have installed the fonts on my server (Im using Open sans) which I thought would solve this issue. The font seems to apply on the labels so Im curious why it wont work on the currency symbols.

Here is what i'm using to get chart;

```

const symbol = '¥';

const options = {
    type: 'png',
    scale: 2,
    options: {
      chart: {
        type: 'column',
        options3d: {
          enabled: true,
          alpha: 10,
          beta: 25,
          depth: 70,
          viewDistance: 25,
          frame: {
            bottom: {
              size: 1,
              color: 'rgba(0,0,0,0.05)',
            },
          },
        },
        height: 350,
        style: {
          fontFamily: 'Open Sans',
        },
      },
      legend: {
        itemStyle: {
          fontSize: '9px',
        },
      },
      title: {
        text: 'COACHING ROI',
        style: {
          fontFamily: 'Open Sans',
          fontSize: '11px',
          fontWeight: 600,
          textTransform: 'uppercase',
        },
      },
      subtitle: {
        text: null,
      },
      xAxis: {
        categories: ['Current Profit', 'New 1-Year Profit', 'Cost of Coaching'],
        crosshair: true,
        labels: {
          skew3d: true,
          style: {
            fontSize: '13px',
            textOverflow: 'none',
          },
        },
        title: {
          text: null,
        },
      },
      yAxis: {
        min: 0,
        crosshair: true,
        labels: {
          overflow: 'justify',
        },
        title: {
          text: null,
        },
      },
      exporting: { enabled: false },
      tooltip: {
        formatter() {
          return `${this.x} is ${symbol}${this.y}`;
        },
      },
      plotOptions: {
        series: {
          pointWidth: 80,
        },
        column: {
          pointPadding: 0.2,
          borderWidth: 0,
          groupPadding: 0,
          shadow: true,
          depth: 25,
          dataLabels: {
            enabled: true,
            skew3d: true,
            crop: false,
            overflow: 'none',
            style: {
              fontFamily: 'Open Sans',
              fontSize: '10px',
              fontWeight: 'normal',
            },
            formatter() { return `${symbol}${this.y}`; },
          },
        },
      },
      credits: {
        enabled: false,
      },
      series: [{
        showInLegend: false,
        data: [
            { y: 200000, color: '#019247' },
            { y: 532500, color: '#019247' },
            { y: 36000, color: '#14143f' },
        ],
        dataLabels: {
          enabled: true,
          skew3d: true,
        },
      }],
    }, 
  };

```

**Comment by PaulDalek** [comment]
Hi @wkungu

Setting the `dataLabel.formatter` such a way won't work. Instead, you can either:

- change the format of data labels through the `format` property: `format: symbol + '{y}'`

- use the `customCode` argument to modify the chart options just before the chart creation:
```
customCode: function (options) {
    const symbol = '¥';

    options.series[0].dataLabels.formatter = function() {
        return symbol + '' + this.y;
    }
}
```

- use the `callback` along with the `allowFileResources` in the `exportOptions`.
```
{
    ...
    allowFileResources: true,
    callback: '<path_to_callback>',
    ...
}
```

**Comment by wkungu** [comment]
Thank you. Worked like a charm!
