### ISSUE TITLE
Fonts are not loading despite being loaded

### ISSUE THREAD

**Issue by johnsona9** [highcharts/node-export-server#26]
I'm running the node-export-server on a docker container on RHEL 7.2 and am having trouble exporting anything other than an SVG. PDF's, PNG's and JPEG's are all missing the text that exists in the SVG. I assumed that this would be due to missing fonts, but I have installed arial (one of the required fonts?) and I am still getting no text on my exports. I have run `fc-cache -fv` to update the cache, and `fc-list` shows `/usr/share/fonts/truetype/arial.ttf: Arial:style=Regular,Normal,obyčejné,Standard,Κανονικά,Normaali,Normál,Normale,Standaard,Normalny,Обычный,Normálne,Navadno,thường,Arrunta`. 

The highcharts log is not particularly helpful as it only sees the SVG come in and then parses and finishes. Log level 3:
`Mon Feb 13 2017 18:25:50 GMT+0000 (UTC) [verbose] got incoming HTTP request 7205a409487b46c79144861969f37023
Mon Feb 13 2017 18:25:50 GMT+0000 (UTC) [verbose] starting export
Mon Feb 13 2017 18:25:50 GMT+0000 (UTC) [verbose] parsing input as svg
Mon Feb 13 2017 18:25:50 GMT+0000 (UTC) [verbose] phantom - received work, finding available worker
Mon Feb 13 2017 18:25:50 GMT+0000 (UTC) [verbose] phantom - found available worker
Mon Feb 13 2017 18:25:50 GMT+0000 (UTC) [verbose] phantom 4 - starting work
Mon Feb 13 2017 18:25:51 GMT+0000 (UTC) [notice] phantom worker 4 finished work 7205a409487b46c79144861969f37023 in 130 ms`

The SVG uses font-family: `<text x="2" y="14" style="font-size:12px;font-family:&quot;lucida grande&quot;, &quot;lucida sans unicode&quot;, arial, helvetica, sans-serif;color:#666666;fill:#666666;">From</text>`

Any idea on other steps I could take to debug?

**Comment by johnsona9** [comment]
For whatever reason the fonts simply did not cache with the container. I zipped up the fonts and copied them with the Dockerfile and then ran `fc-cache -fv`, which then loaded the fonts.

**Comment by sonisaurabh19** [comment]
can you please share your dockerfile?
