### ISSUE TITLE
JSON parsing issue for resources

### ISSUE THREAD

**Issue by Pi-George** [highcharts/node-export-server#260]
```
[developer:/srv/www](task/PM-4063) $ highcharts-export-server -infile /tmp/inQm0DBN710G.json -outfile /tmp/outQm0DBN710G.png -scale 2 -constr Chart -type image/png -resources {"css": "@charset 'UTF-8'"}
    __  ___       __         __               __
   / / / (_)___ _/ /_  _____/ /_  ____ ______/ /______
  / /_/ / / __ `/ __ \/ ___/ __ \/ __ `/ ___/ __/ ___/
 / __  / / /_/ / / / / /__/ / / / /_/ / /  / /_(__  )
/_/ /_/_/\__, /_/ /_/\___/_/ /_/\__,_/_/   \__/____/
        ____//___/                  __     _____
       / ____/  ______  ____  _____/ /_   / ___/___  ______   _____  _____
      / __/ | |/_/ __ \/ __ \/ ___/ __/   \__ \/ _ \/ ___/ | / / _ \/ ___/
     / /____>  </ /_/ / /_/ / /  / /_    ___/ /  __/ /   | |/ /  __/ /
    /_____/_/|_/ .___/\____/_/   \__/   /____/\___/_/    |___/\___/_/
              /_/

                                                                  v2.0.28
Wed Oct 28 2020 12:34:58 GMT+0000 (Coordinated Universal Time) [warning] error parsing resources: SyntaxError: Unexpected token c in JSON at position 1
    at JSON.parse (<anonymous>)
    at doExport (/usr/lib/node_modules/highcharts-export-server/lib/chart.js:100:44)
    at exportAsString (/usr/lib/node_modules/highcharts-export-server/lib/chart.js:244:16)
    at /usr/lib/node_modules/highcharts-export-server/lib/chart.js:286:20
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

For some reason the JSON given to resources isn't being parsed properly

The same issue happens when using the example given in the [documentation](https://www.highcharts.com/docs/export-module/render-charts-serverside): {"files": "highstock.js,highcharts-more.js,data.js,drilldown.js,funnel.js,heatmap.js,treemap.js,highcharts-3d.js,no-data-to-display.js,map.js,solid-gauge.js,broken-axis.js", "css": "g.highcharts-series path {stroke-width:2;stroke: pink}", "js": "document.body.style.webkitTransform = 'rotate(-10deg)';"}

**Comment by Pi-George** [comment]
I'm experiencing the same issue if I try to specify a CSS file as a resource

**Comment by PaulDalek** [comment]
Hi @Pi-George

Thank you for reporting this issue. Try to create the `resources.json` file in the main folder which looks like this:

```
{
    "files": "",
    "css": "@charset 'UTF-8';",
    "js": ""
}
```

If such a file exists, it will be used. Next use the following command:

`highcharts-export-server -infile /tmp/inQm0DBN710G.json -outfile /tmp/outQm0DBN710G.png -scale 2 -constr Chart -type image/png`.

I was able to generate the chart successfully.

**Comment by Pi-George** [comment]
Hi @PaulDalek which resources.json file is this, and where would I find it? I'm simply trying to use the -resources flag as described here https://www.highcharts.com/docs/export-module/render-charts-serverside

Yeah that snippet of code you provided will successfully generate a chart, but it'll be missing any resources I want to include. Some of my charts have quite a few css rules that are required.

**Comment by PaulDalek** [comment]
@Pi-George

When it comes to your question, you must create this file, just as I described in my previous message.

> Yeah that snippet of code you provided will successfully generate a chart, but it'll be missing any resources I want to include.

It will be missing the resources in case you don’t create the `resources.json` (file simply won’t be found). You can also use the CLI argument, but as you can read in the [documentation](https://www.highcharts.com/docs/export-module/render-charts-serverside), the value of the `resources` parameter must be a stringified JSON. So the correct command can look like this (double quotes for Windows): 

`highcharts-export-server -infile /tmp/inQm0DBN710G.json -outfile /tmp/outQm0DBN710G.png -scale 2 -constr Chart -type image/png -resources "{\"files\": \"\",\"css\": \"@charset 'UTF-8'; g.highcharts-series path {stroke-width: 5; stroke: #ff0000;}\",\"js\": \"\"}"`

**Comment by Pi-George** [comment]
Ah right, I'm not a JS dev so I had no idea that stringified json was different to json until I saw your example just there. I'll give that a shot, thank you
