### ISSUE TITLE
Environment variables doesn't get parsed correctly

### ISSUE THREAD

**Issue by Timppe** [highcharts/node-export-server#266]
There's an issue with setting the environment variables HIGHCHARTS_USE_STYLED, HIGHCHARTS_USE_MAPS, HIGHCHARTS_MOMENT and HIGHCHARTS_USE_GANTT. If given values, all values get parsed as string so they will always result in the if statements resolving to true (since a non-empty string always resolves to true).

#### Expected behaviour
First of all, I don't think any of them should be included by default, since the README says one can include them by setting the environment variables, and they should especially not be included if the value is set to 0 or false. I see in the code (build.js) that they are parsed as simply strings, resulting in the if checks in embedAll function to evaluate a string (which always returns true if it's not an empty string) and not a number (1/0) or a boolean (true/false) if given.

#### Actual behaviour
Console outputs reveal that the if checks return true when not setting environment variables, or setting them to whatever (except empty value, which seems to be the workaround, explained later)
```
Including maps support
Including Gantt support
Including styled mode support
```

#### Reproduction steps
Try putting this in the useIfDefined function and run the build with various environment variables set:
```
  console.log(`\nuseIfDefined(what: ${what}, def: ${def})`);
  console.log("\ttypeof what:", typeof what);
  console.log("\treturns:", typeof what === 'undefined' ? def : what);
```
(console logs can be e.g. set in an already installed node_modules/highchart-export-server/build.js and then running that with node)

E.g. `ACCEPT_HIGHCHARTS_LICENSE=true HIGHCHARTS_CDN=npm HIGHCHARTS_USE_STYLED=false HIGHCHARTS_USE_MAPS=0 HIGHCHARTS_USE_GANTT=0 node node_modules/highcharts-export-server/build.js`
will result in including styled mode, maps and gantt.

Workaround seems to be to set them, but leave the value empty, that results in an empty string, which resolves to false in the if check, like so:
`ACCEPT_HIGHCHARTS_LICENSE=true HIGHCHARTS_CDN=npm HIGHCHARTS_USE_STYLED= HIGHCHARTS_USE_MAPS= HIGHCHARTS_USE_GANTT= node node_modules/highcharts-export-server/build.js`

One might get the illusion of setting environment variables working if setting the HIGHCHARTS_MOMENT to whatever value, because the default is false, and putting anything will resolve to a true if check. However, if someone would want to set this to false or 0 explicitly, it would likewise reveal that it's included in the end.

**Comment by PaulDalek** [comment]
Hi @Timppe

Thank you for reporting this issue. You are right, setting the environment variables with anything but an empty value will result as a truthy value. We need to do some better checking for the incoming variables. I’ll label this one as an enhancement.

**Comment by PaulDalek** [comment]
Closing this as in the newest, Puppeteer based, version setting server options is done differently. Also, envs values are checked and set to correct types.
