### ISSUE TITLE
Error when performing chart generation in export server

### ISSUE THREAD

**Issue by IdanZel** [highcharts/node-export-server#268]
#### Expected behaviour
Export server renders chart and returns image link.

#### Actual behaviour
While this works properly for the majority of requests, some requests, that are seemingly not any different from those that do work, return a `400 Bad Request` response, and the following log is written:

`[error] work ... could not be completed, sending: 0x03 error when performing chart generation: please check your input data`

This error appears somewhat consistently, about once in 25~30 requests on average, but not at specific times or intervals.

Also, this error seems to cause another error, which I assume arises from `phantompool.js`:

While the [function](https://github.com/highcharts/node-export-server/blob/master/lib/phantompool.js#L145) that writes the `0x03 error...` log sets `worker.ready` to `false`, the function [`doDone`](https://github.com/highcharts/node-export-server/blob/master/lib/phantompool.js#L117) is called immediately after, and sets `worker.ready` back to `true`. As a result, this worker (which I guess is terminated by this point, correct me if I'm wrong), can be chosen to process another request. If that happens, that request will hang until another request enters [`postWork`](https://github.com/highcharts/node-export-server/blob/master/lib/phantompool.js#L334), and restarts said worker (assuming the work has exceeded `timeoutThreshold`). In our case, by that point, the request has been aborted by the client due to a timeout. However, if the request wasn't aborted, `doDone` is called while restarting, and the following log is written:

`[error] work ... could not be completed, sending: 0x04 error when performing chart generation: please check your input data`

Here are some more detailed logs of this occurrence:
```
Fri Jan 22 2021 00:41:10 GMT+0000 (Coordinated Universal Time) [verbose] starting export
Fri Jan 22 2021 00:41:10 GMT+0000 (Coordinated Universal Time) [verbose] phantom - received work, finding available worker
Fri Jan 22 2021 00:41:10 GMT+0000 (Coordinated Universal Time) [verbose] got incoming HTTP request d9c833c647c9476cbee52e3b5378a2c3
Fri Jan 22 2021 00:41:10 GMT+0000 (Coordinated Universal Time) [verbose] phantom 4 - starting work
Fri Jan 22 2021 00:41:10 GMT+0000 (Coordinated Universal Time) [verbose] phantom - found available worker
Fri Jan 22 2021 00:41:10 GMT+0000 (Coordinated Universal Time) [verbose] attempting to export from raw input
Fri Jan 22 2021 00:41:12 GMT+0000 (Coordinated Universal Time) [notice] phantom worker 4 - process was closed
Fri Jan 22 2021 00:41:12 GMT+0000 (Coordinated Universal Time) [error] work d9c833c647c9476cbee52e3b5378a2c3 could not be completed, sending: 0x03 error when performing chart generation: please check your input data
Fri Jan 22 2021 00:55:15 GMT+0000 (Coordinated Universal Time) [verbose] phantom - received work, finding available worker
Fri Jan 22 2021 00:55:15 GMT+0000 (Coordinated Universal Time) [verbose] phantom - found available worker
Fri Jan 22 2021 00:55:15 GMT+0000 (Coordinated Universal Time) [verbose] got incoming HTTP request fd00ffba0b3640f6970430ae6d9325bb
Fri Jan 22 2021 00:55:15 GMT+0000 (Coordinated Universal Time) [verbose] starting export
Fri Jan 22 2021 00:55:15 GMT+0000 (Coordinated Universal Time) [verbose] phantom 4 - starting work
Fri Jan 22 2021 00:55:15 GMT+0000 (Coordinated Universal Time) [verbose] attempting to export from raw input
Fri Jan 22 2021 00:55:41 GMT+0000 (Coordinated Universal Time) [verbose] got incoming HTTP request 0e52920cce5e4ee9a66e5727dc001ade
Fri Jan 22 2021 00:55:41 GMT+0000 (Coordinated Universal Time) [verbose] starting export
Fri Jan 22 2021 00:55:41 GMT+0000 (Coordinated Universal Time) [verbose] attempting to export from raw input
Fri Jan 22 2021 00:55:41 GMT+0000 (Coordinated Universal Time) [verbose] phantom - received work, finding available worker
Fri Jan 22 2021 00:55:41 GMT+0000 (Coordinated Universal Time) [error] work fd00ffba0b3640f6970430ae6d9325bb could not be completed, sending: 0x04 error when performing chart generation: please check your input data
Fri Jan 22 2021 00:55:41 GMT+0000 (Coordinated Universal Time) [notice] restarting worker. working = false
Fri Jan 22 2021 00:55:41 GMT+0000 (Coordinated Universal Time) [verbose] phantom 6 - spawning worker
Fri Jan 22 2021 00:55:41 GMT+0000 (Coordinated Universal Time) [verbose] phantom - found available worker
Fri Jan 22 2021 00:55:41 GMT+0000 (Coordinated Universal Time) [verbose] phantom 5 - starting work
Fri Jan 22 2021 00:55:42 GMT+0000 (Coordinated Universal Time) [notice] phantom worker 5 finished work 0e52920cce5e4ee9a66e5727dc001ade in 936 ms
```

#### Reproduction steps - 0x03 error
Here is the most frustrating thing about this error - we have not been able to properly reproduce it.
We logged the requests sent from the client and later checked which ones caused this error. However, upon sending requests with the exact same data to our export server the response came back just as expected.

We're ran the server using both the latest version of node (v15) and the current LTS version of node (v14). The error occurred in both cases.

Here is a curl fetch similar to what we've ran in attempts to reproduce the issue (originally, the URL was of our local server):

```
curl --location --request POST 'https://export.highcharts.com/' \
--header 'Content-Type: application/json' \
--data-raw '{ "type": "png", "width": "600", "async": true, "options": { "title": { "text": "" }, "subtitle": null, "yAxis": { "labels": { "format": "{value}C" }, "type": null, "title": { "text": "Temperature" }, "plotLines": [], "categories": null }, "xAxis": { "type": "datetime", "title": { "text": "" }, "plotLines": null, "categories": null }, "series": [{ "id": 9625, "name": "Temperature", "data": [[1611272768892.0, -16.0], [1611273078194.0, -15.0], [1611273387702.0, -14.0], [1611273696644.0, -14.0], [1611274005929.0, -14.0], [1611274315189.0, -15.0], [1611274624522.0, -16.0], [1611274933805.0, -16.0], [1611275243021.0, -16.0], [1611275552230.0, -14.0], [1611275861637.0, -14.0], [1611276170602.0, -15.0], [1611276479877.0, -16.0], [1611276789118.0, -17.0], [1611277098203.0, -15.0], [1611277407452.0, -14.0], [1611277716645.0, -14.0], [1611278025951.0, -16.0], [1611278335124.0, -17.0], [1611278644415.0, -15.0], [1611278953682.0, -14.0], [1611279262951.0, -15.0], [1611279572120.0, -16.0], [1611279881387.0, -16.0], [1611280190588.0, -14.0], [1611280499941.0, -14.0], [1611280809264.0, -16.0], [1611281118475.0, -16.0], [1611281427722.0, -14.0], [1611281737008.0, -12.0], [1611282046195.0, -8.0], [1611282355322.0, -4.0], [1611282664461.0, 1.0], [1611282973496.0, 4.0]], "machineLearningResults": { "anomalyIndicies": [], "forcastRanges": null }, "tooltip": null, "categories": null, "initialState": [] }], "credits": { "enabled": false } } }'
```

I've tried searching through the code to see what might prompt this error. A noteworthy detail I saw was that in most cases, the worker is closed about 2 seconds after it has started processing the request. For example, in the batch of logs above - `attempting to export from raw input` was logged at 00:41:10, and `phantom worker 4 - process was closed` was logged at 00:41:12.

This might correspond to the value of [`pollTimeout`](https://github.com/highcharts/node-export-server/blob/master/phantom/worker.js#L167) at the `buildChart` function in `worker.js`. If so, this could suggest that the error occurs since the `onDone` function ([passed later on as a parameter](https://github.com/highcharts/node-export-server/blob/master/phantom/worker.js#L383)) attempts to render the chart before it has been fully loaded. Consequently - increasing the value of `pollTimeout` and/or making it configurable might solve this issue. Do keep in mind, however, that I have not yet been able to confirm this as the actual source of the error. 

Regardless, the 2nd issue described above (timeout / 0x04 error) does seem to be the result of setting `worker.ready` twice in separate places, and might need fixing.

**Comment by PaulDalek** [comment]
Hi @IdanZel 

My apologies for the late reply. Thank you for contacting us and your thorough analysis of the problem. We will investigate this issue.

**Comment by TimPosey2** [comment]
Any update on this, @PaulDalek ?

**Comment by PaulDalek** [comment]
Closing this as it concerns deprecated, PhantomJS based version where the pool of resources management is different.
