### ISSUE TITLE
Does highchart-export-server use PhantomJS internally?

### ISSUE THREAD

**Issue by tejaspchordiya** [highcharts/node-export-server#27]
Hi,

Does highchart-export-server use PhantomJS internally?

If yes, can I implement highchart export without using phantom js?

**Comment by cvasseng** [comment]
Hi, yes; the export server utilizes PhantomJS.

It's certainly possible to write an exporter that uses something like NW.js, or another "headless browser" library. It's conceivably possible to do it without too, but that would be an immense amount of work.

Any reason why you want a "Phantom-less" version?

**Comment by cvasseng** [comment]
Feel free to reopen this if you have any additional questions about the usage of PhantomJS. Thanks.
