### ISSUE TITLE
Build.js not throw's error if highcharts modules is unreachable

### ISSUE THREAD

**Issue by Keeller** [highcharts/node-export-server#270]
Hello,
 i use node-export-server as node module behind corporative proxy and firewall. I set npm config strict-ssl false and set npm proxy. When i try to get chart, i have that.  
![isuue](https://user-images.githubusercontent.com/43935964/109680003-210c6e00-7b8d-11eb-9bc6-f9b12261df05.png)
Build.js script complete with no issues. I have researching code of modules and understanding that it happening because build script can't  get highcharts modules. In expot html templates happening that
` <script>
      undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
undefined;
    </script>`
If i set this code manualy, all work right.
#### Expected behaviour
Build.js must throw's errors, if highcharts module is unreachable.

#### Actual behaviour
Build.js complete with no issues

#### Reproduction steps
Run build,js behind proxy and firewall.

Thanks.

**Comment by KacperMadej** [comment]
Hi @Keeller 

Thank you for reporting about the problem.

You could try loading the files from NPM and those should later be placed in the project in node_modules to avoid connection blocked by a firewall. You could add a script like `install` in `package.json`.
For Windows: `"install": "set ACCEPT_HIGHCHARTS_LICENSE=1 && set HIGHCHARTS_USE_NPM=1 && node ./build.js"` (`set` and `&&` are needed).
For others: `"install": "export ACCEPT_HIGHCHARTS_LICENSE=1 export HIGHCHARTS_USE_NPM=1 node ./build.js"`,

**Comment by Keeller** [comment]
Thanks, when i modify package.json with "export ACCEPT_HIGHCHARTS_LICENSE=1 && `export HIGHCHARTS_USE_NPM=1 && node ./build.js",` and execute npm install all work right.
