### ISSUE TITLE
High Vulnerabilites Found

### ISSUE THREAD

**Issue by ssgriffen** [highcharts/node-export-server#272]
#### Expected behaviour
No Vulnerabilites ( or atleast no high vulnerabilities )

#### Actual behaviour
found 11 vulnerabilities (3 low, 6 moderate, 2 high) in 2796 scanned packages
![image](https://user-images.githubusercontent.com/19702760/110961456-10869100-830d-11eb-8a44-981ae9f1ba52.png)

#### Reproduction steps
 

npm install highcharts-export-server
npm audit

**Comment by kreintjes** [comment]
You can use this branch/fork which updates the vulnerable packages for now: https://github.com/highcharts/node-export-server/pull/291

**Comment by jakubSzuminski** [comment]
We're doing everything we can to reduce the number of vulnerabilities in our latest version of the Export Server, which I encourage you to try out.

Here's a short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information

In case you find any vulnerabilities in the newest version, please report them so we can investigate them.
