### ISSUE TITLE
Highcharts export server is not working

### ISSUE THREAD

**Issue by nilesflow** [highcharts/node-export-server#275]
Hi,

I will inquire here about the following cases.
https://github.com/highcharts/node-export-server/security/advisories/GHSA-hfwx-c7q6-g54c

In the forum, I was instructed to contact the contact information provided in the above case.
https://www.highcharts.com/forum/viewtopic.php?f=9&t=46068

#### Expected behaviour
The user should be notified in advance of changes that will stop the application from working.

#### Actual behaviour
We haven't been able to see the announcement that the application needs to be modified before it stops working.

#### Reproduction steps
We use Highcharts export server in our application with http://export.highcharts.com/, and 
the export function is not working properly in our application.
The export operation redirects us to https://export.highcharts.com/.

We understood this change on exports server.
We'll modify the URL to https://.

We have two questions.
1. When did this change apply to Highcharts export server?
2. When was this change announced to us?

Regards,

**Comment by nilesflow** [comment]
Append.

We are using several versions of the highcharts library.
In the following file of the 4.1.7 version of the library, it is described as http://export.highcharts.com/, so the export feature is not working.
Highcharts-4.1.7/js/modules/exporting.js

Is the export feature no longer supported by the version of the library?

**Comment by KacperMadej** [comment]
@nilesflow - as for the v4.1.7: [`exporting.url`](https://api.highcharts.com/highcharts/exporting.url) should be set using `https`.

@cvasseng might have more answers for other questions.

_Internal note:_
[This docs](https://www.highcharts.com/docs/export-module/privacy-disclaimer-export#privacy-disclaimer) might be not up to date regarding HTTP info and recent changes. Should this be a separate doc issue on the main repo? @cvasseng

**Comment by munkyxtc** [comment]
I'm also encountering issues as the result of this unexpected breaking change.  I have converted quite a few of our charts to use json; however, even basic parts of the API like custom formatter are now broken with no work arounds.

**Comment by nilesflow** [comment]
@KacperMadej Thank you for your comment.
We'll consider using exporting.url with v4.1.7.

**Comment by KacperMadej** [comment]
We will be investigating the case from the more general point of view - breaking changes; information flow; documentation, newsletter, and changelog updates. By the end of this week, we should provide more info and a full reply as soon as the issue will be resolved.

@nilesflow @munkyxtc 
Please reach us through e-mail with your license number and we will run this through the second line of support and possibly our Sales team to find an individual and satisfactional end of this case for you.

**Comment by nilesflow** [comment]
@KacperMadej I just sent the license numbers to the address  (support@highcharts.com).
We wait for a reply.

**Comment by KacperMadej** [comment]
> When did this change apply to Highcharts export server?
> When was this change announced to us?

The change was not announced and was not aimed to harm or limit any feature or exporting server usage.
The HTTP connection is now temporarily reenabled.
The change to an HTTPS-only connection will be made in about the next two weeks - the time period might slightly change.

**Comment by munkyxtc** [comment]
@KacperMadej after reviewing this chain it seems my case is slightly different; as I understand the reported problem is the export option within the a chart generated in browser. In my case I'm trying to use a headless option to invoke the export server and due to the JSON/SVG change that also accompanied the HTTPS change I'm receiving errors.  I have a support ticket opened but no response on that yet.

**Comment by munkyxtc** [comment]
Although, calling http://export.highcharts.com returns 522 status code

**Comment by nilesflow** [comment]
@KacperMadej We are also seeing calling http://export.highcharts.com returns 522 status code.

**Comment by KacperMadej** [comment]
@nilesflow 
It should be working now (at the time of writing this comment). Please give it another try.

**Comment by nilesflow** [comment]
@KacperMadej Thank you for fixing.
We have confirmed that the fix is ​​effective.
