### ISSUE TITLE
Cannot build in Node Docker container

### ISSUE THREAD

**Issue by lukos** [highcharts/node-export-server#276]
#### Expected behaviour
Any new version of node > 8 and ideally any of the node docker images (alpine, stretch, buster, slim) should all be able to be used with node-export-server to get the smallest container image for production.

It would be really nice if someone could clearly document what all these gotchas are, even though they might be spread between node and other combinations of packages and distros, it makes this very hard to use and I'm not sure that 3GB for 3 instances of the export server will really cut it.

#### Actual behaviour
It seems I can only make this work with the stretch image, which produces a container measuring 1.2GB, which is excessive when I want to run 3 instances of these.

Problems include:

1. PhantomJS installation problems on Alpine
2. If I fix 1 by manually installing phantomized, I can get a build locally but it fails on CI server with a uid/gid bug
3. I can run it on a really old build of node like 7.7 but they are all unsupported and are still quite large (800MB)
4. Debian usually needs bzip2 installed manually but then fails with permission problems setting up PhantomJS
5. Other versions build and run up but then calling the endpoint causes the error:

```TypeError: worker.restart(...).work is not a function    at
/usr/local/lib/node_modules/highcharts-export-server/lib/phantompool.js:373:38    at Array.some (<anonymous>)    at
Object.postWork (/usr/local/lib/node_modules/highcharts-export-server/lib/phantompool.js:370:21)    at exec
(/usr/local/lib/node_modules/highcharts-export-server/lib/chart.js:176:11)    at doExport
(/usr/local/lib/node_modules/highcharts-export-server/lib/chart.js:228:5)    at module.exports
(/usr/local/lib/node_modules/highcharts-export-server/lib/chart.js:359:14)    at handlePost
(/usr/local/lib/node_modules/highcharts-export-server/lib/server.js:230:3)    at Layer.handle [as handle_request]
(/usr/local/lib/node_modules/highcharts-export-server/node_modules/express/lib/router/layer.js:95:5)    at next
(/usr/local/lib/node_modules/highcharts-export-server/node_modules/express/lib/router/route.js:137:13)    at limiter
(/usr/local/lib/node_modules/highcharts-export-server/lib/server.js:63:5)
```

#### Reproduction steps

1. Create docker file like the one below with various combinations and build/run
2. I am running this under WSL on Windows, if that is relevant
3. I am running on an Ubuntu 20.04 cluster in production and also the CI server is Ubuntu server 18.04.

**Comment by askdesigners** [comment]
I think this entire project is very clunky. I don't think I've ever seen a node module that is more complicated to setup and use...

**Comment by lukos** [comment]
I think the issue is that it uses an unmaintained web server that was designed for automated testing and then simply loads up the JS files. It might be easier to just try and run something else. I could even just tag these into an existing application and load them from there perhaps.
