### ISSUE TITLE
Breaking changes in 2.1.0 violating semantic versioning

### ISSUE THREAD

**Issue by Timppe** [highcharts/node-export-server#277]
#### Expected behaviour
2.1.0 contained breaking changes and should be a major version increment.

#### Actual behaviour
Instead it was only a minor version increment, which is violating the https://docs.npmjs.com/about-semantic-versioning principles.

**Comment by KacperMadej** [comment]
Thank you for reporting about the broken recommendation.

_Internal note:_
The solution (as recommended in the semver docs) is to revert the changes in 2.2.0 with relevant release notes and apply the change again with the release of version 3.0.0.
fyi @cvasseng
