### ISSUE TITLE
Problem with generating charts with background image

### ISSUE THREAD

**Issue by Avartil** [highcharts/node-export-server#283]
Hello,
There's this weird issue with generating chart with background image (plotBackgroundImage) when I'm using export server.
Chart generates normally every time at [jsfiddle](https://jsfiddle.net/mqxk7Lhz/2/), but on [export.highcharts.com](http://export.highcharts.com/) only sometimes highchart give us chart with background.
I have the same issue on my own server.

Image size used in this post: 35-40 KB.

#### Expected behavior
Generate chart with vectors and background image everytime

#### Actual behavior
Chart with background image is generated "randomly" (maybe every 3-4 times)

#### Reproduction steps
Copy code from
[code.txt](https://github.com/highcharts/node-export-server/files/6584503/code.txt)
or from [jsfiddle](https://jsfiddle.net/mqxk7Lhz/2/) into http://export.highcharts.com/ and click Preview till you got chart with background image

**Comment by KacperMadej** [comment]
Hi @Avartil 

Thank you for reporting the problem.

Exporting to SVG works every time - maybe it could be considered a workaround.
It looks like exporting server is not waiting enough time for the base64 to be rendered and most of the time it fails to render before the file is exported. In case you have an export server set up, please let us know if the problem also shows there.

Minimal config showing the problem (based on [a default base64 symbol demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-marker-symbol/)):

```js
{
   "chart":{
      "plotBackgroundImage":"data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
   }
}

```
(should give a black background)

_Internal note:_
The size of the base64 image is not an issue (see the minimal demo above).
Exporting via the module in the chart works fine (4 out of 4 tries were ok).

**Comment by Avartil** [comment]
@KacperMadej 
As you wrote, SVG is generated every time. I can work with it.
Thanks for the suggestions.

**Comment by jakubSzuminski** [comment]
I encourage you to try out our latest Puppeteer-based version of the Export Server (here’s a short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information).

Here's a link you can use to test this version: https://export-dev.highcharts.com/

Most likely, this is no longer an issue, but if you find any problems with the newest version please report it again so we can investigate it.
