### ISSUE TITLE
Issue with formatting

### ISSUE THREAD

**Issue by FSE-Hyd-Raju** [highcharts/node-export-server#290]
Hi All,

I was trying to export the high charts using the node export server. Need to format the numbers on the chart. Is there any way that we can achieve this ?

![image](https://user-images.githubusercontent.com/9348371/126940716-37af476c-9d43-497e-a9a6-d51d0fb9d42e.png)

**Comment by KacperMadej** [comment]
For technical support see https://www.highcharts.com/blog/support/

To format dataLabels see [format](https://api.highcharts.com/highcharts/plotOptions.series.dataLabels.format) or [formatter](https://api.highcharts.com/highcharts/plotOptions.series.dataLabels.formatter).
