### ISSUE TITLE
Open Sans Font family in Highcharts Export Server

### ISSUE THREAD

**Issue by Sreejithga** [highcharts/node-export-server#297]
#### Expected behaviour
Font in the chart should be retain when its exported to PNG, JPEG, PDF etc, but its picking up a default font family
Please refer to this link where all the details are provided.
https://github.com/highcharts/highcharts/issues/16250

Please install 'Open Sans' font family complete in the Highcharts Exports server in order to resolve this issue as I understand

#### Actual behaviour
![image](https://user-images.githubusercontent.com/53110553/130740394-d0597fbf-14b6-41e0-93b3-356e76595857.png)

![image](https://user-images.githubusercontent.com/53110553/130740423-10f5e277-440b-468a-849f-88ea5e2c2309.png)

https://jsfiddle.net/sreejithga/objrendg/1/

**Comment by PaulDalek** [comment]
Closing this as the Open Sans font is already installed in the newest server.
