### ISSUE TITLE
resources argument seems to be ignored

### ISSUE THREAD

**Issue by lucasmauro** [highcharts/node-export-server#3]
I tried to set options for decimalPoint and thousandsSep, but the code seems to simply ignore the argument.

**Comment by cvasseng** [comment]
Hi,

could you provide an example of the input you're using?

**Comment by cvasseng** [comment]
Closed of lack of feedback, feel free to reopen this if you're still having issues.

For future reference, the `globalOptions` attribute lets you set global options (like `decimalPoint` and localizations), e.g to set the decimal point, put this into `globalOptions`:
    
    {
       "lang": {
           "decimalPoint": ","
       }
    }
