### ISSUE TITLE
Batch export errors

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/node-export-server#30]
Hi, While i use highcharts-export-server with `--batch` options for multiple export, it's run out errors

1. ReferenceError: func is not defined

![qq 20170224161339](https://cloud.githubusercontent.com/assets/6829290/23295545/1f10245e-faac-11e6-84aa-9107341e5f48.png)

it can be fixed by change `func` to  `funs` in your code `bin\cli.js` line 229

```
async.waterfall(func, function() {    // func should change to funs as defined above
  main.killPool();
});
```
2. while i fixed error 1, it's run out 'uncaughtException: [TypeError: worker.ondone is not a function]'

![qq 20170224161933](https://cloud.githubusercontent.com/assets/6829290/23295690/e9d4c9f6-faac-11e6-9fa7-b45ca7b7b55f.png)

I think you should test batch export, thanks

**Comment by cvasseng** [comment]
Thanks, c7c95cc addresses this. NPM module has been updated.
