### ISSUE TITLE
Images in yaxis labels are not visible in exported charts

### ISSUE THREAD

**Issue by cf-nammari** [highcharts/node-export-server#304]
#### Expected behaviour
That the exported chart contains images which are added to yaxis labels through html (using useHTML: true). The same way they're visible in the chart before exporting.

#### Actual behaviour
Images in the yaxis labels are not visible in the exported chart although they're visible in the chart itself.

#### Live demo with steps to reproduce
https://jsfiddle.net/7083snge/

#### Product version
 Highcharts JS v7.1.1

#### Affected browser(s)
Tested on Google Chrome Version 93.0.4577.63 (Official Build) (x86_64)

**Comment by jakubSzuminski** [comment]
Export Server v2 used the PhantomJS headless browser which is a headless browser with no support for flex, grid, and much more.

I encourage you to try out our latest Puppeteer-based version of the Export Server (here’s a short [setup guide](https://github.com/highcharts/node-export-server#puppeteer-version-information)) which has full support for modern CSS so this should no longer be an issue.

If this problem still persists in the newest version, please report it again so we can investigate it.
