### ISSUE TITLE
 Server not generating images: [notice] the client closed the connection before the chart was done processing

### ISSUE THREAD

**Issue by chrcar01** [highcharts/node-export-server#306]
#### Expected behaviour
Running export server(latest in master) locally with Node 16, sending request to http://localhost:7801 should generate chart.

#### Actual behaviour
Client(Postman, .NET HttpClient, and curl) hangs while the server displays:

![image](https://user-images.githubusercontent.com/43953/137818065-b88f406a-239d-41c9-8d50-6326ca2cdd03.png)

#### Reproduction steps
 

`curl -H "Content-Type: application/json" -X POST -d '{"scale":8,"type":"png","infile":{"chart":{"type":"bar"},"title":{"text":"Bar Chart Sample"},"xAxis":{"categories":["Cat1","Cat2"]},"yAxis":{"min":0,"labels":{"overflow":"justify"}},"series":[{"name":"Cat1","data":[107,31]},{"name":"Cat2","data":[133,156]}]}}' http://localhost:7801 -o barchart.png`

#### Notes
Switching to Node 14, it works as expected.
Node 15.14.0 also works, 16.0.0 seems to have introduced this behavior in Highcharts.

**Comment by level420** [comment]
For me the currently working configuration is node 14 with highcharts 9.2.2.
Im running the node export server in a docker container based on node:14-bullseye-slim from docker hub.

**Comment by gustavocampos** [comment]
I'm having the same problem with node:16.13.2-buster, which I tried to upgrade from node:14.17.5-buster due to some vulnerabilities and to keep Node in a LTS version

**Comment by bm64** [comment]
+1

**Comment by leond08** [comment]
Can you share your docker config?

**Comment by tavib47** [comment]
> This [PR](https://github.com/highcharts/node-export-server/pull/337) by @DominicAlthaus fixes the issue for me.

I confirm that PR fixes the issue.

**Comment by crowne** [comment]
> For me the currently working configuration is node 14 with highcharts 9.2.2. Im running the node export server in a docker container based on node:14-bullseye-slim from docker hub.

How do you resolve highcharts 9.2.2 ?

When I view the versions in npm I see the following:

```
npm view highcharts-export-server versions 
[
  '0.1.0',  '0.1.1',  '0.1.11', '0.1.12', '0.1.13',
  '0.1.14', '0.1.15', '0.1.16', '0.1.17', '0.1.18',
  '0.1.19', '0.1.20', '0.1.21', '0.1.22', '0.1.23',
  '0.1.24', '0.1.25', '0.1.26', '0.2.0',  '0.2.1',
  '0.2.2',  '0.2.3',  '0.2.4',  '0.2.5',  '0.2.51',
  '0.2.52', '0.2.53', '1.0.0',  '1.0.1',  '1.0.2',
  '1.0.3',  '1.0.5',  '1.0.6',  '1.0.7',  '1.0.8',
  '1.0.9',  '1.0.10', '1.0.11', '1.0.12', '1.0.13',
  '1.0.14', '1.0.15', '1.0.16', '1.0.17', '1.0.18',
  '1.0.19', '1.0.20', '1.0.21', '2.0.0',  '2.0.1',
  '2.0.2',  '2.0.3',  '2.0.4',  '2.0.7',  '2.0.8',
  '2.0.9',  '2.0.10', '2.0.11', '2.0.12', '2.0.13',
  '2.0.15', '2.0.16', '2.0.18', '2.0.19', '2.0.20',
  '2.0.21', '2.0.22', '2.0.23', '2.0.24', '2.0.28',
  '2.0.29', '2.0.30', '2.1.0'
]

```

**Comment by jakubSzuminski** [comment]
This PR seems to solve it: https://github.com/highcharts/node-export-server/pull/337
Duplicate issue here: https://github.com/highcharts/node-export-server/issues/312

As I've written there:

_This should no longer be a problem in the latest Puppeteer-based version of the Export Server which I encourage you to try out._

_Here's a short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information_

_Please feel free to report any problems you encounter with the newest version and we will investigate it. If we notice any incompatibilities (or you report them by creating an issue) we will update our docs to include all the necessary information._

**Comment by sjoshid** [comment]
I just did `npm i highcharts-export-server@3.0.0-beta.1 -g` and the errors Im getting are totally inexplicable. 🤯
Upon starting server I get 
```
$ highcharts-export-server --fromFile options.json
/LICENSE.txt: line 2: Note: command not found
/LICENSE.txt: line 3: syntax error near unexpected token `('
/LICENSE.txt: line 3: ` is concerned is _this_ particular version of the license (ie v2, not'
AppData\Roaming\npm/node_modules/highcharts-export-server/bin/cli.js: line 3: Highcharts: command not found
AppData\Roaming\npm/node_modules/highcharts-export-server/bin/cli.js: line 5: syntax error near unexpected token `c'
AppData\Roaming\npm/node_modules/highcharts-export-server/bin/cli.js: line 5: `Copyright (c) 2016-2023, Highsoft'
```

Im running node 18.17.1 on Windows.

**Comment by jakubSzuminski** [comment]
@sjoshid if you encounter any issues with the Export Server please try to create a new issue for it with a full description. Could you please specify what is in your `options.json` file?
