### ISSUE TITLE
SSL handshake error

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/node-export-server#307]
Recently I'm getting an `SSL handshake error` when calling a remote url from within my worker script.  I suspect it relates [to this issue](https://scotthelme.co.uk/lets-encrypt-old-root-expiration) but I don't understand enough about it to be sure.  The error doesn't occur if I use `http` rather than `https`.

I see that phantom.js has various command line switches which may be relevant, e.g. `--ignore-ssl-errors=true` and `--ssl-protocol=any`... but I'm not sure how to pass these switches to phantom.js via the node export server.

Note that I'm using the export server [as a node module](https://github.com/highcharts/node-export-server#using-as-a-nodejs-module) and passing in a custom `worker` via `exporter.initPool()`.

**Comment by drmrbrewer** [comment]
Hi @KacperMadej is a puppeteer-based beta version nearly ready yet?  Can't wait... :)

**Comment by dpetrov** [comment]
hey @KacperMadej how is the transition coming along? Is this still WIP and planned Q1 2022 or postponed/delayed? Thank you for the awesome work.

**Comment by KacperMadej** [comment]
The current state is described [here](https://github.com/highcharts/node-export-server#current-status)

**Comment by Nicolas-Boreal-is** [comment]
I think I found the solution to this problem (mind you, I'm a junior dev, so my solution might not be the best)
In the following code (in node-export-server/lib/server/server.js):
```
if (key && cert) {
        // Main server instance (HTTPS)
        const httpsServer = https.createServer(app);

        // Attach error handlers and listen to the server
        attachErrorHandlers(httpsServer);

        // Listen
        httpsServer.listen(serverConfig.ssl.port, serverConfig.host);

        log(
          3,
          `[server] Started HTTPS server on ${serverConfig.host}:${serverConfig.ssl.port}.`
        );
      }
```
The variables key and cert are verified, but not used anywhere. After some testing, I found that `https.createServer({key: key, cert: cert}, app) ` solves the ssl handshake error and the empty responses. This issue is old, but I hope my comment is helpful to someone.

Happy coding!

**Comment by jszuminski** [comment]
Thanks for the hint @Nicolas-Boreal-is!

I've created a pull request based on your suggestion: https://github.com/highcharts/node-export-server/pull/500 and this will be a part of our next release (v4.0.0) where this should no longer be a problem.

Feel free to review it and test it out.
