### ISSUE TITLE
Export Server Returning : "Chart input data error"

### ISSUE THREAD

**Issue by vinaykevadia** [highcharts/node-export-server#31]
i am running Export server by --enableServer=true. 
i am sending the same request data on server that is given as example. sending a curl request as follow : 
``curl -H "Content-Type: application/json" -X POST -d '{"infile":{"title":{"text":"Steep Chart"},"xAxis":{"categories":["Jan","Feb","Mar"]},"series":[{"data":[29.9, 71.5, 106.4]}]}}' 127.0.0.1:8088 -o mychart.png``

following the error output i am getting instead of chart's png image : 
![image](https://cloud.githubusercontent.com/assets/7442679/23542626/3f0c36b8-0014-11e7-9af5-39298283cf31.png)

**Comment by vinaykevadia** [comment]
this issue has been fixed in version 1.0.10.

**Comment by nischi** [comment]
And it doesn't work again on 1.0.15

**Comment by crapthings** [comment]
i'm trying to put labelFormat, got this too

```js
legend: {
        enabled: true,
        margin: 64,
        itemMarginBottom: 16,
        labelFormat: '{point.y}'
      },
```

**Comment by crapthings** [comment]
okay after remove 
point.

labelFormat: '{name}{percentage}({y})'
