### ISSUE TITLE
0x03 error when performing chart generation: please check your input data

### ISSUE THREAD

**Issue by Noppey** [highcharts/node-export-server#311]
I'm exporting charts with our self-hosted highcharts export server (v2.0.16), but when running multiple charts (~15-30) in sequence, we're getting the error:

0x03 error when performing chart generation: please check your input data

Sometimes it does work properly, but when we generate more charts, the likelihood of failure seems to increase.

I've also tried to increase the amount of workers to 20 and the timeoutThreshold to 60.000, but no luck so far.

Is there any fix or workaround to make sure we can export our charts properly?

When running the same chart requests at http://export.highcharts.com everything does work fine..

**Comment by Prechan** [comment]
Same issue here, with volume increasing, export-server become somehow unstable.
Input data is correct if requested alone.

Any news?

**Comment by acgtwentyone** [comment]
As stated on the readme -> In cases of batch exports, it's faster to use the HTTP server than the CLI. This is due to the overhead of starting PhantomJS for each job when using the CLI. 

So maybe it can clarify. Hope it helps you.

**Comment by jakubSzuminski** [comment]
Apologies for the late response! 

@acgtwentyone you're absolutely right - it's faster to use the HTTP server than the CLI for batch exports.

As stated in the **readme:**

> In cases of batch exports, it's faster to use the HTTP server than the CLI. This is due to the overhead of starting PhantomJS for each job when using the CLI.

Please try out exporting with the HTTP server and let me know if it works any better.

PS. We've recently released a beta version of the Export Server (which now uses Puppeteer as its headless browser library) and this should no longer be an issue there.

Here's a short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information

In case you encounter any problems with the newest version, please report them on this repository and we will investigate them.
