### ISSUE TITLE
Documentation needs to be updated to reflect practical version dependencies (node.js, highcharts)

### ISSUE THREAD

**Issue by mthome** [highcharts/node-export-server#312]
#### Expected behaviour
installation instructions result in a functional server.

#### Actual behaviour

Following the instructions verbatim results in a broken system because of undocumented and unenforced dependencies.

#### Reproduction steps
 

Specific issues:

- the current release of node-export-server is incompatible with the default version of highcharts, erroring with "phantom worker 1 unexpected data - SyntaxError: Expected token ')'  phantomjs://code/worker.js:658 in loop" regardless of input or invocation style.
- the current release of node-export-server is incompatible with node.js@>= 16, failing with "the client closed the connection before the chart was done processing" while leaving the actual client hung waiting for a response when used in server mode, though the cli works.
- the current release of node-export-server is incompatible with node.js@14, workers hanging instead of processing requests in server mode.

Node.js@15 and Highcharts@8.1.2 is functional in server mode.  There are likely to be other functional combinations.

**Comment by JamesBarnes88** [comment]
@mthome this saved me so much time. Thank you! And I wish we could update this at some point, spent hours trying to make this work.

**Comment by pfreunbe** [comment]
We start to run into simmilar issues. Installing highcharts-export-server with node version 15.14.0 won't run the build.js / ask for the licence agreement or the highcharts version.
Running the server seems to work fine until you try the test curl and the "Export Server not configurd!" picture is exported.

We tried node 16, 15 (both wont run build.js during installation) and 14 (runs build.js during npm installation), with highcharts latest, 9.0.1 and 8.1.2. The server starts fine, spawns 4 phantom worker, finishes the work but saves the error image.

running build.js by hand or bulding the project from the git repo holds the same results.

Does anybody have similar issues?

**Comment by DunhamGitHub** [comment]
I had similar issues. **Node 12** works for me!

**Comment by jibaromar** [comment]
This resolved my issue 👍, thanks a lot, I was stuck for 2 days thinking that I'm installing it wrong. Thanks again.

**Comment by jakubSzuminski** [comment]
> - the current release of node-export-server is incompatible with the default version of highcharts, erroring with "phantom worker 1 unexpected data - SyntaxError: Expected token ')' phantomjs://code/worker.js:658 in loop" regardless of input or invocation style. 
> - the current release of node-export-server is incompatible with node.js@>= 16, failing with "the client closed the connection before the chart was done processing" while leaving the actual client hung waiting for a response when used in server mode, though the cli works. 
> - the current release of node-export-server is incompatible with node.js@14, workers hanging instead of processing requests in server mode.

You're completely right. That's the case for PhantomJS.

However, this should no longer be a problem in the latest Puppeteer-based version of the Export Server which I encourage you to try out.

Here's a short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information

Please feel free to report any problems you encounter with the newest version and we will investigate it. If we notice any incompatibilities (or you report them by creating an issue) we will update our docs to include all the necessary information.
