### ISSUE TITLE
Critical npm audit issue

### ISSUE THREAD

**Issue by ssgriffen** [highcharts/node-export-server#313]
#### Expected behaviour

npm audit would not product a critical audit

![image](https://user-images.githubusercontent.com/19702760/142061362-3bf1f957-62bb-480a-a5df-feb545ea8982.png)

**Comment by jakubSzuminski** [comment]
We're doing everything we can to reduce the number of vulnerabilities in our latest version of the Export Server, which I encourage you to try out.

Here's a short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information

In case you find any vulnerabilities in the newest version, please report them so we can investigate them.
