### ISSUE TITLE
Issue with colors.js

### ISSUE THREAD

**Issue by samgreen-spp** [highcharts/node-export-server#318]
#### Expected behaviour
Install should work as normal

#### Actual behaviour
Install is interrupted by an infinite loop of ASCII characters introduced intentionally via [colors.js](https://github.com/marak/colors.js/)

![image](https://user-images.githubusercontent.com/83816945/148707590-76b0b4f1-6b06-4ea8-8a6c-b3cba067b005.png)

#### Reproduction steps
```npm install -g highcharts-export-server```

This appears to be caused by the dependency of colors.js here https://github.com/highcharts/node-export-server/blob/64a6510c8247d4e6cf80b0348e4ed5e59426e59d/package.json#L22

Which needs to be set to the latest working version 1.4.0

Not sure if this has already come across your radar but here is the problem https://github.com/Marak/colors.js/issues/285

We've personally been able to fix this by simply installing the right version of colors before doing our install of the export server

```npm install --silent -g colors@1.4.0 highcharts-export-server```

But I wanted to let you know what was happening. Thanks guys!

**Comment by amirhosseinfaghan** [comment]
im having same problem but thanks to your command i can install the package for now until they fix it , thanks alot for sharing

**Comment by Pascal76** [comment]
I just tested:
npm install --silent -g colors@1.4.0
npm install highcharts-export-server -g --unsafe-perm 

and I got the same error than before:
npm ERR! path /usr/local/lib/node_modules/highcharts-export-server
npm ERR! command failed
npm ERR! signal SIGABRT
npm ERR! command sh -c node ./build.js
npm ERR! LIBERTY LIBERTY LIBERTY
npm ERR! LIBERTY LIBERTY LIBERTY
npm ERR! LIBERTY LIBERTY LIBERTY
npm ERR!                                    !             H|H|H|H|H           H__________________________________             H|§|§|§|H           H|* * * * * *|---------------------|             H|§|∞|§|H           H| * * * * * |---------------------|             H|§|§|§|H           H|* * * * * *|---------------------|             H|H|H|H|H           H| * * * * * |---------------------|             H|H|H|H|H           H|---------------------------------|          ===============        H|---------------------------------|            /| _   _ |          H|---------------------------------|            (| O   O |)          H|---------------------------------|            /|   U   |          H-----------------------------------             |  =/  |           H              _..._/            H              _|I/|_            H      _______/| H |/_______    H     /           / /          H    |          | | /         |  H    |          ||o||          |  H    |    |     ||o||     |    |  H    |    |     ||o||     |    |  H   Carl Pilcher
npm ERR! �e̴̢͇̹̠̺͕͉̗͉̝̭̠̽̓̌ͩ̀͡͝s̵̭̠͖̥̺̜͎͉̥̙̳̳ͨ̓̊̔̽̆̂ͣ́̚͡͡͝ͅͅ�ĭ̡̩̠͉̹̪̙̣̥̗̲̪͛̍̆̈͛͋ͣ̆ͦ̃̔ͧ̈̓̋ͭ̕�� ̸̴̨̨̟͔̪̻͍̗̈ͦͬ͂̀̓̓ͥͯͫ̆̍ͮ̏̀t̴̸̡̤̠̤̗̰͎ͮ̋͂̓ͣ̓̌͂ͪ̏̉̽̾̀̋�s̑͆ͪͪ̎ͭͫ̍͂ ҉ ҉̛͙͇̬̲͉́͢�i̵͎͓̹̬̙̞̠̍̑̈͑̓̔ͭ͛͆́̀̕͜���t̸̿̊͒͊̊�e̶̵̾̐ͭ͂ͦ͢�ş̟̳̘̙̰̜ͤ̀̀̒ͨͤͥͧͬ̉̊͗͛͐ͬ͟ṭ̷̶̢̬̜̮̳͚̙̗́̒̀̄̔̂̐̉̿̅́̇̓ͦ͌ͤ̽͢͟����tͮͨͨͤͥ̿̌̅̌͊ͭͭ̃͂̋���������e̾̇̄̉͒̊̏͛̂̀̚͟ ҉̸̳͇̜͚̬͙̞̣̥̟̗̘̣̭̳̮̤̭̫̼͈͍͖͜͝ş̐́̎͒̑ͭ̿̀̿̎̃͋̅ͧ̚͟��i̓̅̋̽͗͊̅ͪ̈ͩ̚�n̈ͮͦ͆ͧͨͩͯͦ͒͗̚ ҉̸̶̮͕̱͉̘̪͍͇̻̯�������n͊̒ͨͪͯ́ͪͥ̎ͫͮ͗�g̸͒̇͆̈̉̂̃͊ͮ͆͑̆͌̂ͪ ҉͈̖̠̝̳̞̺̠͎̠̙̣͟͠ ̴̧̭̼̯̥̣͎̾̌͆̓͞�ḙ͉͍̤̭̺̙̰̤̠͍̲̔͂́̇̆ͣ̈͂̓̐͑̈ͩͩ̾̚͠͠�ṭ̵̴̡̣͈̟͓̤̹͉͚̖̞̟̲̭̲͚ͥͬ̾̑͡͡�ñ̸̷̷̰͙̪̹͔̜͖̫̠̫͎̗̝̥̪̙̗͋̃͌́̍̋̊̿g̶̵̸̣̪̳͚͎͖͉̦̩̠̫͌̄ͭͪ̏̋̒̊ͤ̀ͩ̌̓̆̋̌͠ͅ

**Comment by Pascal76** [comment]
a warning about colors package: [https://twitter.com/louloulfx/status/1480491799961645056?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1480491799961645056%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.numerama.com%2Fcyberguerre%2F813825-un-developpeur-sabote-son-projet-open-source-et-paralyse-des-milliers-dapplications.html](url)

**Comment by samgreen-spp** [comment]
NPM have removed the problematic versions from the package so I believe this issue can be resolved https://github.com/Marak/colors.js/issues/285#issuecomment-1009437042
