### ISSUE TITLE
NPM install broken

### ISSUE THREAD

**Issue by jarrettj** [highcharts/node-export-server#319]
Hi,

Good day.

The npm install no longer works on our machines. I'm receiving a ton of gibberish in the logs.

#### Expected behaviour
Export server should install.

#### Actual behaviour
I would attached the entire log file but it is huge!

![Screenshot 2022-01-10 at 11 37 56](https://user-images.githubusercontent.com/777547/148744901-10c00f3a-6eeb-403b-a896-933eb5bfd86f.png)

![Screenshot 2022-01-10 at 11 38 16](https://user-images.githubusercontent.com/777547/148744921-9160eec2-445c-41db-9d35-796fd57d377d.png)

Simply ran:
```
npm install highcharts-export-server -g --unsafe-perm
```

**Comment by Pascal76** [comment]
similar issue for me:

node build.js
LIBERTY LIBERTY LIBERTY
LIBERTY LIBERTY LIBERTY
LIBERTY LIBERTY LIBERTY
                                   !             H|H|H|H|H           H__________________________________             H|§|§|§|H           H|* * * * * *|---------------------|             H|§|∞|§|H           H| * * * * * |---------------------|             H|§|§|§|H           H|* * * * * *|---------------------|             H|H|H|H|H           H| * * * * * |---------------------|             H|H|H|H|H           H|---------------------------------|          ===============        H|---------------------------------|            /| _   _ |          H|---------------------------------|            (| O   O |)          H|---------------------------------|            /|   U   |          H-----------------------------------             |  =/  |           H              _..._/            H              _|I/|_            H      _______/| H |/_______    H     /           / /          H    |          | | /         |  H    |          ||o||          |  H    |    |     ||o||     |    |  H    |    |     ||o||     |    |  H   Carl Pilcher
tͪ͑̏ͯ͋̂̈ͬ̅́̈͂̄̾ ҉̠̤̻̣͕͚̘͖̤̺̜̩̳̯͜͜�s̶̷̒͑ͬ̓ͨ̈͒ͦ̂ͤ̍̇͌͆̌ͪ̐͘����gͮ͌ͪͫ̋̿͐̓̀͒̚̚͘��t̶͚̯̰̗̜̺͈͓̼̭͍̠̊ͣͦ̔̋̍̏̄͌ͬͮ̀͢͝eͤ͒̇ͫ��������ȅͩ̃ͤ̍̆͛̅ͬ̓ͩͩ̕���ì̡̛͓̘̼̮̤̜̺͌ͬͫ̉̓̂ͭ͑̈ͣ̌̊ͮ̆̓̌n̾̿ͬͧ̓̔̈ͬ̎ͤ͐̋̓̑̉�� ̿̏̉̎̐̑̈ͨ ҉�tͮ̍ͯ̓̀̊͐ͨ̊̓ͯ̅ͯͯ̋ͭ̚͢��s̗͖̲̗̜̤̥͊ͥͪͩ̈͑̇ͪ̓̅͌̐̍͊̀ͫ̏̕͟͞t̋̂̎̄͌́͆̑ͪ̇ͬ̾͟���� ̶̻̗̣̥̰͉͚̮͙̿̓͋͊̌ͨ̈͢ť̯̠̩̩̥̒̿̋ͬͩ̓̄̀ͯ̀ͬ̕͜͟e̟̫͉̼̗̰̪͊͑͐ͫ̂̾̀͘͢͟͢ş̖̮̣̬͎͍̗̦̫̼̭̠̤̩ͬ͑ͭ̈ͬͧͦ́́͑̋ͤ̒͘͝ͅ��ǹ̸̶̲͍̳̞̯̘̰͉͇̮̟̖̲͂ͬ̊͡� ̡̼̮̤̱̺͉̼͉̖̮̞̹̒̏̇͌̌̉͐̈͋̈̈ͣ̍̿͆͢͡ͅt̴͎̰̝͈̦̎͗ͤ̌̂̆̆͆̆̓͒̀͢͞͠e̷̶̳̬̭͇̜̲͖̤̦̫̗͇̫͙͚̤ͩͩ̃ͦ̚s̵͎͍͈̩̖͈͎̰͓͇̻͓̭̱̖̗̃̑ͮ͌̑̈ͧͦ̐̄̚̕������ė̢͋͐͊͛͟�����g̿ͨ̎̒͆̈͆̈̎͐ͩ̎̿ͤ̔ͦ̏̽�
������g̐ͤ̈ͪ̿ͪͧ͋���e̸̶͍̮͉̫̻̟ͯ̅̒ͫ͆̄̾͢������ṱ̸̳̳̻̱͇̬͓̯͔͚̑̿ͥͭ͞����n̡͎̤̲̠͍̲͈̭̋̅ͨ͂͆̿̇̀̓́͘g̴̸̜̘͉̘̖̹͓̝̯̻̞͇̥̫̼̭̳̯͈̠̙̞̓͒̈̾́͞ ̷ͬ͂̋̍͛ͣͣ̈͑̔̆ͪ͋̅ͧ̎̂͘ ҉̶̮̘̙͓͈͇͖͍̀ͅ��s̏̀̽͂̏̐̽̿ͭ́͂̾͊̊̉̚����� ̨͔̣̙͓̇͛̐ͫ͐ͬͭ̅̐͞ṭ̸̡̰͓̖̦͍͓̺̱̗͕͉͚̗̮̼̪̓ͨ̈̌͜͢͡e̢̧̧͎͚͕̦̯͕ͥͮ̄ͥ͗̀̚���n̎ͣ̓̑̎̑͛̆ͩ̍ͪͧͮ͊ͤ̽̈̚���ţ̴ͥ̊̐̊ͫ̇̑͆ͨ̏͐͑̒̐̍̕ ҉̭̖̹͓̬͍̭̬̮̗̺̮̣͘e̶͎̩͖͖̥͙͍͙̤͔̳̜̞̣ͣ̐̓͆ͥ̿ͨ͌ͨͬͮͬ̈͠�t̏͒͊͆̄ͯ̚������eͬ̌̍̂̂ͬ͝�s̎̅ͤ̇ ҉̷̶̙̩̗̦̪̞̯̠͎̩͔̠̺̕��n̷̶̢̯͚̣̥̣̤̦̋̔̓͛͐ǵ̷ͫ̃ͯ̓́̐͐̄�

**Comment by Pascal76** [comment]
do you know when the rewrite (using puppeteer) will be deployed ?

**Comment by jarrettj** [comment]
Nope. I do not.

**Comment by MattBlissett** [comment]
Installing from the current master branch in Git works, though I don't know why: https://github.com/highcharts/node-export-server#install

For the sake of people searching, the corrupted text above is "testing testing testing" with many Unicode combining accents added:
```
t̃̆eͪ̋sͫͪ ̘̦ẗ̌iͦ̂n̊ͧǵ̇ ̏̆t́ͫe͌͊s̽͂tͥ̎iͧ͆n͋̚gͯ̈ ̾̏ ̶͎t͛̈e͒́ś̾t͂ͧ ̜̭iͫͥn̑̚gͪ͛ ͙͢ ͗ͮt͛̿eͩ̓s͆͌t̾̊í̅ ̩͘n͛ͭg͐̚ ̈ͥẗͣ ̙̲e̊̌ ̵̛s̍ͪt̃͑ï̏ń̽g̓́ ͂̔t̎̆eͣͫsͦ̈t͒̔i̎ͥn͒̍ġ̒ ̋ͪt͊ͥe͌̋ ͜͜sͬ̄t͂ͩi̅̿ ̨̗nͭͧg̍ͩ
ẗ̚ȇ̈ ̵͘sͭ̒t̐̽i̎̇ ̛̝nͭͩ  ̭́g̒ͩ ͋̒ ̶̠tͨ̈ ̶̀eͭ̐s͋̒t͛̓i̐͒n̆̆g̑͊ ̀́t̅͋ ̵̡e͆̿śͦtͬ͆ỉ͌n͑͛g̈̈ ̶͜ ͂̉tͭ̿eͥ̓sͯ̃tͫ̔iͪ̈n̈̓ĝͧ ́ͬẗ̍e̿̊s͐͌t͛̓i̎͆n̐̃ ̨̕ǧ̆ ̤̩ ͧ̓tͦ̈e̓̋  ̗͠ś̅t̽ͮi̓̓n̔ͤğ̀ ͫ̌ ̀͜t̀ͥe͋̐s̄̑t̎ͨ ̴̴ ̯̖i̓͒nͫͪg͌ͥ
t̆͆e͂͌s̽ͩt̊͌iͪ͆n̍͂g͑̈ ͦͨt̀̃ ͟͡e͐͂s̏̂t̍ͪ ̦ͅiͪ̌n̉͗gͨ̑ ͗̂ ̕͜t̽̈ ̧͘é͐s̊ͧẗͯiͬͤn̂ͣǧ̒ ̓̄t͗ͮĕ̿sͣ́tͯ͗ ̢͢i̐̋nͣ͊g̈̅ ͦ͋t͆͗e̅̅sͣ̓t͌̆iͣ͆ ̻͢n̐͆g̏͂ ̓͑t͋ͦé̋s̽̋tͨ͌i̐͒n͋̉g̑͐ ͩ̓tͬ̽e̒̈sͫͧt̒̐i̓̚nͭ͋g̐ͣ
```

It would also be useful if the repository had a tag for version 2.1.0.

**Comment by jarrettj** [comment]
Thanks @MattBlissett. Should have searched for install issues. Will close this issue as #318 covers it.
