### ISSUE TITLE
Export CLI : --batch is not working 

### ISSUE THREAD

**Issue by vinaykevadia** [highcharts/node-export-server#32]
when i pass only one json input file as parameter with --batch, it is not giving any error but it is also not generating output file. when i pass multiple input=output files with --batch. following is the error i am getting. 
![image](https://cloud.githubusercontent.com/assets/7442679/23542778/04ccb1ac-0015-11e7-9f84-9c05aeeba4a6.png)

**Comment by vinaykevadia** [comment]
i has tested it in version 1.0.9 but also version 1.0.10 still having this issue.

**Comment by cvasseng** [comment]
Thanks for reporting.

This is fixed in master now, will be pushed to NPM shortly.
