### ISSUE TITLE
Highcharts export server hangs and runs forever

### ISSUE THREAD

**Issue by danbrenden** [highcharts/node-export-server#322]
**Problem description:**
I’m currently testing Node Higharchart export server on Windows 2019 with CURL commands. The process hangs and runs forever with the following log message on the server: “the client closed the connection before the chart was done processing”. Testing is done locally with 127.0.0.1, localhost and Host IP. File is only created when the Curl command syntax is wrong.

Server: Windows 2019 (Version 10.0.17763 Build 17763)
Firewall: Tested with firewall turned on and off 

**Installed versions:**
Node:	Node.js v17.3.0 (also tried v16 with no luck)
Highcharts: v2.1.0
npm: npm@8.3.0

Starting server with log level 4:
highcharts-export-server --enableServer 1 --logLevel 4  

**Curl command:**
curl.exe -H "Content-Type:application/json" -X POST -d "{""infile"": {""series"": [{""data"": [29.9, 71.5, 106.4]}]}}" 127.0.0.1:7801 -o curl.png
Also tried from Powershell, with the same result. HTTP post does not work either.

**Detailed Log (level 4):**
[verbose] phantom 1 - spawning worker
[verbose] phantom 2 - spawning worker
[verbose] phantom 3 - spawning worker
[verbose] phantom 4 - spawning worker
[notice] http server started on 0.0.0.0:7801
[verbose] got incoming HTTP request 3022f28f17524cbaab12cc69e64703b3
[verbose] starting export
[verbose] attempting to export from raw input
[verbose] phantom - received work, finding available worker
[verbose] phantom - found available worker
[verbose] phantom 3 - starting work
[notice] phantom worker 3 finished work 3022f28f17524cbaab12cc69e64703b3 in 3063 ms
[notice] the client closed the connection before the chart was done processing
[notice] terminating, killing all running phantom processes

**Screenshots**
<img width="660" alt="HighchartsExportScreenshot2" src="https://user-images.githubusercontent.com/7086428/149587946-7ee93dea-2ec3-49b0-b04b-8870ca93baed.PNG">
<img width="881" alt="HighchartsExportScreenshot1" src="https://user-images.githubusercontent.com/7086428/149587949-be42aa42-e4a0-4ddc-a4c5-3f697cef952a.PNG">

**Comment by chrcar01** [comment]
I opened the [same issue](https://github.com/highcharts/node-export-server/issues/306#issue-1029687300) a while back, downgrading node to a version before 16 alleviated the issue for me.

**Comment by kevinbourassahoule** [comment]
Any chance this gets fixed for Node >15 with the export server's v3 release?

**Comment by DominicAlthaus** [comment]
I also ran into this issue and decided to have a look at it for a second before I give up.

I found that this fixes the issue: https://github.com/highcharts/node-export-server/pull/337

**Comment by jakubSzuminski** [comment]
This PR seems to solve it: https://github.com/highcharts/node-export-server/pull/337
Duplicate issue here: https://github.com/highcharts/node-export-server/issues/312

I regret to inform you that we do not have plans to update the PhantomJS-based version of the Export Server as Phantom has been deprecated for a few years now and there's a long list of issues related to it.

The good news is that we've recently released a beta version of the Export Server based on Puppeteer (a modern headless browser library). I encourage you to try it out (here's a [short setup guide](https://github.com/highcharts/node-export-server#puppeteer-version-information)).

In case you encounter any problems with the newest version, please report them and we will investigate them.
