### ISSUE TITLE
Environment variable value non-interpreted

### ISSUE THREAD

**Issue by DocBraaa** [highcharts/node-export-server#327]
#### Expected behaviour

I'm using environment variable to accept highcharts licence and choose what to include when installing the package.

The problem is in the build.js.

1. There isn't environment variable available to accept or decline "cdn scripts optional" so add one like "HIGHCHARTS_USE_OPTIONAL_CDN_SCRIPTS"

2. The useIfDefined function doesn't interpret the value of an environment variable. Remember an environment variable is always a string so even if the variable
HIGHCHARTS_USE_STYLED is set as 0 or false, it isn't interpreted so the value is always true according to the current function definition

Quick fix:

```ts
function useIfDefined(what, def, supposedToBeBoolean = false) {
  return (typeof what === 'undefined' ? def : 
    supposedToBeBoolean ? what == 'true' : what);
}

if (process.env.ACCEPT_HIGHCHARTS_LICENSE) {

    cdnURL = process.env.HIGHCHARTS_CDN || cdnURL;

    embedAll(
      useIfDefined(process.env.HIGHCHARTS_VERSION, 'latest'),
      useIfDefined(process.env.HIGHCHARTS_USE_STYLED, false, true),
      useIfDefined(process.env.HIGHCHARTS_USE_MAPS, true, true),
      useIfDefined(process.env.HIGHCHARTS_MOMENT, false, true),
      useIfDefined(process.env.HIGHCHARTS_USE_GANTT, true, true),
      getOptionals(cdnScriptsOptional, 
        useIfDefined(process.env.HIGHCHARTS_USE_OPTIONAL_CDN_SCRIPTS, false, true)
      )
    );
} else {
    console.log(fs.readFileSync(__dirname + '/msg/licenseagree.msg').toString().bold);
    startPrompt();
}
```

Thanks for the consideration of this problem. Have a nice day :-)

**Comment by jakubSzuminski** [comment]
Thanks for reporting and apologies for the late response!

We've recently released a beta version of the Puppeteer-based Export Server which I encourage you to try out (here's a short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information).

After we fix all the priority issues related to server health, we will dive deeper into this and check if all the environment variables with `''` are taken care of correctly.

_Internal note:_
Need to check & possibly refactor the `initConfig` method.
https://github.com/highcharts/node-export-server/blob/2a5d8df3d1e2f0b11a7984c55501507fd70d78a6/lib/schemas/config.js#L750-L774

**Comment by PaulDalek** [comment]
Closing this as it is related to the old, PhantomJS based, solution. Since v3.0.0 no prompt to accept specific options is used at start and all server related configuration can be set through the `./lib/schemas/config.js` and `.env` files (more info can be found in the [Readme](https://github.com/highcharts/node-export-server/tree/stable#highcharts-nodejs-export-server)).
