### ISSUE TITLE
Heatmap not rendered correctly

### ISSUE THREAD

**Issue by egoam** [highcharts/node-export-server#33]
Heatmaps are not rendered correctly when produced with the export server. Using the attached  configuration object at http://export.highcharts.com/ server the output produced looks misaligned.
[heatmapOptionsExample.txt](https://github.com/highcharts/node-export-server/files/817551/heatmapOptionsExample.txt)

**Comment by larsac07** [comment]
Hi, @egoam.

If you're referring to the skewed look of the heatmap, this can be reproduced with the same config in Highcharts: http://jsfiddle.net/larsac07/LLExL/7201/, so it's not an export server issue. It looks like an issue with your data. If you're sure it's not, please post your issue on the [highcharts repo](https://github.com/highcharts/highcharts).

**Comment by egoam** [comment]
Hi @larsac07,
You're right, the problem was in the way I was converting data before sending it to the export server.
Thanks for your support and sorry for the waste of time.

**Comment by larsac07** [comment]
No problem, @egoam. It happens :)
