### ISSUE TITLE
Depedency vulnerabilities

### ISSUE THREAD

**Issue by bensimian** [highcharts/node-export-server#349]
According to a few node vulnerability websites (snyk.io and nodesecurity.io), this package has a few high vulnerabilities (https://snyk.io/test/npm/highcharts-export-server/2.1.0)  caused by the packages phantomjs-prebuilt, async and body-parser. Is there any reason those haven't been updated yet?
Thanks in advance

**Comment by PaulDalek** [comment]
Hi @bensimian,

Thanks for reporting this. As long as the `async` and `body-parser` can be updated, the most of the vulnerabilities come from [phantomjs-prebuilt](https://www.npmjs.com/package/phantomjs-prebuilt) package which is deprecated as currently PhantomJS is not being developed. Therefore, this unfortunately won't be fixed. We are currently working on [Puppeteer branch](https://github.com/highcharts/node-export-server/tree/enhancement/puppeteer) which soon will replace the PhantomJS solution.

**Comment by bensimian** [comment]
@PaulDalek thanks for you for the response. Looking forward to the upgrade
