### ISSUE TITLE
Export Map bubble

### ISSUE THREAD

**Issue by ppiccolo** [highcharts/node-export-server#35]
Hello,

There is a way to allow export server to correctly export map bubble, at the moment I got only the map without bubble, any suggestion ?

tnx in advance

**Comment by cvasseng** [comment]
Hi,

could you post a fiddle with a test case demonstrating the issue?

Thanks.

**Comment by cvasseng** [comment]
Given almost a year without a reply, I'm closing this. If you're still having issues,  please open a new issue.
