### ISSUE TITLE
Exporting a chart using the module pattern-fill doesn't work

### ISSUE THREAD

**Issue by Alays5656** [highcharts/node-export-server#354]
#### Expected behaviour

Exporting a chart using the module pattern-fill should work with the export server

#### Actual behaviour

Here is the jsfiddle :

https://jsfiddle.net/vs9hjne5/4/

Exporting a chart using the module pattern-fill doesn't work with the export server :

Here is a configuration : 
`{
 "series":[
  {
    "color":{
      "pattern":{
        "path":{
          "strokeWidth":1,
          "d":"M 0 0 L 10 10 M 9 -1 L 11 1 M -1 9 L 1 11"
        },
        "backgroundColor":"#5B799E",
        "color":"#F6A800",
        "width":10,
        "opacity":1,
        "height":10
      }
    },
    "data":[[1,10]],
    "type":"column"
  }
 ]
}`

with your service available here : https://export.highcharts.com/

here is the result :

![Capture d’écran 2022-06-29 à 10 35 41](https://user-images.githubusercontent.com/103569045/176401772-83f6d7af-37c2-408e-a2fc-6a163c0ae5e4.png)

with this configuration it works :

`{
 "series":[
  {
    "color":"red",
    "data":[[1,10]],
    "type":"column"
  }
 ]
}`

![Capture d’écran 2022-06-29 à 10 37 57](https://user-images.githubusercontent.com/103569045/176402569-477ee981-1d53-4638-bd02-7cc1629c412d.png)

#### Reproduction steps

Simple case works :

curl -H "Content-Type: application/json" -X POST -d '{"infile":{"series": [{"color":"red","type":"column","data": [29.9]}]}}' https://export.highcharts.com/ -o mychart.png

With pattern it doesn't :

curl -H "Content-Type: application/json" -X POST -d '{"infile":{"series": [{"color":{"pattern":{"path":{"strokeWidth":1,"d":"M 0 0 L 10 10 M 9 -1 L 11 1 M -1 9 L 1 11"},"backgroundColor":"#5B799E","color":"#F6A800","width":10,"opacity":1,"height":10}},"type":"column","data": [29.9]}]}}' https://export.highcharts.com/ -o mychart.png

**Comment by jakubSzuminski** [comment]
Apologies for the late response.

I've tested this out in our latest, Puppeteer-based Export Server and this should no longer be an issue.

I encourage you to try out our newest version with this short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information

In case you encounter any problems, please report them on this repository and we will investigate them.
