### ISSUE TITLE
Export chart for with yAxis with logarithmic type

### ISSUE THREAD

**Issue by gallandYoann** [highcharts/node-export-server#356]
#### Expected behaviour
![image](https://user-images.githubusercontent.com/11424591/176891894-a67cd477-95ba-457b-9845-0aa3387f5b80.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/11424591/176892129-3cc36dfd-6cf4-4586-8bd0-09e37ea873d7.png)
I use the same configuration for expected and actual behaviour. 
I suppose the logarithmic type it's don't use because it's the same graph than with linear type. 

#### Reproduction steps
Exporting a chart with this following configuration : [configuration.txt](https://github.com/highcharts/node-export-server/files/9028661/test.txt)
Or create a simple column chart with logarithmic type to yAxis.

Best regards, Yoann Galland

**Comment by jakubSzuminski** [comment]
Apologies for the late response!

Here's a demo with your config: https://jsfiddle.net/BlackLabel/2dchmpz6/

The "actual behavior" which you treat as "unexpected" is the same in Highcharts on the client side so it seems to be unrelated to the **Export Server**.

---

I encourage you to try out our latest Puppeteer-based version of the Export Server (here’s a short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information).

If you encounter any problems in the newest version of the Export Server, please report it and we will investigate it.
