### ISSUE TITLE
Highcharts Node.js Export Server  does not work

### ISSUE THREAD

**Issue by MendesWashington** [highcharts/node-export-server#358]
I am generating graphic image via server but a solution proposed by you is not working.
Every time we try to run it, it generates an image with this error, but the documentation doesn't say how we should configure it.
![image](https://user-images.githubusercontent.com/26007230/177453671-69fef8fb-b274-4e85-83d3-5498b51f7a4a.png)

**Comment by Ash-v-G** [comment]
Have you successfully ran the build script? The instructions on the image may solve your issue. I.e.:
```
cd node_modules/highcharts-export-server
node build.js
```

**Comment by believe-Mahesh** [comment]
Hi,

Is there any update on this issue. I am trying to set up export server as a service in AWS lambda. The response returns the same image. I tried the above steps mentioned and it does not help. Please assist. Here is what I do.

1. I had cloned node-export-server from github and ran npm install (agreed to all the prompts with yes except the CDN and the version for which I left blank)  and npm link. The node module is installed globally.
2. I navigated into my project repository and did npm install highcharts-export-server.
3. inside the project and switched to node_modules/highcharts-export-server and ran node build.js and carried out giving yes to all the promps except cdn and version.
4. copying my nodemodules, js file and package*.json into ecr and deploy in lambda.

When i try to invoke the gateway api connecvted to above lambda, it returns export server not configured.

**Comment by trimbilrepo** [comment]
> Hi,
> 
> Is there any update on this issue. I am trying to set up export server as a service in AWS lambda. The response returns the same image. I tried the above steps mentioned and it does not help. Please assist. Here is what I do.
> 
> 1. I had cloned node-export-server from github and ran npm install (agreed to all the prompts with yes except the CDN and the version for which I left blank)  and npm link. The node module is installed globally.
> 2. I navigated into my project repository and did npm install highcharts-export-server.
> 3. inside the project and switched to node_modules/highcharts-export-server and ran node build.js and carried out giving yes to all the promps except cdn and version.
> 4. copying my nodemodules, js file and package*.json into ecr and deploy in lambda.
> 
> When i try to invoke the gateway api connecvted to above lambda, it returns export server not configured.

tried to uninstall highcharts-export-server by `npm uninstall highcharts-export-server -9 --no-save`
go to your cloned repository, then rerun `npm install && npm link && node build.js`

I have the same problem, finally made it work using manual install from repository rather than direct npm

**Comment by jakubSzuminski** [comment]
Apologies for the late response. Related issue issue: https://github.com/highcharts/node-export-server/issues/399 (PhantomJS Export Server does not work well with some versions of Node.js).

I regret to inform you that we do not plan to update the PhantomJS-based version of the Export Server as PhantomJS has been deprecated for a long time now and a long list of issues arised from that.

The good news is that we've recently released a beta version which uses Puppeteer as its headless browser library where this should no longer be a problem (here's a [short setup guide](https://github.com/highcharts/node-export-server#puppeteer-version-information)).

In case you encounter any problems with the newest version, please report them on this repository and we will investigate them.
