### ISSUE TITLE
"--globalOptions" does not work during batch execution

### ISSUE THREAD

**Issue by umey111** [highcharts/node-export-server#36]
Hello,
"--globalOptions" does not work during batch execution.

**Comment by markdegrootnl** [comment]
Also does not work when using server mode.

**Comment by larsac07** [comment]
@markdegrootnl I can confirm that `globalOptions` is working quite well in **server mode**:

1. Run `highcharts-export-server -enableServer 1`
2. Run `curl -H "Content-Type: application/json" -X POST -d '{"infile":"{\"yAxis\": {\"type\": \"logarithmic\"},\"series\": [{\"data\": [0.029, 71.5, 1.06, 1292, 14400, 1.760, 135, 1480, 0.0216, 0.194, 9.56, 54.4]}]}","type":"png","globalOptions": "{\"lang\": {\"numericSymbols\": [\" thousands\", \" millions\"]}}"}' 127.0.0.1:7801 -o chart.png`
3. Open `chart.png` and see that setting the globalOptions `lang` in server mode works fine.

@umey111 In **batch mode**, `globalOptions` are indeed not respected. Adding a fix now.
