### ISSUE TITLE
Fetching Highcharts scripts behind proxy (enhancement/puppeteer)

### ISSUE THREAD

**Issue by pfreunbe** [highcharts/node-export-server#365]
While behind a proxy fetching scripts for the highcharts cache during the highcharts-export-server startup runs into ECONNREFUSED errors. Opening the URLs via the browser with the system configured proxy opens them just fine.
I did not find a way to configure a proxy here. Did I miss something?

**Comment by PaulDalek** [comment]
Hi @pfreunbe 

Sorry for the late reply. Recently I've added a possibility to configure a proxy for correctly fetching scripts from the 3rd party (in this specific case the CDN of Highcharts scripts). You can take a look at this PR: https://github.com/highcharts/node-export-server/pull/369 and try if this works. Let us know if that helped you with refusing connections.

**Comment by PaulDalek** [comment]
Fixed by https://github.com/highcharts/node-export-server/pull/369.

**Comment by meightymike** [comment]
Sorry to bother, but we need Credentials for our Corporate WebProxy.
Is there a way to pass them into the HighCharts-Export-Server?

I've already tried to set SERVER_PROXY_HOST to http://user:password@proxyname.domain but that dont seem to work
