### ISSUE TITLE
When axis labels are aligned left, space reserveSpace option is no longer respected

### ISSUE THREAD

**Issue by yoh-extradat** [highcharts/node-export-server#372]
curl http://localhost:8080 -H "Content-Type: application/json" -X POST -d '{"infile":{"chart":{"type":"bar"},"title":{"text":"Stacked bar chart"},"xAxis":{"categories":["Apples","Oranges","Pears","Grapes","Bananas"],"labels":{"align":"left","reserveSpace":true}},"yAxis":{"min":0,"title":{"text":"Total fruit consumption"}},"legend":{"reversed":true},"plotOptions":{"series":{"stacking":"normal"}},"series":[{"name":"John","data":[5,3,4,7,2]},{"name":"Jane","data":[2,2,3,2,1]},{"name":"Joe","data":[3,4,4,2,5]}]}}' -o mychart.png

should look like this: http://jsfiddle.net/highcharts/w315zkaf/5/

looks like this: 
![mychart](https://user-images.githubusercontent.com/41435569/196465837-305d4ae3-9108-4e89-9598-e7cdf6c4fd87.png)

**Comment by jakubSzuminski** [comment]
Apologies for the late response and thanks for reporting!

I've tested this out in our latest version of the Export Server which is now based on Puppeteer (a modern headless browser library) and everything seems to work as expected.

PhantomJS has been deprecated for a few years now and therefore, a lot of issues are related to the previous version of the Export Server. I regret to inform you that we do not plan to update the Phantom-based version of the Export Server, but if you switch to our latest version, you will not encounter this issue.

**Demo:** https://jsfiddle.net/BlackLabel/r3ph5mjc/

In case you encounter any problems with the newest version, please report them and we will investigate them.
