### ISSUE TITLE
Puppeteer status?

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/node-export-server#388]
The [current status](https://github.com/highcharts/node-export-server#current-status) suggests that v3 (based on puppeteer) would hopefully be released in Q2 of 2022.  It's now nearly Q2 of 2023.  What is the situation now?  Thanks!

**Comment by stefancplace** [comment]
Is there any news about the release date? Do you need support?

**Comment by lennarthohl** [comment]
Any updates here?

**Comment by kevinbourassahoule** [comment]
[This thread](https://www.highcharts.com/forum/viewtopic.php?f=9&t=50606&start=15) seems to contain the most recent updates.

FWIW, I managed to get it running with the approach described in the thread [here](https://www.highcharts.com/forum/viewtopic.php?f=9&t=50606#p185672).  The installation process was definitely more stable than the v2 for which I had to downgrade Node.  I wouldn't be comfortable using it in my production context until we get an official release, but my preliminary tests were successful, which I hope means the end is in sight!

**Comment by Pascal76** [comment]
I still see references to moment.js which is obsolete
Any chance to migrate to luxon ?

"scripts": [
      "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.3/moment.min.js"
    ]

**Comment by Subtletree** [comment]
> I still see references to moment.js which is obsolete Any chance to migrate to luxon ?
> 
> "scripts": [ "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.3/moment.min.js" ]

Is that related to this issue? Haven't tried luxon but day.js works basically as a drop in replacement for moment.

**Comment by Pascal76** [comment]
I wanted to say the puppeteer build is to avoid obsolete softwares but it will still use obsolete librairies

**Comment by jakubSzuminski** [comment]
Hi,

Just wanted to let you know that we've released a beta version of Puppeteer-based Export Server which you can read more about here: https://github.com/highcharts/node-export-server#puppeteer-version-information

Feel free to report any issues you find.

**Comment by floviolleau** [comment]
Hi,

Thanks a lot for this beta release. I'm trying to make it working with docker.
I use this Dockerfile but it not working.

```dockerfile
FROM node:alpine

WORKDIR /home/highchart-export-server

ENV ACCEPT_HIGHCHARTS_LICENSE=1
ENV HIGHCHARTS_USE_MAPS=0
ENV HIGHCHARTS_USE_GANTT=0
ENV HIGHCHARTS_VERSION=11.1.0

RUN apk update \
    && apk upgrade \
    && apk add --no-cache git patch \
    && rm -rf /var/lib/apt/lists/*

RUN npm install highcharts-export-server@3.0.0-beta.1

EXPOSE 7801

ENTRYPOINT ["node", "node_modules/highcharts-export-server/bin/cli.js", "--enableServer", "true", "--logDest", "/var/log/", "--logLevel", "2", "--constr", "chart", "--allowCodeExecution", "true", "--enableUi", "true"]
```

Am I doing it wrong?

When it starts, I have vundefined after the logo (version seems to not be found)
I try to make a GET call to /health but nothing happens.
And after a while, without doing something, I have a bunch of 
`Error creating a new page in pool entry creation! invalid page`

Any tips?
Thanks

**Comment by jakubSzuminski** [comment]
@floviolleau I'll look into it **asap** and let you know why that happens. I'll keep you posted.

**Comment by jakubSzuminski** [comment]
@floviolleau when it comes to printing the package version you're completely right - it did not work as expected because we did not consider what happens when running with `node ./bin/cli.js` and not with the `highcharts-export-server` command. I've already created a pull request here: https://github.com/highcharts/node-export-server/pull/407 and this will be solved within the next minor release.

When it comes to the error you get after sending a request - could you please share the request you're sending to the server? I've ran simple `http` requests and everything seemed to have worked. If you provide me with your requests I'll investigate why that happens.

**Comment by floviolleau** [comment]
@jakubSzuminski like explained a bit above, after a while, without doing something, I have a bunch of those error.
I only made a requests to /health for now

**Comment by jakubSzuminski** [comment]
Hi @floviolleau, thank you very much for sharing.

Just to keep the repository relatively clean, would you mind creating a completely new issue for your problem?

Include all the stuff that you've included here: CPU, RAM, your docker setup and the logs you get. We would go from there - we are currently performing stress tests and I believe that the problems you encounter might be related to what we may find during this stage.

Unfortunately, these types of issues are much more difficult to debug as their cause is inappropriate server resource management (or as you said, memory leaks), but we will try to find what's the cause as soon as possible.

Please create a new issue on this repo and we will go from there. If we need any more details I think it will be cleaner if there's a single issue for our discussion.

**Comment by floviolleau** [comment]
Hi,

I created https://github.com/highcharts/node-export-server/issues/412
