### ISSUE TITLE
Passing command line option to phantomjs

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/node-export-server#394]
How do I specify [command line options](https://phantomjs.org/api/command-line.html) to pass directly to phantomjs?  For example, `--web-security=false`.

These are different to the [command line options](https://github.com/highcharts/node-export-server#command-line-arguments) for the export server itself.

Specifically, I'm using this as a node module.

**Comment by jakubSzuminski** [comment]
Thanks for the question and apologies for the late response.

There's no built-in feature that allows you to add PhantomJS arguments in the `v2.1.0` of the Export Server. The easiest way to go is to modify the `spawnWorker` method (located in `./lib/phantompool.js` file) and add custom arguments to the spawned PhantomJS worker.

I regret to inform you that we do not plan to update the Phantom-based version of the Export Server as the PhantomJS library has been deprecated for a long time now and there's a long list of issues related to it. 

The good news is that we've recently released the Puppeteer-based version of the Export Server (here's a [short setup guide](https://github.com/highcharts/node-export-server#puppeteer-version-information)) where you can easily add arguments to the headless browser library.

This is explained in the [**_Loading JSON Configs_** section of the readme](https://github.com/highcharts/node-export-server/tree/enhancement/puppeteer#loading-json-configs). You can load your custom config file, where you have the `"puppeteer": { "args": [] }` array filled with all your custom arguments that you want to pass to the Puppeteer headless browser library.
