### ISSUE TITLE
HIGHCHARTS_VERSION needs pinning, get SyntaxError with the latest version

### ISSUE THREAD

**Issue by bamarch** [highcharts/node-export-server#396]
#### Expected behaviour

`curl -H 'Content-Type: application/json' -X POST -d '{"infile":{"title": {"text": "Steep Chart"}, "xAxis": {"categories": ["Jan", "Feb", "Mar"]}` works without errors without pinning `HIGHCHARTS_VERSION`

![image](https://user-images.githubusercontent.com/24650490/235717570-5f713eb3-ff0b-4f0b-a43b-ef5e9b81baf1.png)

#### Actual behaviour

a syntax error happens

![image](https://user-images.githubusercontent.com/24650490/235717135-66f70565-b5e8-45b8-8df1-f8d768b5ace8.png)

#### Reproduction steps
 

1) be sure not to set `HIGHCHARTS_VERSION` (it then defaults to "latest" which I believe is v11.0.0)

2) `curl -H 'Content-Type: application/json' -X POST -d '{"infile":{"title": {"text": "Steep Chart"}, "xAxis": {"categories": ["Jan", "Feb", "Mar"]}`

3) a syntax error happens

   ![image](https://user-images.githubusercontent.com/24650490/235717135-66f70565-b5e8-45b8-8df1-f8d768b5ace8.png)

note it works as expected when using `ENV HIGHCHARTS_VERSION="v10.3.3"`

![image](https://user-images.githubusercontent.com/24650490/235717531-4896426f-4324-44f1-9844-456ae45cda16.png)

**Comment by bamarch** [comment]
Including the Dockerfile, compose file and curl command for testing

Just stick the Dockerfile in a dir and replace `MyDirWithDockerfile` then `docker compose -f docker-compose.yml up` and run the `curl` command

```Dockerfile
FROM node:18-slim
WORKDIR /tmp

ENV ACCEPT_HIGHCHARTS_LICENSE="true"
ENV NODE_EXPORT_SERVER_SHA="5cbd3568dc9ce17d8ee74db1b9be70abd37fd5ec"

# pin version of highcharts the exporter uses, defaults to "latest"
#   note node-export-server not working with v11.0.0 as of right now
#   results in "SyntaxError: Use of reserved word 'let' in strict mode"
ENV HIGHCHARTS_VERSION="v10.3.3"

# install ttfs fonts from contrib repos since PhantomJS uses system install fonts to render pages
RUN sed -i 's/ main$/ main contrib/' /etc/apt/sources.list \
  && apt-get update  \
  && apt-get -y upgrade \
  && ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections \
  && apt install -y --no-install-recommends \
    bzip2 \
    fontconfig \
    libcap2-bin \
    git \
    patch \
    ttf-mscorefonts-installer \
  # install node highcharts server
  && git clone https://github.com/highcharts/node-export-server \
  && cd node-export-server \
  && git checkout ${NODE_EXPORT_SERVER_SHA} \
  && npm install \
  && npm link \
  && fc-cache -rfv \
  && apt-get -y remove \
    bzip2 \
    git \
    patch \
  && apt-get -y autoremove \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# run as non-root user (with no login shell)
RUN sed -i 's/^node:\(.*\):\/bin\/sh$/node:\1:\/sbin\/nologin/' /etc/passwd && \
    mkdir -p /mnt/tmp && \
    chown -R node:node /mnt/tmp
# node user - we must use the uid to satisfy runAsNonRoot
USER 1000
WORKDIR /home/node

# assign tmp dirs to writeable volumes since root fs is readonly
ENV TMPDIR=/mnt/tmp
ENV npm_config_cache /mnt/tmp

# OPENSSL_CONF env resolves PhantomJS compatibility issue with debian base
ENV OPENSSL_CONF=/dev/null

CMD [\
  "highcharts-export-server", \
  "--enableServer", "1", \
  "--port", "8080", \
  # logLevel: 0 = off, 1 = errors, 2 = warn, 3 = notice, 4 = verbose
  "--logLevel", "3" \
]
```

```yaml
version: '3.4'

services:
  chartexporter.server:
    build:
      context: MyDirWithDockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
```

```bash
curl \
  -H "Content-Type: application/json" \
  -X POST \
  -d '{"infile":{"title": {"text": "Steep Chart"}, "xAxis": {"categories": ["Jan", "Feb", "Mar"]}, "series": [{"data": [29.9, 71.5, 106.4]}]}}' \
  chartexporter.server:8080 \
  --max-time 5 \
  -o mychart.png
```

**Comment by azorius-mage** [comment]
I can confirm exact same problem for us adding ENV HIGHCHARTS_VERSION=10.3.3 to Dockerfile solved it. Maybe fix it in the puppeteer release......
