### ISSUE TITLE
Resources and multiple files

### ISSUE THREAD

**Issue by iherbak** [highcharts/node-export-server#397]
#### Expected behaviour
When i add multiple files inside the resources i can reference to whats inside the files.

#### Actual behaviour

Only the first file can be used.  All reference to functions in the second file cause chart data error.
#### Reproduction steps
 

Create two js files liek a.js and b.js

a.js content
var a = {
afunc : function(){
}
}
b.js content

var b = {
bfunc : function(){
}
}
add in the "resources": { "files": "a.js, b.js"}

add in the "callback": "function(chart) { b.bfunc() }" is not working

Thanks

**Comment by jakubSzuminski** [comment]
Thanks for reporting and apologies for the late response.

We've recently released a Puppeteer-based version of the Export Server where this should no longer be an issue.

As you can see in the `./lib/schemas/config.js` the:

> resources: An additional resource in a form of stringified JSON. It can contain files, js, and CSS sections.

Here's a short setup guide for the Puppeteer version: https://github.com/highcharts/node-export-server#puppeteer-version-information

In case you encounter any problems with the newest version please report them and we will investigate them.
