### ISSUE TITLE
luxon.js compatibility

### ISSUE THREAD

**Issue by Pascal76** [highcharts/node-export-server#398]
Hello,

I try to use LUXON (instead of moment.js which is obsolete)

I updated export_styled.html and export.html to add:
<script src="https://cdnjs.cloudflare.com/ajax/libs/luxon/3.3.0/luxon.min.js"></script>

I also added this after the first <style>....</style>
    <script>
      // luxon
      const DateTime = luxon.DateTime;
    </script>

But it does not work.
TypeError: undefined is not a function (evaluating 'Number.isNan(t.ts)')

Do you know what the issue is ?

**Comment by jakubSzuminski** [comment]
Thanks for reporting and apologies for the late response.

Recently, we've released a beta version of the Puppeteer-based Export Server which I encourage you to try out. It should be much easier to add custom resources and modify exporting configs.

Here's a short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information

1. Could you please specify how do you plan to use the `luxon.js` library with Export Server?
2. Could you please try using it within the `--callback` or `--resources` as explained [here](https://github.com/highcharts/node-export-server#command-line-arguments)?

**Comment by PaulDalek** [comment]
Luxon.js can be used as any other custom script, by simply placing the CDN url of a script into the array of the `scripts` object, in the `./lib/schemas/config.js` file.
