### ISSUE TITLE
New release for newer versions of node ( > 16)

### ISSUE THREAD

**Issue by HanMoeHtet** [highcharts/node-export-server#399]
I am getting error 

> the client closed the connection before the chart was done processing

I find commits in the repo that says the issue is fixed. But it seems the npm package is not updated.

**Comment by torso70** [comment]
I have the same issue. The export server doesn't work with node version > 15.
Please fix

**Comment by zodiake** [comment]
According to the plan that version 3 would be release in 2022 Q3 right?
Do we have any updates?
Thanks

**Comment by jakubSzuminski** [comment]
I regret to inform you that we do not plan to update the Export Server version based on PhantomJS as it has been deprecated for a few years now (and a long list of problems arised on the way).

The good news is that we've recently released a beta version which uses Puppeteer as its headless browser library where this should no longer be a problem.

I encourage you to try this out, here's a short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information

Please feel free to report any problems you encounter with the newest version and we will investigate it.
