### ISSUE TITLE
UUID has minimum version

### ISSUE THREAD

**Issue by mymainmanbrown** [highcharts/node-export-server#40]
My project has UUID version 2.0.1 installed, and because this project's package.json requires any uuid version, it won't install its own version of UUID.  I get the following error:

```
uncaughtException: { Error: Cannot find module 'uuid/v4'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (./node_modules/highcharts-export-server/lib/server.js:38:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
```

After I upgrade my project's version of UUID, I was able to successfully run the highcharts export server.

I'm not sure which version of UUID added the `uuid/v4` option, so I'm not sure what the absolute minimum is.  UUID version 3.0.1 (the current latest) worked for me though.

Additionally, to prevent other potential breaking changes from other libraries, you may also want to specify minimum version of the other dependencies that are listed as `"*"`.

**Comment by cvasseng** [comment]
Which version of the export server are you using? UUID has been included as `"uuid": ">=3.0.1"` in [`package.json`](https://github.com/highcharts/node-export-server/blob/master/package.json#L29) since version 1.0.11 on NPM, and since February 10th in master.

**Comment by wergeld** [comment]
This is found in highcharts-export-server\lib\server.js:
> const uuid = require('uuid/v4');

**Comment by larsac07** [comment]
@wergeld `const uuid = require('uuid/v4');` does not mean requiring a version of the `uuid` package, which was the issue here, but rather the [UUID version](https://en.wikipedia.org/wiki/Universally_unique_identifier#Versions).

Since updating highcharts-export-server to version 1.0.11 (or commit 54dba5fa100ad42188f85007f4fe0076e8a4c0af in master) fixes this problem, I'm considering this issue as closed.
