### ISSUE TITLE
Error: the client closed the connection before the chart was done processing

### ISSUE THREAD

**Issue by fundamental-ricardo** [highcharts/node-export-server#411]
"The client closed the connection before the chart was done processing"

It is a known issue for node > 16. I am on node 18 and having this issue. 
I can confirm that the fix https://github.com/highcharts/node-export-server/pull/337 works for node 18. 

Are there any plans to implement this fix in the coming updates?

**Comment by jakubSzuminski** [comment]
@fundamental-ricardo thanks for reporting!

I regret to inform you that we do not plan to update the Export Server version based on PhantomJS as it has been deprecated for a few years now (and a long list of problems arised on the way).

The good news is that we've recently released a beta version which uses Puppeteer as its headless browser library.

I encourage you to try this out, here's a short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information

Please feel free to report any problems you encounter with the newest version and we will investigate it.
