### ISSUE TITLE
[puppeteer] Make height/width styles optional

### ISSUE THREAD

**Issue by ivan-jelev** [highcharts/node-export-server#419]
Hello,

We are trying to migrate from exporter 2.x to 3.x-beta + Highchart 11+ and facing couple of issues.
One of them is unwanted container height/width CSS which doesn't reflect runtime changes to chart width/height. 

Use case: we have horizontal line chart with dynamic amount of horizontal columns/bars. Based on the amount of bars we are calculating the total height of the chart in the callback function.

Due to this css styles we are getting our chart cut (I assume scrolling appears on real page).

Plz consider to make this styles optional or maybe completely remove.

Note that it worked as expected in exporter v2.x
Plz let me know if you need more info.

Thanks.

https://github.com/highcharts/node-export-server/blob/fd0e4ed8a8a1509cd9ed6411405a24cef631f675/templates/template.html#L190-L215

**Comment by ivan-jelev** [comment]
Here is an example of the chart we are trying to export:

https://jsfiddle.net/ivanjelev/4qp0Lco9/

**Comment by jakubSzuminski** [comment]
Thanks for reporting @ivan-jelev!

Currently, we're working on a few prioritized issues related to server health (which is crucial for us to solve asap), but I'm adding this issue to our backlog for further development.

I'll keep you posted here.

**Comment by PaulDalek** [comment]
Fixed by https://github.com/highcharts/node-export-server/pull/440.
