### ISSUE TITLE
CommonJS support

### ISSUE THREAD

**Issue by cs-warshauer** [highcharts/node-export-server#424]
I reached out to support about this, and they suggested I post here. I’ve been attempting to install and use the RC version of the puppeteer export server. A recent change to using ES Modules has broken the build for me. 

Do you plan on offering a CommonJS version alongside the ESM? From my understanding, it shouldn’t be a large lift as shown here: https://stackoverflow.com/questions/74937600/how-to-support-es-modules-and-commonjs-modules-at-the-same-time

But I also understand if that's not on the roadmap!

**Comment by jakubSzuminski** [comment]
Hi @cs-warshauer, thanks for the suggestion!

What do you think about this @cvasseng?

**Comment by Anutrix** [comment]
https://github.com/highcharts/node-export-server/pull/426 should resolve this when finished I think.

**Comment by jakubSzuminski** [comment]
Closing as solved via https://github.com/highcharts/node-export-server/pull/426.
