### ISSUE TITLE
Export Server returning error after install - SyntaxError: Unexpected token S in JSON at position 0

### ISSUE THREAD

**Issue by PJPane** [highcharts/node-export-server#425]
I installed highcharts-export-server globally on windows machine per instructions. I then start the server with the command "highcharts-export-server -enableServer 1 -logLevel 4", everything appears normal. I then run the test curl below (the standard test from the documentation):

curl -H "Content-Type: application/json" -X POST -d '{"infile":{"title":{"text":"Steep Chart"},"xAxis":{"categories":["Jan","Feb","Mar"]},"series":[{"data":[29.9,71.5,106.4]}]}}' 127.0.0.1:7801 -o mychart.png

The server starts generating the chart then return the following error:
 work 844978b025f645d3929ffec5659e3251 could not be completed, sending: an error occured when rendering the chart: SyntaxError: Unexpected token S in JSON at position 0

I am running node v14.16.0

I have tried installing from scratch on 1 windows server and 2 windows PCs, all get the same error.

**Comment by jakubSzuminski** [comment]
Thanks for reporting @PJPane. I think it might be related to this topic: https://www.highcharts.com/forum/viewtopic.php?f=9&t=50838#p186185

Unfortunately, the PhantomJS-based version of the Export Server does not work with Highcharts 11.

Could you please try out our latest Puppeteer-based version of the Export Server and let me know if this issue still occurs? Here's a short setup guide: https://github.com/highcharts/node-export-server#puppeteer-version-information

**Comment by PJPane** [comment]
I am not trying to use the export server as a node module. Are you saying
that following the instructions on the github page to download/install/and
run the highcharts-export-server (non puppeteer version) is no longer
supported and no longer works?

**Comment by jakubSzuminski** [comment]
Unfortunately, the PhantomJS-based Export Server does not work with Highcharts 11.

Highcharts 11 got rid of the support for old IE browsers which is reflected in the PhantomJS which has been deprecated for a few years now and has no support for modern browsers.

We're currently making a switch to Puppeteer (a modern headless browser library) where you should not encounter this problem. Here's a short [setup guide](https://github.com/highcharts/node-export-server#puppeteer-version-information).

Please let me know if you encounter any issues with the latest version.
