### ISSUE TITLE
Export Server not rendering images

### ISSUE THREAD

**Issue by pamelafox** [highcharts/node-export-server#43]
I have been experimenting with various ways to embed images in HighCharts, and none of them seem to work on the highcharts-export-server.

For example, the following chart renders, but without the images:
http://jsfiddle.net/ZZ7Kd/135/
I have also tried data URIs with formatter(), local images, etc.

Should it be possible for it to render images, or is this an insurmountable permissions issue?
Thanks!

**Comment by larsac07** [comment]
HI, @pamelafox. I cannot reproduce the issue with the fiddle you provided (tries to get an old version of Highcharts from a URL that does not exist). However: the same JS works just fine with a more recent Highcharts version: http://jsfiddle.net/ZZ7Kd/304/. Hope this helps :)

**Comment by pamelafox** [comment]
Ah, sorry, I had fixed the JS include in my own version. What I mean is that the images do not render when piped through the server. Here's the server code:

`var chartOptions = {
      chart: {
        renderTo: 'container',
        marginRight: 80,
        type: 'spline'
    },
    xAxis: [{
        tickWidth: 0,
        lineWidth: 0,
        categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    }],
    series: [
    {
        data: [
            { y: 29.9 },
            { y: 71.5 },
            { y: 106.4 },
            { y: 129.2 },
            { y: 144.0 },
            { y: 176.0 },
            { y: 135.6 },
            { y: 148.5 },
            { y: 216.4 },
            { y: 194.1 },
            { y: 95.6 },
            { y: 54.4 }
        ]
    },
    {
        data: [
            { y: 220, marker: { symbol: 'url(http://www.highcharts.com/demo/gfx/sun.png)' }},
            { y: 220, marker: { symbol: 'url(http://www.highcharts.com/demo/gfx/sun.png)' }},
            { y: 220, marker: { symbol: 'url(http://www.highcharts.com/demo/gfx/sun.png)' }},
            { y: 220, marker: { symbol: 'url(http://www.highcharts.com/demo/gfx/snow.png)' }},
            { y: 220, marker: { symbol: 'url(http://www.highcharts.com/demo/gfx/sun.png)' }},
            { y: 220, marker: { symbol: 'url(http://www.highcharts.com/demo/gfx/sun.png)' }},
            { y: 220, marker: { symbol: 'url(http://www.highcharts.com/demo/gfx/sun.png)' }},
            { y: 220, marker: { symbol: 'url(http://www.highcharts.com/demo/gfx/snow.png)' }},
            { y: 220, marker: { symbol: 'url(http://www.highcharts.com/demo/gfx/sun.png)' }},
            { y: 220, marker: { symbol: 'url(http://www.highcharts.com/demo/gfx/sun.png)' }},
            { y: 220, marker: { symbol: 'url(http://www.highcharts.com/demo/gfx/sun.png)' }},
            { y: 220, marker: { symbol: 'url(http://www.highcharts.com/demo/gfx/sun.png)' }}
        ],
       	type: 'scatter'
    }
  ]
  };

    var exportSettings = {
      'type': 'png',
       options: chartOptions
    };

    Highcharts.initPool({maxWorkers: 2});
    Highcharts.export(exportSettings, function(err, res) {
        Highcharts.killPool();
        if (res) {
          resolve(res.data);
        } else {
          reject(new Error(err));
        }
      });
1

**Comment by larsac07** [comment]
Yes, it seems that the export server prematurely renders an image of the chart when producing an SVG from a Highcharts config. Exporting a chart via the export menu sends the chart SVG and not the config to the server, which seems to work fine.

**Comment by jacobweber** [comment]
Also looking for a way to do this.

**Comment by TorsteinHonsi** [comment]
@cvasseng with the old PhantomJS script we looked for references to online image files in the source, downloaded them first, then returned the snapshot once all image files were loaded.

**Comment by statista** [comment]
For me it doesn't work to render images in callback as well.

This my callback
`function(chart) {
    chart.renderer.image('https://www.highcharts.com/samples/graphics/sun.png', 100, 100, 30, 30).add();
}`

which I call like this

`highcharts-export-server 
--infile /home/highChartsExportImages/0/1439-1000.js
--callback ...Resources/js/logoCallback.js 
--type pdf 
--outfile /home/highChartsExportImages/0/1439.pdf

**Comment by matheenkhan** [comment]
Facing the same issue. Such as for the following JSON data structure, 

`"series":[{"data":[{"y":0.06,"x":3.5815,"marker":{"symbol":"url(http://ubuntueod.getcloudcherry.com/Impactanalysis/markers_nps_01.png)","width":40,"height":40}}}]`

The rendering is inconsistent in the sense that it loads at times and doesn't at others. I am assuming the highchart export server returns the graph much before the images from the URL are loaded onto it.
Alternatively, is there any other way to load images as markers onto the graph by passing such a parameter in the JSON file?

**Comment by statista** [comment]
any updates on this?

**Comment by TorsteinHonsi** [comment]
@gvaartjes This needs attention.

**Comment by cvasseng** [comment]
Commit cf04c66 implements a wait poll that waits for images to finish loading. It will timeout if the images aren't loaded within 2 seconds.

**Comment by 100phel** [comment]
@cvasseng please, reopen this issue. The fix has not helped. The SVGs are still loaded like 2 times out of 10. Here's the config that I use:
```
"series": [
    {
      "type": "line",
      "lineWidth": 0,
      "data": [
        {
          "x": 1592586000000,
          "y": 86,
          "marker": {
            "symbol": "url(https://dots.dataontouchdev.com/images/weather/yr_weather_symbols/svg/01d.svg)",
            "width": 40,
            "height": 40
          }
        },
...
```

**Comment by 100phel** [comment]
@cvasseng When will this commit be merged in master?

**Comment by 100phel** [comment]
@cvasseng I'm facing the same issue - the SVGs used in markers are loaded like 2 times out of 10:
```
"series": [
    {
      "type": "line",
      "lineWidth": 0,
      "data": [
        {
          "x": 1592586000000,
          "y": 86,
          "marker": {
            "symbol": "url(https://dots.dataontouchdev.com/images/weather/yr_weather_symbols/svg/01d.svg)",
            "width": 40,
            "height": 40
          }
        },
...
```

**Comment by pawelfus** [comment]
Answered in #186

**Comment by jesusmena** [comment]
I'm getting an error and I don't know if it's a problem with the libraries used by the server or if perhaps the chart data has some element that cannot be parsed by the export server. The chart JSON is as follows:

> Error occurred: TypeError: p.getTotalLength is not a function

`{
    "data": [
        {
            "x": [
                "25/10/24 0:0",
                "25/10/24 1:0",
                "25/10/24 2:0",
                "25/10/24 3:0",
                "25/10/24 4:0",
                "25/10/24 5:0",
                "25/10/24 6:0",
                "25/10/24 7:0",
                "25/10/24 8:0",
                "25/10/24 9:0",
                "25/10/24 10:0",
                "25/10/24 11:0",
                "25/10/24 12:0",
                "25/10/24 13:0",
                "25/10/24 14:0",
                "25/10/24 15:0",
                "25/10/24 16:0",
                "25/10/24 17:0",
                "25/10/24 18:0",
                "25/10/24 19:0",
                "25/10/24 20:0",
                "25/10/24 21:0",
                "25/10/24 22:0",
                "25/10/24 23:0"
            ],
            "close": [
                67989.27,
                67969.7,
                68066.99,
                68008,
                67744,
                67757.21,
                67646.21,
                67531.97,
                67658.5,
                67837.28,
                67855.23,
                68105.79,
                68061.9,
                68334,
                68311.31,
                67690.01,
                67670,
                66836.01,
                67026.61,
                66850,
                66937.99,
                67297.9,
                66626.42,
                66374
            ],
            "high": [
                68286.56,
                68010.01,
                68080,
                68234.34,
                68045.36,
                67875.08,
                67860,
                67727.3,
                67757.58,
                67878,
                67878.76,
                68183.78,
                68294.92,
                68427.62,
                68771.49,
                68543.3,
                67890.52,
                67814,
                67585.87,
                67237.01,
                67034.36,
                67297.9,
                67392.52,
                66729.6
            ],
            "low": [
                67903,
                67845.01,
                67836,
                67989.55,
                67691.44,
                67574.92,
                67596.92,
                67250,
                67286.28,
                67524.91,
                67678,
                67801.21,
                67959.68,
                67737.61,
                68140,
                67429.87,
                67355,
                66770.7,
                66006.6,
                66618.58,
                66620.38,
                66938,
                66618.01,
                66241.14
            ],
            "open": [
                68198.27,
                67989.26,
                67969.7,
                68066.99,
                68007.99,
                67744.01,
                67757.21,
                67646.21,
                67531.96,
                67658.49,
                67837.29,
                67855.23,
                68105.79,
                68061.89,
                68334.01,
                68311.3,
                67690.01,
                67669.99,
                66836,
                67026.62,
                66849.99,
                66938,
                67297.89,
                66626.43
            ],
            "increasing": {
                "line": {
                    "color": "green"
                }
            },
            "decreasing": {
                "line": {
                    "color": "red"
                }
            },
            "type": "candlestick",
            "xaxis": "x",
            "yaxis": "y"
        },
        {
            "x": [
                "25/10/24 0:0",
                "25/10/24 1:0",
                "25/10/24 2:0",
                "25/10/24 3:0",
                "25/10/24 4:0",
                "25/10/24 5:0",
                "25/10/24 6:0",
                "25/10/24 7:0",
                "25/10/24 8:0",
                "25/10/24 9:0",
                "25/10/24 10:0",
                "25/10/24 11:0",
                "25/10/24 12:0",
                "25/10/24 13:0",
                "25/10/24 14:0",
                "25/10/24 15:0",
                "25/10/24 16:0",
                "25/10/24 17:0",
                "25/10/24 18:0",
                "25/10/24 19:0",
                "25/10/24 20:0",
                "25/10/24 21:0",
                "25/10/24 22:0",
                "25/10/24 23:0"
            ],
            "y": [
                603.33465,
                508.33758,
                478.05039,
                513.74526,
                757.84685,
                688.27431,
                555.06302,
                1238.06394,
                931.52642,
                1010.31439,
                456.55528,
                1034.19925,
                658.31277,
                1218.60277,
                2041.27174,
                2145.61355,
                1661.39602,
                2503.52003,
                6126.68051,
                2527.96506,
                1056.82465,
                482.54189,
                660.45329,
                410.34256
            ],
            "xaxis": "x",
            "yaxis": "y2",
            "showlegend": false,
            "type": "bar"
        }
    ],
    "layout": {
        "title": {
            "text": "Last 1 days 1h chart (24 candles) with Key Candle Bar stress lines",
            "font": {
                "size": 40,
                "style": "underline"
            }
        },
        "showlegend": false,
        "plot_bgcolor": "white",
        "xaxis": {
            "rangeslider": {
                "visible": false
            },
            "shared": true
        },
        "yaxis": {
            "dtick": 500,
            "side": "right",
            "domain": [
                0.1,
                1
            ]
        },
        "yaxis2": {
            "dtick": 1000,
            "side": "left",
            "domain": [
                0,
                0.1
            ]
        },
        "xaxis2": {
            "dtick": 1000,
            "side": "left"
        },
        "annotations": [
            {
                "x": "25/10/24 23:0",
                "y": 68543.3,
                "text": "3.27 %",
                "font": {
                    "color": "green"
                },
                "showarrow": true,
                "arrowhead": 1,
                "xanchor": "right"
            },
            {
                "x": "25/10/24 15:0",
                "y": 68543.3,
                "text": 68543.3,
                "font": {
                    "color": "red"
                },
                "showarrow": false,
                "xanchor": "left",
                "yanchor": "top",
                "xshift": 2
            },
            {
                "x": "25/10/24 15:0",
                "y": 68543.3,
                "text": "25/10/24 15:0",
                "font": {
                    "color": "black"
                },
                "showarrow": false,
                "xanchor": "center"
            },
            {
                "x": "25/10/24 23:0",
                "y": 68543.3,
                "text": "3.27 %",
                "font": {
                    "color": "green"
                },
                "showarrow": true,
                "arrowhead": 1,
                "xanchor": "right"
            },
            {
                "x": "25/10/24 15:0",
                "y": 68543.3,
                "text": 68543.3,
                "font": {
                    "color": "red"
                },
                "showarrow": false,
                "xanchor": "left",
                "yanchor": "top",
                "xshift": 2
            },
            {
                "x": "25/10/24 15:0",
                "y": 68543.3,
                "text": "25/10/24 15:0",
                "font": {
                    "color": "black"
                },
                "showarrow": false,
                "xanchor": "center"
            },
            {
                "x": "25/10/24 23:0",
                "y": 67392.52,
                "text": "1.53 %",
                "font": {
                    "color": "green"
                },
                "showarrow": true,
                "arrowhead": 1,
                "xanchor": "right"
            },
            {
                "x": "25/10/24 22:0",
                "y": 67392.52,
                "text": 67392.52,
                "font": {
                    "color": "red"
                },
                "showarrow": false,
                "xanchor": "left",
                "yanchor": "top",
                "xshift": 2
            },
            {
                "x": "25/10/24 22:0",
                "y": 67392.52,
                "text": "25/10/24 22:0",
                "font": {
                    "color": "black"
                },
                "showarrow": false,
                "xanchor": "center"
            },
            {
                "x": "25/10/24 23:0",
                "y": 67392.52,
                "text": "1.53 %",
                "font": {
                    "color": "green"
                },
                "showarrow": true,
                "arrowhead": 1,
                "xanchor": "right"
            },
            {
                "x": "25/10/24 22:0",
                "y": 67392.52,
                "text": 67392.52,
                "font": {
                    "color": "red"
                },
                "showarrow": false,
                "xanchor": "left",
                "yanchor": "top",
                "xshift": 2
            },
            {
                "x": "25/10/24 22:0",
                "y": 67392.52,
                "text": "25/10/24 22:0",
                "font": {
                    "color": "black"
                },
                "showarrow": false,
                "xanchor": "center"
            },
            {
                "x": "25/10/24 23:0",
                "y": 66374,
                "text": 66374,
                "font": {
                    "color": "white",
                    "size": 12,
                    "shadow": "auto"
                },
                "showarrow": false,
                "xanchor": "left",
                "yanchor": 66374,
                "bgcolor": "purple"
            },
            {
                "x": "25/10/24 14:0",
                "y": 68771.49,
                "text": "68771.49 (3.61 %)",
                "font": {
                    "color": "white",
                    "size": 12,
                    "shadow": "auto"
                },
                "showarrow": false,
                "xanchor": "bottom",
                "yanchor": 68771.49,
                "yshift": 15,
                "bgcolor": "purple"
            }
        ],
        "margin": {
            "t": 90,
            "b": 110
        },
        "shapes": [
            {
                "type": "rect",
                "xref": "x",
                "yref": "y",
                "x0": "25/10/24 4:0",
                "y0": 68045.36,
                "x1": "25/10/24 11:0",
                "y1": 68045.36,
                "fillcolor": "red",
                "opacity": 0.2,
                "line": {
                    "width": 1,
                    "color": "red"
                }
            },
            {
                "type": "rect",
                "xref": "x",
                "yref": "y",
                "x0": "25/10/24 4:0",
                "y0": 68045.36,
                "x1": "25/10/24 11:0",
                "y1": 68007.99,
                "fillcolor": "red",
                "opacity": 0.2,
                "line": {
                    "width": 1,
                    "color": "red"
                }
            },
            {
                "type": "rect",
                "xref": "x",
                "yref": "y",
                "x0": "25/10/24 7:0",
                "y0": 67727.3,
                "x1": "25/10/24 9:0",
                "y1": 67727.3,
                "fillcolor": "red",
                "opacity": 0.2,
                "line": {
                    "width": 1,
                    "color": "red"
                }
            },
            {
                "type": "rect",
                "xref": "x",
                "yref": "y",
                "x0": "25/10/24 7:0",
                "y0": 67727.3,
                "x1": "25/10/24 9:0",
                "y1": 67646.21,
                "fillcolor": "red",
                "opacity": 0.2,
                "line": {
                    "width": 1,
                    "color": "red"
                }
            },
            {
                "type": "rect",
                "xref": "x",
                "yref": "y",
                "x0": "25/10/24 9:0",
                "y0": 67524.91,
                "x1": "25/10/24 17:0",
                "y1": 67524.91,
                "fillcolor": "green",
                "opacity": 0.2,
                "line": {
                    "width": 1,
                    "color": "green"
                }
            },
            {
                "type": "rect",
                "xref": "x",
                "yref": "y",
                "x0": "25/10/24 9:0",
                "y0": 67524.91,
                "x1": "25/10/24 17:0",
                "y1": 67658.49,
                "fillcolor": "green",
                "opacity": 0.2,
                "line": {
                    "width": 1,
                    "color": "green"
                }
            },
            {
                "type": "rect",
                "xref": "x",
                "yref": "y",
                "x0": "25/10/24 15:0",
                "y0": 68543.3,
                "x1": "25/10/24 23:0",
                "y1": 68543.3,
                "fillcolor": "red",
                "opacity": 0.2,
                "line": {
                    "width": 1,
                    "color": "red"
                }
            },
            {
                "type": "rect",
                "xref": "x",
                "yref": "y",
                "x0": "25/10/24 15:0",
                "y0": 68543.3,
                "x1": "25/10/24 23:0",
                "y1": 68311.3,
                "fillcolor": "red",
                "opacity": 0.2,
                "line": {
                    "width": 1,
                    "color": "red"
                }
            },
            {
                "type": "rect",
                "xref": "x",
                "yref": "y",
                "x0": "25/10/24 21:0",
                "y0": 66938,
                "x1": "25/10/24 22:0",
                "y1": 66938,
                "fillcolor": "green",
                "opacity": 0.2,
                "line": {
                    "width": 1,
                    "color": "green"
                }
            },
            {
                "type": "rect",
                "xref": "x",
                "yref": "y",
                "x0": "25/10/24 21:0",
                "y0": 66938,
                "x1": "25/10/24 22:0",
                "y1": 66938,
                "fillcolor": "green",
                "opacity": 0.2,
                "line": {
                    "width": 1,
                    "color": "green"
                }
            },
            {
                "type": "rect",
                "xref": "x",
                "yref": "y",
                "x0": "25/10/24 22:0",
                "y0": 67392.52,
                "x1": "25/10/24 23:0",
                "y1": 67392.52,
                "fillcolor": "red",
                "opacity": 0.2,
                "line": {
                    "width": 1,
                    "color": "red"
                }
            },
            {
                "type": "rect",
                "xref": "x",
                "yref": "y",
                "x0": "25/10/24 22:0",
                "y0": 67392.52,
                "x1": "25/10/24 23:0",
                "y1": 67297.89,
                "fillcolor": "red",
                "opacity": 0.2,
                "line": {
                    "width": 1,
                    "color": "red"
                }
            }
        ],
        "grid": {
            "rows": 2,
            "columns": 1,
            "subplots": [
                "xy",
                "x2y2"
            ],
            "roworder": "top to bottom",
            "vertical_spacing": 0.01
        }
    }
}`
