### ISSUE TITLE
Change the priority of options loading to adjust the `--loadConfig` usage

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/node-export-server#432]
#### Actual behaviour
Options are loaded in such a priority:

1. Options from the `lib/schemas/config.js` file.
2. Environment variables.
3. Command line arguments.
4. Custom JSON file (loaded by the `--loadConfig` option).

#### Expected behaviour
We need to change the priority to:

1. Options from the `lib/schemas/config.js` file.
2. Custom JSON file (loaded by the `--loadConfig` option).
3. Environment variables.
4. Command line arguments.

**Comment by jakubSzuminski** [comment]
Fixed with https://github.com/highcharts/node-export-server/pull/433.
