### ISSUE TITLE
globalOptions.lang doesn't work for HTTP Server

### ISSUE THREAD

**Issue by m-cisse-easy-live** [highcharts/node-export-server#434]
Hello,
 I'm here to report a bug concerning the HTTP server provided by highcharts-export-server with the Puppeter version. I started the server and when I passed the "globalOptions" option to have translated dates and well no modification took place on the generation of my graph. I made a console.log in the source code and the globalOptions instruction seems to be taken into account.

#### Expected behaviour
![image](https://github.com/highcharts/node-export-server/assets/127489442/eebacdae-a45e-4e99-982d-fcc4205cb3bd)
I was expecting xAxis dates to have "Déc" as the month, not "Dec", as I had specified this in globalOptions => lang

#### Actual behaviour
![image](https://github.com/highcharts/node-export-server/assets/127489442/b4455288-34ac-457a-b5ce-a3027feea59f)

#### Reproduction steps
```
# Install with the following command
npm i highcharts-export-server@3.0.0-rc.2

# Run the following command to start the HTTP server
node node_modules/highcharts-export-server/bin/cli.js --enableServer 1
```
```
# Do a cURL request on the current HTTP server
curl --location 'http://127.0.0.1:7801' \
--header 'Content-Type: application/json' \
--data '{"constr":"Chart","globalOptions:":{"global":{"useUTC":false},"lang":{"months":["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Août","Septembre","Octobre","Novembre","Décembre"],"shortMonths":["Jan","Fev","Mar","Avr","Mai","Juin","Juil","Août","Sept","Oct","Nov","Déc"],"shortWeekdays":["Di","Lu","Ma","Me","Je","Ve","Sa"],"thousandsSep":" ","weekdays":["Dimanche","Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi"]}},"infile":{"plotOptions":{"series":{"stacking":"","pointPadding":0}},"legend":{"enabled":false},"title":{"text":""},"xAxis":{"type":"datetime","title":{"text":"","style":{"fontSize":"0.6em"}},"labels":{"style":{"fontSize":"0.6em"}}},"yAxis":{"title":{"text":"Consommation (kWh)","style":{"fontSize":"0.6em"}},"labels":{"style":{"fontSize":"0.6em"}}},"series":[{"name":"Eléc Départ borne de charge ","data":[[1702115469000,8],[1702201869000,14],[1702288269000,15],[1702374669000,0],[1702461069000,4],[1702547469000,0],[1702633869000,17]],"color":"#a0a0a0","type":"column"}],"credits":{"enabled":false}},"type":"image/svg+xml","width":1200}'
```

**Comment by PaulDalek** [comment]
Hi @m-cisse-easy-live

Thank you for reporting this. We already prepared a fix for the behavior and here is the [PR](https://github.com/highcharts/node-export-server/pull/437). It should be released soon.

**Comment by jakubSzuminski** [comment]
Closing as fixed via https://github.com/highcharts/node-export-server/pull/437.
