### ISSUE TITLE
Puppeteer TROUBLESHOOTING on version 3 (Stable)

### ISSUE THREAD

**Issue by m-cisse-easy-live** [highcharts/node-export-server#436]
Hello, I'd like to report a bug in version 3 Puppeteer of highcharts-export-server.

I did the following command: 
```
 npm i -g highcharts-export-server@3.0.0
```

And run the following command: 
```
highcharts-export-server --enableServer 1
```

I get the following errors on server startup : 
```
TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (C:\Bitbucket\highchart\node_modules\@puppeteer\browsers\lib\cjs\launch.js:271:24)
    at ChildProcess.emit (node:events:526:35)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
Fri Nov 10 2023 11:57:58 GMT+0100 [notice] - [browser] attempting to get a browser instance (try 15)
Fri Nov 10 2023 11:57:58 GMT+0100 [notice] - [browser] failed: Error: Failed to launch the browser process! undefined
```

**Comment by m-cisse-easy-live** [comment]
In case I've found the problem, it's coming from https://github.com/highcharts/node-export-server/blob/stable/lib/browser.js#L122-L126 : 
```
  browser = await puppeteer.launch({
    headless: 'new',
    args: allArgs,
    userDataDir: './tmp/'
  });
```
And it should be replaced by : 
```
  browser = await puppeteer.launch({
    headless: false,
    args: allArgs,
    userDataDir: './tmp/'
  });
```

**Comment by jakubSzuminski** [comment]
Hi @m-cisse-easy-live,

We will investigate this issue. In the meantime, could you please share your:
- Node version
- npm version
- more details that might be hepful in finding a fix

When it comes to `headless: 'new'`, it has been described [here](https://pptr.dev/#default-runtime-settings). 

We have a new release scheduled for this week and there's a chance that this problem will disappear. I'll keep you posted.

**Comment by m-cisse-easy-live** [comment]
> Hi @m-cisse-easy-live,
> 
> We will investigate this issue. In the meantime, could you please share your:
> 
> * Node version
> * npm version
> * more details that might be hepful in finding a fix
> 
> When it comes to `headless: 'new'`, it has been described [here](https://pptr.dev/#default-runtime-settings).
> 
> We have a new release scheduled for this week and there's a chance that this problem will disappear. I'll keep you posted.

Hello @jakubSzuminski,

Thank you for your reply. I'll expect your reply within the week then. And I've attached my NodeJS and npm versions below : 
```
node -v
v18.17.1
-----------
npm -v
9.6.7
```
Now I can't reproduce the error and I don't know why. I reinstalled the library and went from version 3.0.1 to version 3.0.2 and I no longer get the error.

**Comment by PaulDalek** [comment]
Hi @m-cisse-easy-live,

Are you able to reproduce the error or does the v3.0.2 update resolve your problem?

**Comment by m-cisse-easy-live** [comment]
> ```
> highcharts-export-server --enableServer 1
> ```

Hello @PaulDalek,

It cant reproduced the error in v.3.0.2. So for me the problem is corrected. Thanks

**Comment by jakubSzuminski** [comment]
Great! Closing as completed with v3.0.2.
