### ISSUE TITLE
Using custom js code in callback

### ISSUE THREAD

**Issue by iherbak** [highcharts/node-export-server#443]
#### Expected behaviour
When I have a function defined in a resource file that I include either as files or js the callback function is able to use it.

#### Actual behaviour

The including of external resources happens after evaluating the callback function in export.js' export function, therefore it fails.
export function calls setAsConfig before reaching line 233 where resources are added.

#### Reproduction steps
Create a callback function that uses a function declared in a resource js file.

**Comment by PaulDalek** [comment]
Hi @iherbak,

Sorry for the late response. Regarding your question, for your purpose, you can use the `callback` option. The resources file (more specifically, the `js` and `files` properties) is used, as you noticed, to include the code after the chart creation.
