### ISSUE TITLE
Background transparency stopped working with version 3.0

### ISSUE THREAD

**Issue by hectoplasm** [highcharts/node-export-server#447]
We have updated our highcharts-export-server from version 2 to 3, and since that all images we are generating stopped showing background transparency, so when we insert them in a PDF with background colors charts are appearing with white background instead. On version 2 it was enough to set the property backgroundColor: 'transparent' to the "chart" object of the JSON.

We have already tried to set backgroundColor: 'rgba(0,0,0,0)' with same result, it continues to show white background. It's like if the alpha information gets lost when generating the image. See the attached screenshot:

![Captura de pantalla 2023-11-22 a las 13 48 40](https://github.com/highcharts/node-export-server/assets/146712094/8ea1189d-5891-4acd-8e6c-7ff11b815554)

Any idea if this is a puppeteer server related issue or if there is any configuration workarround to solve this?

**Comment by jakubSzuminski** [comment]
Thanks for reporting @hectoplasm!

Could you please share the:
- chart's config that you use?
- the entire request that you're sending to the server

I will then try to reproduce this issue locally and investigate what's wrong.

**Comment by hectoplasm** [comment]
Thanks for your fast reply @jakubSzuminski !

Here's one of our charts config:

`{
  "options": {
    "chart": {
      "type": "spline",
      "width": 350,
      "height": 170,
      "backgroundColor": "transparent"
    },
    "plotOptions": {
      "spline": {
        "negativeColor": "#DC0028",
        "color": "#5E6E7D"
      },
      "series": {
        "lineWidth": 4
      }
    },
    "colors": [
      "#5E6E7D"
    ],
    "xAxis": {
      "categories": [
        "2016",
        "2017",
        "2018"
      ],
      "labels": {
        "enabled": true,
        "style": {
          "fontSize": "18px"
        }
      }
    },
    "yAxis": {
      "lineColor": "#000000",
      "lineWidth": 1,
      "title": {
        "text": ""
      },
      "endOnTick": false,
      "maxPadding": 0.02,
      "min": 0,
      "labels": {
        "enabled": true,
        "useHTML ": true,
        "style": {
          "fontSize": "16px",
          "width": "50px",
          "text-align": "right",
          "min-width": "50px"
        }
      },
      "tickAmount": 4,
      "plotLines": [
        {
          "color": "#000000",
          "width": 2,
          "value": 0
        }
      ]
    },
    "series": [
      {
        "data": [
          {
            "y": 8194637000,
            "color": "#5E6E7D",
            "marker": {
              "symbol": "circle",
              "fillColor": "#FFFFFF",
              "lineColor": "#5E6E7D",
              "lineWidth": 2,
              "radius": 7
            }
          },
          {
            "y": 8450554000,
            "color": "#5E6E7D",
            "marker": {
              "symbol": "circle",
              "fillColor": "#FFFFFF",
              "lineColor": "#5E6E7D",
              "lineWidth": 2,
              "radius": 7
            }
          },
          {
            "y": 9136575000,
            "color": "#5E6E7D",
            "marker": {
              "symbol": "circle",
              "fillColor": "#FFFFFF",
              "lineColor": "#5E6E7D",
              "lineWidth": 2,
              "radius": 7
            }
          }
        ],
        "negativeColor": "#DC0028"
      }
    ],
    "credits": {
      "enabled": false
    },
    "title": {
      "text": ""
    },
    "subtitle": {
      "text": ""
    },
    "legend": {
      "enabled": false
    }
  },
  "globalOptions": {
    "lang": {
      "decimalPoint": ",",
      "thousandsSep": "."
    }
  }
}`


The request is being sent through a java RestTemplate from SpringFramework. Here is a screenshot of the code we use:

![Captura de pantalla 2023-11-23 a las 8 10 05](https://github.com/highcharts/node-export-server/assets/146712094/283f52c0-10ed-4249-a65e-85e76ed1a846)

The "json" object contains exactly the previous chart config stringified.

Tell me if you need more details to reproduce the request.

**Comment by jakubSzuminski** [comment]
Thanks! I've created a pull request here: https://github.com/highcharts/node-export-server/pull/450

You can try it out and see if that solves your problem.

This fix should be a part of our next minor release.

**Comment by hectoplasm** [comment]
Great!! Many thanks!

It may seem obvious, but how can I install highcharts-export-server from that particular branch? Until now I was installing your latest version through "npm -g install highcharts-export-server". I've tried "npm -g install "https://github.com/highcharts/node-export-server#bugfix/447-page-transparency" but with no luck, I get this error:

<img width="842" alt="Captura de pantalla 2023-11-23 a las 16 00 08" src="https://github.com/highcharts/node-export-server/assets/146712094/959c7772-021c-4972-b675-a6e58a832e04">

**Comment by jakubSzuminski** [comment]
Closing as fixed via #450.

---
I've merged the pull request to the `stable` branch and the `dist/` directory has been built.

You should be able to install the package from GitHub branch like this:
`npm i github:highcharts/node-export-server#stable` or like this: `npm i https://github.com/highcharts/node-export-server#stable`

Please let me know if that works.

**Comment by hectoplasm** [comment]
@jakubSzuminski after installing husky now I get this error when I try to install using any of your commands:

<img width="1115" alt="Captura de pantalla 2023-11-23 a las 16 54 18" src="https://github.com/highcharts/node-export-server/assets/146712094/9ff6139c-2793-4304-9d08-80e65b474ca7">

**Comment by jakubSzuminski** [comment]
Try running `npm i github:highcharts/node-export-server#stable` without the `-g` flag. It works on my & my colleague's machine. We will release a new minor version by the end of next week so if that does not work for you, you will be able to install it from npm normally very soon.

**Comment by hectoplasm** [comment]
Hi @jakubSzuminski! I managed to get it working without de -g flag. Now all charts have transparency again! Good work! Thanks!!
