### ISSUE TITLE
Highcharts expects point configuration to be numbers or arrays in turbo mode

### ISSUE THREAD

**Issue by dancojocar** [highcharts/node-export-server#457]
#### Expected behaviour
When using this configuration: 
[turbo.json](https://github.com/highcharts/node-export-server/files/13657440/turbo.json)

Getting the following error when generating a PNG or PDF using the node-export-server stable version:

```
Highcharts expects point configuration to be numbers or arrays in turbo mode
This error occurs if the series.data option contains object configurations and the number of points exceeds the turboThreshold. It can be fixed by either setting turbo Threshold to a higher value, or changing the point configurations to numbers or arrays.
In boost mode, turbo mode is always on, which means only array of numbers or two dimensional arrays are allowed.
See plotOptions.series.turboThreshold
```
Tried to disable the boost mode by loading the following using the --loadConfig:
```
"boost": {
        "enabled": false
},

```
Also tried to disable the `turboThreshold` by setting it to 0, also tried to set it to a really big value.
None of the above are working.

#### Actual behaviour

![out](https://github.com/highcharts/node-export-server/assets/79465/f427442b-0444-4898-a2dd-714538210c70)

**Comment by jakubSzuminski** [comment]
Thanks for reporting @dancojocar!

It seems to me like it's unrelated to the Export Server but to your Highcharts config. Could you please share the chart's config that you're using? I will then let you know what's the source of the problem.

**Comment by dancojocar** [comment]
Thanks @jakubSzuminski for your quick reply!
I'm executing with `--loadConfig batch.json --infile turbo.json --outfile out.png --type png `
And the content of batch.json is:
```
{
    "boost": {
        "enabled": false
    },
    "credits": {
        "enabled": false
    }
}
```

**Comment by jakubSzuminski** [comment]
@dancojocar just wanted to let you know that this issue have not slipped my mind is still on our backlog. However, after deploying the Export Server@3.0.3 with unusually heavy traffic on _export.highcharts.com/_ we need to first focus on fine-tuning the parameters so that the server available to all Highcharts users is working as expected. 

Then, this issue will become our priority. I will keep you posted about the progress.

**Comment by jszuminski** [comment]
@dancojocar with new updates, we've updated the structure of the json config files as well. Here's a file with the latest structure: https://github.com/highcharts/node-export-server/blob/master/lib/schemas/config.js

I've created a config.json file with the following content:
```JSON
{
    "export": {
        "globalOptions": "{\"credits\":{\"enabled\":false}}"
    }
}
```

And I'm running a simple: `node ./bin/cli.js --loadConfig config.json --infile input.json` where `input.json` is just:

```
{
    "series": [{
        "data": [1, 2, 3]
    }]
}
```

So, I belive that this is no longer an issue (loading of the config works as expected assuming you follow the proper structure of the config file).

Please test it out and let me know if it works as expected now.

**Comment by dancojocar** [comment]
@jszuminski Thank you very much! I can confirm that the issue was fixed!
