### ISSUE TITLE
How can I address the "missing module for treegraph" error in the stable branch of the export-server?

### ISSUE THREAD

**Issue by swapnilhadole-gg** [highcharts/node-export-server#459]
I added a new module to the config.js file, and the module installation was successful. However, when I make the following request, I encounter an error indicating the absence of the treegraph module. Is there a solution for this?

Request: 
curl --location 'https://localhost:7801' \
--header 'cache-control: no-cache' \
--header 'content-type: application/json' \
--header 'postman-token: 27681222-8352-e3e1-656c-cf73992dac0b' \
--data '{
    "infile": {
  "chart": {
    "inverted": false,
    "spacingBottom": 30,
    "marginRight": 200
  },
  "credits": {
    "enabled": false
  },
  "title": {
    "text": null
  },
  "legend": {
    "enabled": false
  },
  "series": [
    {
      "type": "treegraph",
      "clip": false,
       "keys": ["id", "parent", "name", "level"],
      "data": [
        {
          "id": "0.0",
          "parent": "",
          "name": "Intellect"
        },
        // ... (rest of the data)
      ],
      "dataLabels": {
        // ... (dataLabels configuration)
      },
      "marker": {
        // ... (marker configuration)
      },
      "levels": [
        // ... (levels configuration)
      ]
    }
  ]
}
}'

Please provide a solution to resolve the missing treegraph module error.

**Comment by jakubSzuminski** [comment]
Thanks @swapnilhadole-gg!

You're absolutely right - it seems that we've overlooked the `treegraph` module in the `schmeas/config.js` file. I've pushed a commit which fixed it: https://github.com/highcharts/node-export-server/commit/4a89ce0abcb4019a8b986938a5efd0fc1264e7f0

This fix will be available on npm with our next minor version of the Export Server.
