### ISSUE TITLE
1.0.15 broke exporting 

### ISSUE THREAD

**Issue by eugenelabonarsky** [highcharts/node-export-server#47]
Export doesn't work: 
`curl -H "Content-Type: application/json" -X POST -d '{"infile":{"title": {"text": "Steep Chart"}, "xAxis": {"categories": ["Jan", "Feb", "Mar"]}, "series": [{"data": [29.9, 71.5, 106.4]}]}}' 127.0.0.1:7801 -o mychart.png`

By the way version 1.0.14 is working

![mychart2222](https://cloud.githubusercontent.com/assets/2414095/26310102/47d1f7f0-3f08-11e7-83ff-7c5a6994004a.png)

**Comment by valdomir** [comment]
Same problem to me...

**Comment by cvasseng** [comment]
Sorry for the delay.

What's your configuration (OS/node version etc)?
