### ISSUE TITLE
All Exports Given Default "chart" Filename

### ISSUE THREAD

**Issue by andrewhathaway** [highcharts/node-export-server#470]
#### Expected behaviour

When a custom filename is given in a request, the returned filename should match the given filename.

#### Actual behaviour

Filenames being returned as the default `chart` filename, including when using the Highcharts `exportChart` API 

#### Reproduction steps

Example: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/exporting/filename/

<img width="305" alt="image" src="https://github.com/highcharts/node-export-server/assets/1188830/b98ca364-5dee-4aa0-808e-149de324899b">

**Comment by jakubSzuminski** [comment]
Hi @andrewhathaway,

Thanks for reporting!

This issue has already been solved here: https://github.com/highcharts/node-export-server/pull/462

The `filename` option should work as expected now.
