### ISSUE TITLE
Where to set lang: { numericSymbols: null }

### ISSUE THREAD

**Issue by rafael-trevisan** [highcharts/node-export-server#48]
Hey guys,

Where do I set `lang: { numericSymbols: null }` when using `const exporter = require('highcharts-export-server');` ?

**Comment by cvasseng** [comment]
Sorry for the late reply, in case you didn't figure it out already (which I'm guessing is not the case given your other issues regarding `globalOptions`), it's set through `globalOptions`.

```
let myExportOptions = {
   options: { ..chart config..},
   globalOptions: {
      lang: {..lang options..}
   }
};
```
