### ISSUE TITLE
No ability to change cache directory path

### ISSUE THREAD

**Issue by yankos** [highcharts/node-export-server#480]
#### Expected behaviour
```
const server = require("highcharts-export-server");
server.setOptions({
    other: {
        cacheDir: "/tmp/highcharts"
    }
});
```
Highcharts will use `other.cacheDir` from configuration instead hardcoded `const cachePath = join(__dirname, '.cache');`.

#### Actual behaviour
Highcharts use hardcoded `const cachePath = join(__dirname, '.cache');`.
Which caused an error when `cachePath` is not writable.

We package dependencies into a system package (deb, rpm, etc.) to speed-up deployment. So user can not write into the "node_modules" directory and it is causes a crash of Highcharts export server.

**Comment by jszuminski** [comment]
This has been fixed on the `master` branch with this pull request: https://github.com/highcharts/node-export-server/pull/488 so this should no longer be an issue from v4.0.0.

**Comment by jszuminski** [comment]
Completed via #488. Will be a part of v4.0.0.
