### ISSUE TITLE
Is .env file in root is now ignored?

### ISSUE THREAD

**Issue by UglyRichard** [highcharts/node-export-server#496]
#### Expected behaviour
.env 
HIGHCHARTS_NO_LOGO = false

has higher priority than in 

config.js
noLogo: {
      envLink: 'HIGHCHARTS_NO_LOGO',
      value: true,
      type: 'boolean',
      description:
        'Skip printing the logo on a startup. Will be replaced by a simple text.'
    }

#### Actual behaviour
i.e. HIGHCHARTS_NO_LOGO = false in .env and  PROXY_SERVER_HOST seems ignored or is preferred config "\lib\schemas\config.js" file over .env file in root

version: highcharts export server v3.1.1
nodejs version: v20.11.1
npm version 10.2.4

**Comment by jszuminski** [comment]
Thanks for reporting @UglyRichard!

I'll try to investigate this issue and prepare a pull request before the v4.0.0 release.

**Comment by jszuminski** [comment]
I've created a pull request for this: https://github.com/highcharts/node-export-server/pull/498 so this will no longer be a problem since the upcoming v4.0.0.

**Comment by jszuminski** [comment]
Completed via #498. Will be a part of v4.0.0.
