### ISSUE TITLE
Unable to setup on Ubuntu Server 22.04

### ISSUE THREAD

**Issue by LEEVEE1606** [highcharts/node-export-server#497]
refuses to install - get these errors listed below; extract from debug log file;

35 warn EBADENGINE Unsupported engine {
35 warn EBADENGINE   package: 'highcharts-export-server@4.0.0',
35 warn EBADENGINE   required: { node: '>=16.14.0' },
35 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
35 warn EBADENGINE }
36 warn EBADENGINE Unsupported engine {
36 warn EBADENGINE   package: '@puppeteer/browsers@2.1.0',
36 warn EBADENGINE   required: { node: '>=18' },
36 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
36 warn EBADENGINE }
37 warn EBADENGINE Unsupported engine {
37 warn EBADENGINE   package: '@rollup/plugin-terser@0.4.4',
37 warn EBADENGINE   required: { node: '>=14.0.0' },
37 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
37 warn EBADENGINE }
38 warn EBADENGINE Unsupported engine {
38 warn EBADENGINE   package: 'agent-base@7.1.0',
38 warn EBADENGINE   required: { node: '>= 14' },
38 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
38 warn EBADENGINE }
39 warn EBADENGINE Unsupported engine {
39 warn EBADENGINE   package: 'ansi-escapes@6.2.0',
39 warn EBADENGINE   required: { node: '>=14.16' },
39 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
39 warn EBADENGINE }
40 warn EBADENGINE Unsupported engine {
40 warn EBADENGINE   package: 'type-fest@3.13.1',
40 warn EBADENGINE   required: { node: '>=14.16' },
40 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
40 warn EBADENGINE }
41 warn EBADENGINE Unsupported engine {
41 warn EBADENGINE   package: 'cli-truncate@4.0.0',
41 warn EBADENGINE   required: { node: '>=18' },
41 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
41 warn EBADENGINE }
42 warn EBADENGINE Unsupported engine {
42 warn EBADENGINE   package: 'commander@11.1.0',
42 warn EBADENGINE   required: { node: '>=16' },
42 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
42 warn EBADENGINE }
43 warn EBADENGINE Unsupported engine {
43 warn EBADENGINE   package: 'cosmiconfig@9.0.0',
43 warn EBADENGINE   required: { node: '>=14' },
43 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
43 warn EBADENGINE }
44 warn EBADENGINE Unsupported engine {
44 warn EBADENGINE   package: 'data-uri-to-buffer@6.0.2',
44 warn EBADENGINE   required: { node: '>= 14' },
44 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
44 warn EBADENGINE }
45 warn EBADENGINE Unsupported engine {
45 warn EBADENGINE   package: 'degenerator@5.0.1',
45 warn EBADENGINE   required: { node: '>= 14' },
45 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
45 warn EBADENGINE }
46 warn EBADENGINE Unsupported engine {
46 warn EBADENGINE   package: 'eslint-plugin-prettier@5.1.3',
46 warn EBADENGINE   required: { node: '^14.18.0 || >=16.0.0' },
46 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
46 warn EBADENGINE }
47 warn EBADENGINE Unsupported engine {
47 warn EBADENGINE   package: 'execa@8.0.1',
47 warn EBADENGINE   required: { node: '>=16.17' },
47 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
47 warn EBADENGINE }
48 warn EBADENGINE Unsupported engine {
48 warn EBADENGINE   package: 'express-rate-limit@7.2.0',
48 warn EBADENGINE   required: { node: '>= 16' },
48 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
48 warn EBADENGINE }
49 warn EBADENGINE Unsupported engine {
49 warn EBADENGINE   package: 'fs-extra@11.2.0',
49 warn EBADENGINE   required: { node: '>=14.14' },
49 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
49 warn EBADENGINE }
50 warn EBADENGINE Unsupported engine {
50 warn EBADENGINE   package: 'get-east-asian-width@1.2.0',
50 warn EBADENGINE   required: { node: '>=18' },
50 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
50 warn EBADENGINE }
51 warn EBADENGINE Unsupported engine {
51 warn EBADENGINE   package: 'get-stream@8.0.1',
51 warn EBADENGINE   required: { node: '>=16' },
51 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
51 warn EBADENGINE }
52 warn EBADENGINE Unsupported engine {
52 warn EBADENGINE   package: 'get-uri@6.0.3',
52 warn EBADENGINE   required: { node: '>= 14' },
52 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
52 warn EBADENGINE }
53 warn EBADENGINE Unsupported engine {
53 warn EBADENGINE   package: 'http-proxy-agent@7.0.2',
53 warn EBADENGINE   required: { node: '>= 14' },
53 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
53 warn EBADENGINE }
54 warn EBADENGINE Unsupported engine {
54 warn EBADENGINE   package: 'https-proxy-agent@7.0.4',
54 warn EBADENGINE   required: { node: '>= 14' },
54 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
54 warn EBADENGINE }
55 warn EBADENGINE Unsupported engine {
55 warn EBADENGINE   package: 'human-signals@5.0.0',
55 warn EBADENGINE   required: { node: '>=16.17.0' },
55 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
55 warn EBADENGINE }
56 warn EBADENGINE Unsupported engine {
56 warn EBADENGINE   package: 'husky@9.0.11',
56 warn EBADENGINE   required: { node: '>=18' },
56 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
56 warn EBADENGINE }
57 warn EBADENGINE Unsupported engine {
57 warn EBADENGINE   package: 'lilconfig@3.0.0',
57 warn EBADENGINE   required: { node: '>=14' },
57 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
57 warn EBADENGINE }
58 warn EBADENGINE Unsupported engine {
58 warn EBADENGINE   package: 'lint-staged@15.2.2',
58 warn EBADENGINE   required: { node: '>=18.12.0' },
58 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
58 warn EBADENGINE }
59 warn EBADENGINE Unsupported engine {
59 warn EBADENGINE   package: 'listr2@8.0.1',
59 warn EBADENGINE   required: { node: '>=18.0.0' },
59 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
59 warn EBADENGINE }
60 warn EBADENGINE Unsupported engine {
60 warn EBADENGINE   package: 'log-update@6.0.0',
60 warn EBADENGINE   required: { node: '>=18' },
60 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
60 warn EBADENGINE }
61 warn EBADENGINE Unsupported engine {
61 warn EBADENGINE   package: 'is-fullwidth-code-point@5.0.0',
61 warn EBADENGINE   required: { node: '>=18' },
61 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
61 warn EBADENGINE }
62 warn EBADENGINE Unsupported engine {
62 warn EBADENGINE   package: 'slice-ansi@7.1.0',
62 warn EBADENGINE   required: { node: '>=18' },
62 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
62 warn EBADENGINE }
63 warn EBADENGINE Unsupported engine {
63 warn EBADENGINE   package: 'pac-proxy-agent@7.0.1',
63 warn EBADENGINE   required: { node: '>= 14' },
63 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
63 warn EBADENGINE }
64 warn EBADENGINE Unsupported engine {
64 warn EBADENGINE   package: 'pac-resolver@7.0.1',
64 warn EBADENGINE   required: { node: '>= 14' },
64 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
64 warn EBADENGINE }
65 warn EBADENGINE Unsupported engine {
65 warn EBADENGINE   package: 'prettier@3.2.5',
65 warn EBADENGINE   required: { node: '>=14' },
65 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
65 warn EBADENGINE }
66 warn EBADENGINE Unsupported engine {
66 warn EBADENGINE   package: 'proxy-agent@6.4.0',
66 warn EBADENGINE   required: { node: '>= 14' },
66 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
66 warn EBADENGINE }
67 warn EBADENGINE Unsupported engine {
67 warn EBADENGINE   package: 'puppeteer@22.4.0',
67 warn EBADENGINE   required: { node: '>=18' },
67 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
67 warn EBADENGINE }
68 warn EBADENGINE Unsupported engine {
68 warn EBADENGINE   package: 'puppeteer-core@22.4.0',
68 warn EBADENGINE   required: { node: '>=18' },
68 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
68 warn EBADENGINE }
69 warn EBADENGINE Unsupported engine {
69 warn EBADENGINE   package: 'rollup@4.12.1',
69 warn EBADENGINE   required: { node: '>=18.0.0', npm: '>=8.0.0' },
69 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
69 warn EBADENGINE }
70 warn EBADENGINE Unsupported engine {
70 warn EBADENGINE   package: 'signal-exit@4.1.0',
70 warn EBADENGINE   required: { node: '>=14' },
70 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
70 warn EBADENGINE }
71 warn EBADENGINE Unsupported engine {
71 warn EBADENGINE   package: 'socks-proxy-agent@8.0.2',
71 warn EBADENGINE   required: { node: '>= 14' },
71 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
71 warn EBADENGINE }
72 warn EBADENGINE Unsupported engine {
72 warn EBADENGINE   package: 'string-width@7.1.0',
72 warn EBADENGINE   required: { node: '>=18' },
72 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
72 warn EBADENGINE }
73 warn EBADENGINE Unsupported engine {
73 warn EBADENGINE   package: 'synckit@0.8.8',
73 warn EBADENGINE   required: { node: '^14.18.0 || >=16.0.0' },
73 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
73 warn EBADENGINE }
74 warn EBADENGINE Unsupported engine {
74 warn EBADENGINE   package: 'wrap-ansi@9.0.0',
74 warn EBADENGINE   required: { node: '>=18' },
74 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
74 warn EBADENGINE }
75 warn EBADENGINE Unsupported engine {
75 warn EBADENGINE   package: 'yaml@2.3.4',
75 warn EBADENGINE   required: { node: '>= 14' },
75 warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
75 warn EBADENGINE }

611 info run puppeteer@22.4.0 postinstall node_modules/puppeteer node install.mjs
612 info run puppeteer@22.4.0 postinstall { code: 1, signal: null }
613 timing reify:rollback:createSparse Completed in 1310ms
614 timing reify:rollback:retireShallow Completed in 0ms
615 timing command:install Completed in 12197ms
616 verbose stack Error: command failed
616 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
616 verbose stack     at ChildProcess.emit (events.js:314:20)
616 verbose stack     at maybeClose (internal/child_process.js:1022:16)
616 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
617 verbose pkgid puppeteer@22.4.0
618 verbose cwd /node-export-server
619 verbose Linux 5.15.0-101-generic
620 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
621 verbose node v12.22.9
622 verbose npm  v8.5.1
623 error code 1
624 error path /node-export-server/node_modules/puppeteer
625 error command failed
626 error command sh -c node install.mjs
627 error file:///node-export-server/node_modules/puppeteer/install.mjs:31
627 error   const {downloadBrowser} = await importInstaller();
627 error                             ^^^^^
627 error
627 error SyntaxError: Unexpected reserved word
627 error     at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
627 error     at async link (internal/modules/esm/module_job.js:42:21)
628 verbose exit 1
629 timing npm Completed in 12917ms
630 verbose unfinished npm timer reify 1711187345108
631 verbose unfinished npm timer reify:build 1711187355647
632 verbose unfinished npm timer build 1711187355650
633 verbose unfinished npm timer build:deps 1711187355650
634 verbose unfinished npm timer build:run:postinstall 1711187355717
635 verbose unfinished npm timer build:run:postinstall:node_modules/puppeteer 1711187355718
636 verbose code 1

**Comment by LEEVEE1606** [comment]
Perfect! Ubuntu repository only install node v12 as latest default - i didn't notice that!
I manually installed v21, and all works as expected.
Thank you!

**Comment by jszuminski** [comment]
Great, I'm happy to hear that!
