### ISSUE TITLE
Batch in Node.js Module

### ISSUE THREAD

**Issue by rafael-trevisan** [highcharts/node-export-server#50]
Hey guys,

Could someone provide some guidance to how exporting multiples charts at once using Node.js Module?

I have an array of charts objects that I'd like to loop through and export them one by one.

I'm getting stuck on that initPool / killPool and basically I'm getting only my last export.

Thanks in advance,

**Comment by cvasseng** [comment]
Hi, 

check out my answer [here](https://github.com/highcharts/node-export-server/issues/41). 

Let me know if you need more details!
