### ISSUE TITLE
Export CLI doesn't parse globalOptions json

### ISSUE THREAD

**Issue by rafael-trevisan** [highcharts/node-export-server#52]
Hey guys,

It looks like a bug in parsing the json

[Here](https://stackoverflow.com/questions/44251052/highcharts-node-js-export-server-how-to-export-pattern-fill-using-setoptions-d) are the details.

**Comment by rafael-trevisan** [comment]
I made a [PR ](https://github.com/highcharts/node-export-server/pull/53) with a fixing

**Comment by dhyey35** [comment]
@cvasseng `JSON.stringify(script)` on line 114 of `phantom/worker.js` also fixed my issue. Can you please check if change suggested by @rafael-trevisan is proper and merge it ?
