### ISSUE TITLE
Font missing in export.highcharts.com

### ISSUE THREAD

**Issue by cyrusho100** [highcharts/node-export-server#524]
Unicode characters do not display properly when exporting PNG from Highcharts' export server (export.highcharts.com)
![first-chart](https://github.com/highcharts/highcharts/assets/52916238/9f3f7e04-b3b4-4d1b-85c2-21793e127140)

**Comment by kyoya-atsushi-cyberwave** [comment]
@cyrusho100 
I am in charge of a service that uses the official server to output Highcharts graph images. Could you please provide an update on the status of the issue we encountered?

It seems that Japanese characters are now displaying correctly, but I would like to know if this means the bug has been fully resolved. Was it a temporary glitch that fixed itself, or was there an identifiable cause that has been addressed? We need to inform our end-users about the situation, so any information you can provide would be greatly appreciated.


![Uploading 性別年齢層の推移_男女合計_ドラッグストア_全国_2022年05月01日_2024年04月30日_商品-アメジスト なが～い伸縮包帯 M 7-5cm×9m.png…]()

**Comment by cyrusho100** [comment]
It also works fine for Traditional Chinese and Simplified Chinese. Thanks a lot.
