### ISSUE TITLE
[Windows] No success in getting export server to accept input via custom server

### ISSUE THREAD

**Issue by PaMcZee** [highcharts/node-export-server#55]
I have no issues running the highcharts-export-server module when producing charts without the --exportServer flag.  The issues arise if I attempt to set up my own export server. 

I have been trying to test the server as described by the ReadMe on main page using curl, i.e. 

> curl -H "Content-Type: application/json" -X POST -d '{"infile":{"title": {"text": "Steep Chart"}, "xAxis": {"categories": ["Jan", "Feb", "Mar"]}, "series": [{"data": [29.9, 71.5, 106.4]}]}}' 127.0.0.1:7801 -o mychart.png  

I am starting the highcharts server:
> highcharts-export-server --enableServer 1 

I know that the server is getting the input due to the errors (stated below), so it isn't an issue with communicating with the server.  The issue seems to be that no matter what I've tried, the JSON string doesn't get accepted due to parsing errors.   Here are the errors returned from using the curl command as stated in the readme:

highcharts:

> SyntaxError: Unexpected token '
>     at parse (C:\highcharts\export\node_modules\highcharts-export-server\node_mo
> dules\body-parser\lib\types\json.js:83:15)
>     at C:\highcharts\export\node_modules\highcharts-export-server\node_modules\b
> ody-parser\lib\read.js:116:18
>     at invokeCallback (C:\highcharts\export\node_modules\highcharts-export-serve
> r\node_modules\raw-body\index.js:262:16)
>     at done (C:\highcharts\export\node_modules\highcharts-export-server\node_mod
> ules\raw-body\index.js:251:7)
>     at IncomingMessage.onEnd (C:\highcharts\export\node_modules\highcharts-expor
> t-server\node_modules\raw-body\index.js:307:7)
>     at emitNone (events.js:86:13)
>     at IncomingMessage.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)

So I attempted to write the JSON string escaped, since Windows may have an issue, so here is my second attempt using curl:

> curl -H "Content-Type: application/json" -X POST -d "{\"infile\":\"{\"title\": {\"text\": \"Steep Chart\"}, \"xAxis\": {\"categories\": [\"Jan\", \"Feb\", \"Mar\"]}, \"series\": [{\"data\": [29.9, 71.5, 1
> 06.4]}]}\"}" 127.0.0.1:7801 -o mychart.png
> 

This time, curl returned "good" information, (I was getting "globbing" errors before):

>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  1266  100  1128  100   138  18193   2225 --:--:-- --:--:-- --:--:-- 18193
> 

However highcharts server now returns these errors:

> SyntaxError: Unexpected token t in JSON at position 13
>     at Object.parse (native)
>     at parse (C:\highcharts\export\node_modules\highcharts-export-server\node_mo
> dules\body-parser\lib\types\json.js:88:17)
>     at C:\highcharts\export\node_modules\highcharts-export-server\node_modules\b
> ody-parser\lib\read.js:116:18
>     at invokeCallback (C:\highcharts\export\node_modules\highcharts-export-serve
> r\node_modules\raw-body\index.js:262:16)
>     at done (C:\highcharts\export\node_modules\highcharts-export-server\node_mod
> ules\raw-body\index.js:251:7)
>     at IncomingMessage.onEnd (C:\highcharts\export\node_modules\highcharts-expor
> t-server\node_modules\raw-body\index.js:307:7)
>     at emitNone (events.js:86:13)
>     at IncomingMessage.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
> 

I even took the time to write a small Java program (on Windows) to set up a simple http POST call to see if I can successfully send JSON data to the server.  Again, server responds, but with same errors as above.  The content header is "application/json", as stated in the documentation.

Unless I am doing something obviously wrong, there seems to be something inconsistent or not being explicitly stated as to how to successfully produce a chart using the export server in Windows using a simple HTTP post (note:  I am **not** using JavaScript -- it's either Java or from command-line (using curl)).  The stumbling block seems to the the JSON string and a parsing failure.

Thanks for looking into this.

**Comment by cvasseng** [comment]
Hi, could you try to reinstall the export server to get the latest version? A similar issue was fixed in 1.0.16.
