### ISSUE TITLE
Can't get the export tool to run!

### ISSUE THREAD

**Issue by gregbengis** [highcharts/node-export-server#56]
If I have nodejs-legacy installed, I get this

/usr/local/lib/node_modules/highcharts-export-server/node_modules/express-form-data/express-form-data.js:3
let multipart = require('connect-multiparty');
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/highcharts-export-server/lib/server.js:36:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

if I uninstall it, and then 'apt-get install node' and run highcharts-export-server, I get no errors, it doesn't matter what parameters I pass, it just does nothing
agent@xxx:~$ highcharts-export-server --enableServer 1
agent@xxx:~$

What am I doing wrong?

**Comment by gregbengis** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

**Comment by gregbengis** [comment]
I also had to install the nodejs-legacy to get the package to install, else I was getting 'weird' errors

**Comment by cvasseng** [comment]
It looks like the legacy package node is too old. The server requires at least node 5.14.

Could you try installing the current one, and then starting the server with `highcharts-export-server --enableServer 1 --logLevel 4` and see if you get any errors?

**Comment by gregbengis** [comment]
Nothing from that -
However if I run 'node' or 'node --version' it does the exact thing, so I guess the problem is with node itself.. I am not sure what the issue is.

agent@xxx:~$ sudo apt-get install node
Reading package lists... Done
Building dependency tree
Reading state information... Done
node is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 184 not upgraded.

I'll see if I can find a solution

**Comment by cvasseng** [comment]
You may be installing the wrong package if you're on Ubuntu. There was already a node package in their repositories when node.js was released, so the package is named nodejs there.

Try `sudo apt-get install nodejs`, and remove the `node` package, and instead create a symlink like so `sudo ln -s "$(which nodejs)" /usr/bin/node`.

**Comment by gregbengis** [comment]
I wasn't able to install Node with apt-get, but I did  download the binary from their website, and now Highcharts works! (At least, it runs, I haven't tried to generate any graphs yet)

Thanks for your help

**Comment by cvasseng** [comment]
That's great!
