### ISSUE TITLE
Highcharts cache folder

### ISSUE THREAD

**Issue by istvanherbak** [highcharts/node-export-server#574]
#### Expected behaviour
The cache folder for Highcharts in config should work with absolute file path.

#### Actual behaviour
Currently the cache folder is always joined to the base folder of the highcharts-export-server thus always forcing the cache folder to be located under it.

**Comment by DanielRuf** [comment]
Duplicate of https://github.com/highcharts/node-export-server/issues/562.

**Comment by jszuminski** [comment]
Closing as it's a duplicate.
