### ISSUE TITLE
PDF option not working

### ISSUE THREAD

**Issue by ss1796** [highcharts/node-export-server#59]
Have installed node-export-server on a windows 2012 R2 server. Trying to create a PDF and whatever is getting created is a 30-40KB pdf file for the following command and the PDF is corrupt and cannot open that in any PDF reader. 
Is there any option that I'm missing for PDFs?

curl -H "Content-Type: application/json" -X POST -d '{"type":"pdf","infile":{"title": {"text": "Steep Chart"}, "xAxis": {"categories": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]}, "series": [{"data": [29.9, 71.5, 55, 66, 77, 44, 32, 99, 22, 11, 106.4]}]}}' TestServer:7801 -o mychart01.pdf

**Comment by cvasseng** [comment]
Does it work if you set the type to PNG (and change the output file from curl to .png)? Just want to be sure that the issue is limited to PDF exporting.

**Comment by ss1796** [comment]
I was running an older version and updated to the latest version and I can generate PDFs. Thanks.
