### ISSUE TITLE
forever example

### ISSUE THREAD

**Issue by beck24** [highcharts/node-export-server#6]
The docs suggest using https://github.com/foreverjs/forever but there's no example of how to do that.

I'm fairly new to nodejs and although I was able to get the server installed and working it's not clear how to do that in the context of forever.

This is what I've tried

create a file highcharts-node.js
```
// include the exporter module
const exporter = require('highcharts-export-server');

exporter.startServer(7801);
```

Then try to run it with forever:
```
forever start -l forever-highcharts.log -a -o highcharts.log -e error.log highcharts-node.js
```

I see it attempt to start the process then it fails.  The error is shown in the logs as

```
Error: Cannot find module 'highcharts-export-server'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/vagrant/netfloimg/highcharts-server.js:2:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
error: Forever detected script exited with code: 1
```

When I run ```require('highcharts-export-server');``` in the node command prompt I get a "cannot find module" error.

**Comment by beck24** [comment]
So I've finally figured this out... forever won't work if highcharts-export-server is installed globally as documented.

Install locally:

```
npm install highcharts-export-server
```

Then create a file for our node app called highcharts-server.js
```
// include the exporter module
const exporter = require('highcharts-export-server');

//Set up a pool of PhantomJS workers
exporter.initPool();

exporter.startServer(7801);
```


Then start the server with pm2
```
forever start -l forever-highcharts.log -a -o highcharts.log -e error.log highcharts-node.js
```

Though I've also found a newer more actively maintained and better documented alternative to forever - https://github.com/Unitech/pm2

```
pm2 start highcharts-server.js --name "highcharts-export-server"
```

Hopefully this can be incorporated into the docs somewhere to help the next guy.  Thanks!

**Comment by cvasseng** [comment]
Thanks!

I've added a section on running with forever (by cloning the export repo to avoid having to write a boilerplate script).

I will look into pm2 and add it to the docs once I've tried it out. :)

**Comment by beck24** [comment]
That's perfect, thank you!

**Comment by ShevtsivAndriy** [comment]
Work in my case **highcharts-export-server --enableServer 1 &**
The last symbol very important!
For detail google => "how run program in terminal and return control in terminal"

**Comment by crapthings** [comment]
if u want to pass options to highchart server you can 

pm2 start ./bin/cli.js --name='highchart-server' -- --enableServer=1 --port=8080

**Comment by thduttonuk** [comment]
For anyone trying `pm2 start highcharts-export-server -- --enableServer 1 --host 10.4.0.9 --port 443 --allowCodeExecution true`
