### ISSUE TITLE
Generate a few charts into one file

### ISSUE THREAD

**Issue by nizlobin** [highcharts/node-export-server#60]
Hey guys, I need to generate several charts into one file with single terminal command only (as a node module to simplify integrations) but have no idea how to do it. My simplified code with one chart look's like:

```
const exporter = require('highcharts-export-server');

let exportSettings = {
type: 'svg',
outfile: 'chart.svg',
constr: "StockChart",
options: {
rangeSelector: {
enabled: false
},
navigator: {
enabled: false
},
scrollbar: {
enabled: false
},
title: {
text: 'Simple stock chart'
},
series: [{
name: 'The pair 1',
data: processedCsv,
}]
}
};

exporter.initPool();

exporter.export(exportSettings, function (err, res) {
if (err) {
console.log(err)
}

exporter.killPool();
process.exit(1);
});
```

And I want to add another similar chart below to output file..

**Comment by kryft** [comment]
I don't think highcharts-export-server supports this; you will probably need to do export each chart separately and do the concatenation yourself somehow.

**Comment by wandiong** [comment]
you need to do asynchronous work with some callback

try something like this
`
var async = require("async");
var exporter = require('highcharts-export-server');

// you may need to do npm install async for it
var rep = {
chartA : "",
chartB : "",
chartC : ""
}
var exportSettings = {
    type: 'png',
    options: {
        title: {
            text: 'My Chart'
        },
        xAxis: {
            categories: ["Jan", "Feb", "Mar", "Apr", "Mar", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
        },
        series: [
            {
                type: 'line',
                data: [1, 3, 2, 4]
            },
            {
                type: 'line',
                data: [5, 3, 4, 2]
            }
        ]
    }
};
// perform here
exporter.initPool();
async.series ([
function(callback) {
exporter.export(exportSettings, function (err, res) {
rep.chartA = res.data
callback(null,"one")
});
}, function(callback) {
exporter.export(exportSettings, function (err, res) {
rep.chartB = res.data
callback(null,"two")
});
}, function(callback) {
exporter.export(exportSettings, function (err, res) {
rep.chartC = res.data
callback(null,"three")
});
}, function(callback) {
//input your execution to input the base64 file here
}
])

`

hope it works

**Comment by qwe900** [comment]
you can maybe try multiple axis on one plot ?

**Comment by abhikhatri67** [comment]
Any solution for this?
