### ISSUE TITLE
Must cd into the project DIR for the process to work

### ISSUE THREAD

**Issue by DunhamGitHub** [highcharts/node-export-server#607]
How can I configure highcharts (or puppeteer) so I can call the process from anywhere?
...
I cannot create a highchart process without being in the project's directory.
My projects sits in: `/opt/mx/reports_highcharts_export_server/`
I have to `cd` into that before calling the `cli.js` to create an svg from my json chart-data-file

- `cd /opt/mx/reports_highcharts_export_server/`
- `/opt/mx/reports_highcharts_export_server /opt/mx/reports_highcharts_export_server/node_modules/highcharts-export-server/bin/cli.js -infile /tmp/_test_in.json -outfile /tmp/_test.svg -type svg -constr StockChart`

[_test_in.json](https://github.com/user-attachments/files/17963573/_test_in.json)

#### Expected behaviour
<img width="813" alt="Screenshot 2024-11-30 at 00 59 36" src="https://github.com/user-attachments/assets/0cb244fd-9f8b-4aa5-9235-b6f0f6f4b7d1">

#### Actual behaviour

<img width="489" alt="Screenshot 2024-11-30 at 00 58 01" src="https://github.com/user-attachments/assets/4b059a09-abd0-4c64-954b-633ec7bc4b9e">

**Comment by jszuminski** [comment]
You're right, it only works from the same path currently. The workaround, however, is easy - just enter the directory of the server. Could you please let me know why entering the directory does not work for you?

**Comment by DunhamGitHub** [comment]
> You're right, it only works from the same path currently. The workaround, however, is easy - just enter the directory of the server. Could you please let me know why entering the directory does not work for you?

It's just different from the previous version I was using. Cannot get it to work on first try...

```
Process process = Runtime.getRuntime()
			      .exec(String.format("/opt/mx/reports_highcharts_export_server/node_modules/highcharts-export-server/bin/cli.js -infile /tmp/_test_in.json -outfile /tmp/_test.svg -type svg -constr StockChart", "/opt/mx/reports_highcharts_export_server/"));
		
```
