### ISSUE TITLE
Node API width parameter doesn't seem to work for SVG export

### ISSUE THREAD

**Issue by kryft** [highcharts/node-export-server#61]
All SVG charts exported via the Node API seem to have a width of 1200 (that is, the svg tag has the property width="1200"). Setting the width parameter for node-export-server doesn't have any effect, and neither does setting the width in the Highcharts chart options.

Setting the height in the Highcharts chart options does work, but I haven't found a way to set the width.

**Comment by cvasseng** [comment]
The size needs to be set in the chart config when using SVG.

Either of these will work:

- Set it in the chart config under [`chart.width`](https://api.highcharts.com/highcharts/chart.width)
- Set it in the chart config under [`exporting.sourceWidth`](https://api.highcharts.com/highcharts/exporting.sourceWidth)
