### ISSUE TITLE
Add listenToProcessExits to README

### ISSUE THREAD

**Issue by pamelafox** [highcharts/node-export-server#64]
I just found this option while looking through old issues, and I think this option may very well fix the issue I've been running into (uncaught exceptions taking down our EC2 node server), so I was very happy to find it. Can it be added to the README?

**Comment by cvasseng** [comment]
A bit late to the party, but the switch has been documented for some time in the options list. I also added a separate section in the readme explaining what this does, and the pitfalls involved.
