### ISSUE TITLE
Add silent option for cli, to avoid printing logo

### ISSUE THREAD

**Issue by josecanciani** [highcharts/node-export-server#68]
In bin/cli.js:103
`console.log(fs.readFileSync(__dirname + '/../msg/startup.msg').toString().bold.yellow);`

I would like to have a --silent option that avoids printing the startup.msg in the console, so I can get all log output.

I'm using the server and logging to stdout like this:
`highcharts-export-server --infile mypie.json --outfile mypie.pdf --type pdf --logDest /dev --logFile stdout --logLevel 2`

Thanks!

**Comment by cvasseng** [comment]
There's now a `-nologo 1` switch that skips the logo printing.  I opted to name it that instead of `--silent` because `silent` is usually used to suppress all logging, which is done by default in the export server when `--logLevel n` is not supplied
