### ISSUE TITLE
Exported chart when running HTTP producing blank charts

### ISSUE THREAD

**Issue by PaMcZee** [highcharts/node-export-server#69]
The following JSON produces a 4 line series chart.  
[chart.txt](https://github.com/highcharts/node-export-server/files/1192079/chart.txt)

Here is the chart produced by the export server when **not** running in server mode:
![02aed7b8-ca47-49be-ba41-950a45ad5b8a](https://user-images.githubusercontent.com/1283116/28849196-0115d48a-76e4-11e7-9a10-e10c276a6bc4.png)

However changing the "chart" node to "infile" so as to be used by the export server produces a PNG that is only around 3K in size when --enableServer is invoked

Here is the adjusted JSON:
[infile.txt](https://github.com/highcharts/node-export-server/files/1192081/infile.txt)

and here is the image produced by the export server running in server mode:

![partial_chart](https://user-images.githubusercontent.com/1283116/28849315-860efcde-76e4-11e7-8d27-bab93a317053.png)

The export server is running in Windows, and I am using version 1.0.16.  I started it as
highcharts-export-server --enableserver --host localhost

The thing is that the simple example on the readme page works correctly but not the more complex example as the one I am testing with.  I used both libcurl and a small Java app that HTTP posts, and the same issue occurs.

I don't know if there is something in the JSON that the server rejects, so I may be doing something wrong.  Would like for someone to look into this.  Thanks.

**Comment by cvasseng** [comment]
Hi,

it looks like your JSON is not following the correct format.

The chart options should be in the `infile` object in your POST body, as such (you can find the supported post arguments here https://github.com/highcharts/node-export-server#http-server):
    
    {
       "infile": {
           <chart options>
       }
    }

While in your file, the chart options are set directly in the body. 

I've attached a modified version of your file, could you please try it?
[infile.json.txt](https://github.com/highcharts/node-export-server/files/1193697/infile.json.txt)

**Comment by PaMcZee** [comment]
Thanks.

I see what the issue is and will correct it.
