### ISSUE TITLE
yAxis datalabels doesn't work?

### ISSUE THREAD

**Issue by zlink** [highcharts/node-export-server#70]

**Comment by TorsteinHonsi** [comment]
Can you elaborate please? Y axis data labels is not a thing... There is `yAxis.labels` and `series.dataLabels`.

**Comment by zlink** [comment]
gratitude for your reply.

**Comment by cvasseng** [comment]
Functions are not fully supported when running as a module. If you stringify your input without quotes, it will work, but if you define the function directly in an object like that it won't.

**Comment by JibranKalia** [comment]
Is there any timeline for formatter functions to be supported? Alternatively, are there any workarounds?

**Comment by cvasseng** [comment]
We are likely to improve this when we make the switch to chrome headless.

The workaround is to send your configuration unquoted and stringified to the export function (e.g. `exporter.export({infile: '{plotOptions: { columnRange: dataLabels: {formatter: function () {return 123;}}}}'});`)

**Comment by vikassaklecha** [comment]
@zlink @JibranKalia were you able to get any work around working? I have the same issue and have tried multiple things and not able to get around it.

var chartExporter = require('highcharts-export-server');
var settings = { chart : { legend : { formatter : function() { console.log("not coming here!!!"); } } } }
chartExporter.export(settings, function (err, res) { }

Also tried, but no luck with formatters
var settings = { chart : { legend : { formatter : "function() { console.log("not coming here!!!")(); }" } } }

Any help will be appreciated.

**Comment by uddhavb** [comment]
@vikassaklecha any luck with this?
