### ISSUE TITLE
"chart.forExport = true" leads to exception

### ISSUE THREAD

**Issue by jb3-2** [highcharts/node-export-server#71]
Thanks for all the great work in this module! I'm currently incorporating the npm module into my build and stumbled over this problem. 

The issue can be reproduced by opening http://export.highcharts.com/ and pasting the following options (the only relevant parameter is chart.forExport = true): 
`
{
  "chart": {
    "forExport": true
  },
    "xAxis": {
        "categories": [
            "Jan",
            "Feb",
            "Mar",
            "Apr",
            "May",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
            "Oct",
            "Nov",
            "Dec"
        ]
    },
    "series": [
        {
            "data": [1,3,2,4],
            "type": "line"
        },
        {
            "data": [5,3,4,2],
            "type":"line"
        }
    ]
}
`

![image](https://user-images.githubusercontent.com/7261044/28960382-ae6bc128-78fe-11e7-8e5e-8fa28140228a.png)

**Comment by PaulDalek** [comment]
The `forExport` option doesn't affect export process anymore on the new, Puppeteer based export server (tested on the `enhancement/puppeteer` branch).
