### ISSUE TITLE
Load event drawing

### ISSUE THREAD

**Issue by benmann497** [highcharts/node-export-server#75]
Hello, we're adding a line to a chart using the chart.events.load function. This works fine in the browser, but isn't rendering when using the node export server.

Is there an alternative or a setting to make the load event fire?

Thanks.

**Comment by cvasseng** [comment]
Hi,

how are you POSTing to the server? It needs to be formatted as JavaScript rather than JSON for function callbacks to work (i.e. no escaping of properties).

**Comment by benmann497** [comment]
Hi,

Thanks for the response. I am using the Node module, so am passing in a JS object with properties. Below is an example of the chart property, with load event. I have simplified the code for calculating where to draw the line, but even with static values it doesnt show...

```javascript
chart: {
        type: 'column',
        backgroundColor: '#F8F9FA',
        events: {
          load: function () {
            const renderer = this.renderer;

            const lineWidth = 2;
            const xPlotPoint = 50;
            const yStartPlotPoint = 150;
            const yEndPlotPoint = 250;

            renderer.path(['M', xPlotPoint, yStartPlotPoint, 'L', xPlotPoint, yEndPlotPoint])
              .attr({
                'stroke-width': lineWidth,
                stroke: 'red',
                dashstyle: 'solid',
                zIndex: 5
              })
              .add();
          }
        }
      }
```

Thanks.

**Comment by benmann497** [comment]
Thanks for these, I will give them a go shortly.

**Comment by benmann497** [comment]
Hello,

I was able to get this working by passing null as the dataOptions and customCode to add the load event.

Thanks for your help.

**Comment by jb3-2** [comment]
Great, thanks for letting getting back on this!
