### ISSUE TITLE
[Error: read ECONNRESET] code: 'ECONNRESET'

### ISSUE THREAD

**Issue by watergate7** [highcharts/node-export-server#77]
I have a C# client that sends requests to the Node server which I started via cli.js.
After the client gets the response, it shuts down and node server logs this error message.
Wed Aug 23 2017 20:45:07 GMT-0700 (Pacific Daylight Time) [error] socket error:
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 're
ad' }

And it's followed by hundreds of this message, then the node server crashed.
Wed Aug 23 2017 20:45:08 GMT-0700 (Pacific Daylight Time) [error] socket error:
[Error: This socket is closed.]

I think it's due to not correctly handling the error in server.js
line 308          socket.end('HTTP/1.1 400 Bad request\r\n\r\n');
This code in errorHandler is causing exception.

Could you please check? Thanks.

**Comment by cvasseng** [comment]
Which version of the export server are you running?

Based on the error message it sounds like the client closes the connection before the processing is done. The latest version added additional safeguards to handle that.

**Comment by watergate7** [comment]
Thanks for your quick response. I'm using the latest version actually.
As you said, it does handle that error case, but my point is that the handling code itself is causing exceptions again.

After I remove this line, the console just gives a simple error message and the node server won't crash.
line 308 socket.end('HTTP/1.1 400 Bad request\r\n\r\n');

The evidence is that before the node server crashes, hundreds of this message pop up in the console.
Wed Aug 23 2017 20:45:08 GMT-0700 (Pacific Daylight Time) [error] socket error:
[Error: This socket is closed.]

**Comment by cvasseng** [comment]
Sorry - I misunderstood you. I removed this line in  0c65e278b1af6c323b67c1aee8b4694452191392.

**Comment by watergate7** [comment]
Thanks. I'm closing this issue.
