### ISSUE TITLE
"no input given"

### ISSUE THREAD

**Issue by Coemgen4** [highcharts/node-export-server#78]
**Context**
___

I'm currently developing an engine to generate HighMaps script with Asp.Net Core.

To manage to do that, I used the API *Microsoft.AspNetCore.NodeServices* to execute a node module provided by HighChart (see https://github.com/highcharts/node-export-server).

I've followed this link to implement a solution https://davidsekar.com/angular/server-side-rendering-of-highcharts-in-net-core.

**Problem**
___

My code is included below :

Node module

    /**
     * https://github.com/highcharts/node-export-server
     */

    const exporter = require('highcharts-export-server');

    // Set up a pool of PhantomJS workers
    let config = {
        maxWorkers: 10,
        initialWorkers: 5,
        reaper: true,
        listenToProcessExits: true
    };
    // exporter.logLevel(4);
    exporter.initPool(config);

    // Export settings 
    // var exportSettings = { type: 'png', options: { title: { text: 'My Chart' }, xAxis: { categories: ["Jan", "Feb", "Mar", "Apr", "Mar", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] }, series: [{ type: 'line', data: [1, 3, 2, 4] }, { type: 'line', data: [5, 3, 4, 2] }] } };

    module.exports = {
        generateHighChart: (callback, configurationHighMaps) => {
            try {

                //console.log(configurationHighMaps);

                console.log(exporter);

                //var exportSettings2 = { type: exportSettings.type, options: exportSettings.chartOptions, scale: 2, sourceWidth: '1170', sourceHeight: '300' };

                // Perform an export
                // Export/Chart settings corresponds to the available CLI arguments.
                exporter.export(configurationHighMaps,
                    (err, res) => {

                        // try {
                        // The export result is now in res.
                        // If the output is not PDF or SVG, it will be base64 encoded (res.data).
                        // If the output is a PDF or SVG, it will contain a filename (res.filename).
                        // exporter.killPool();
                        // process.exit(1); Immediate exit will cause error in .Net Core NodeServices
                        //} catch (innerError) {
                        //  exporter.log(4, 'Kill throws error : ' + innerError);
                        //}
                        //callback(err, res);
                        callback(err, JSON.stringify(res));
                    });
            } catch (err) {
                callback(err, null);
            };
        }
    };

    // For testing
    // exp.generateHighChart(function () { }, exportSettings);

Controller :

    private async Task<StructureFichier> GenererCarteStatistiqueAsync(ConfigurationHighMaps poConfigurationHighMaps)
        {
            JObject loConfigurationHighMaps = JObject.FromObject(poConfigurationHighMaps);

            string lbytFichier = await mNodeServices.InvokeExportAsync<string>(@"wwwroot\HighMaps\v5\Moteur\MoteurHighMaps.js",
                                                                                "generateHighChart",
                                                                                loConfigurationHighMaps.ToString());

            string lsrCheminComplet = Directory.GetCurrentDirectory() + "/modeles/" + "test.png";

            //System.IO.File.WriteAllBytes(lsrCheminComplet, lbytFichier);

            return new StructureFichier(lsrCheminComplet);
        }

When I execute the method `GenererCarteStatistiqueAsync`, I have this error which is thrown by `InvokeExportAsync`. 

> Call to Node module failed with error: no input given

The parameter pass looks like this json object : https://jsfiddle.net/kpmvmajg/

**Question**

----------

What is wrong with the parameter that I have provided?

**Comment by cvasseng** [comment]
Could you post the contents of `configurationHighMaps` when you attempt an export?

**Comment by Coemgen4** [comment]
@cvasseng Oh sorry, I thought that I copied it. I edited my post (https://jsfiddle.net/kpmvmajg/)

**Comment by cvasseng** [comment]
Sorry for the delay on this. I can't see anything wrong with the dataset you provided, and it exports fine using the export server directly.

Which version of the export server are you running?

**Comment by Coemgen4** [comment]
I correct the trouble. It was caused by a wrong implementation in.NET Core !
I have another problem with the export but I created a post in the highmaps forum
(https://forum.highcharts.com/highmaps-usage-f14/how-use-highmaps-on-server-side-t39520/)
