### ISSUE TITLE
Running Export Server From Windows Task Scheduler Fails to Export PDF or SVG

### ISSUE THREAD

**Issue by wergeld** [highcharts/node-export-server#79]
We are running the export server via a bat file that is executed by Windows Task Scheduler:
`highcharts-export-server --enableServer 1 --sslPath C:\highchartsExport --sslOnly true --tmpDir C:\highchartsExport\tmp --logDest C:\highchartsExport\logs --logLevel 4`

This fails to export PDF or SVG files. The web page requesting it returns this error:

> error generating - check your json

The log file states:

> Wed Sep 06 2017 11:09:26 GMT-0400 (Eastern Daylight Time) [verbose] attaching exit listeners to the process..
> Wed Sep 06 2017 11:09:26 GMT-0400 (Eastern Daylight Time) [verbose] Pool started: 
>     maxWorkers: 4 
>     initialWorkers: 4 
>     workLimit: 60 
>     listening to process exit: true
> Wed Sep 06 2017 11:09:26 GMT-0400 (Eastern Daylight Time) [verbose] phantom 1 - spawning worker
> Wed Sep 06 2017 11:09:26 GMT-0400 (Eastern Daylight Time) [verbose] phantom 2 - spawning worker
> Wed Sep 06 2017 11:09:26 GMT-0400 (Eastern Daylight Time) [verbose] phantom 3 - spawning worker
> Wed Sep 06 2017 11:09:26 GMT-0400 (Eastern Daylight Time) [verbose] phantom 4 - spawning worker
> Wed Sep 06 2017 11:09:26 GMT-0400 (Eastern Daylight Time) [notice] https server started on port 443
> Wed Sep 06 2017 11:09:35 GMT-0400 (Eastern Daylight Time) [verbose] got incoming HTTP request 01a75b36b9024aa9af45c7fe37253448
> Wed Sep 06 2017 11:09:35 GMT-0400 (Eastern Daylight Time) [verbose] starting export
> Wed Sep 06 2017 11:09:35 GMT-0400 (Eastern Daylight Time) [verbose] parsing input as svg
> Wed Sep 06 2017 11:09:35 GMT-0400 (Eastern Daylight Time) [verbose] phantom - found available worker
> Wed Sep 06 2017 11:09:35 GMT-0400 (Eastern Daylight Time) [verbose] phantom 1 - starting work
> Wed Sep 06 2017 11:09:35 GMT-0400 (Eastern Daylight Time) [verbose] phantom - received work, finding available worker
> Wed Sep 06 2017 11:09:35 GMT-0400 (Eastern Daylight Time) [notice] phantom worker 1 finished work 01a75b36b9024aa9af45c7fe37253448 in 31 ms
> Wed Sep 06 2017 11:09:35 GMT-0400 (Eastern Daylight Time) [error] 01a75b36b9024aa9af45c7fe37253448 Error: ENOENT: no such file or directory, open 'C:\Windows\system32\tmp\chart.01a75b36b9024aa9af45c7fe37253448.svg'

System
OS: Windows Server 2016
node.js version: v6.11.2
npm version: 3.10.10
highcharts export server: installed via npm

This seems odd to me as I am explicitly giving it the directory to hold the tmp files (--tmpDir) it is still looking for the file in C:\Windows\system32\tmp - which does not exist.

If I run this just from the command line with the same parameters it works as expected.

**Comment by cvasseng** [comment]
The `-tmpdir` option now works as expected when running as a server.

Do let me know if you're still having issues after updating.

**Comment by wergeld** [comment]
Updated to latest 2.0.1 package and still getting error regarding temp directory. Method to update:
cd to module location
git pull origin master (I see change listings)
npm install
npm link
npm list -g to verify version (2.0.1)

Created bat file with the following:
`highcharts-export-server --enableServer 1 --sslPath C:\highchartsExport --sslOnly true --tmpDir C:\highchartsExport\tmp --logDest C:\highchartsExport\logs --logLevel 4`

Error still present when trying to export SVG or PDF:

> Fri Sep 15 2017 10:44:45 GMT-0400 (Eastern Daylight Time) [verbose] attaching exit listeners to the process..
> Fri Sep 15 2017 10:44:45 GMT-0400 (Eastern Daylight Time) [verbose] Pool started: 
>     maxWorkers: 4 
>     initialWorkers: 4 
>     workLimit: 60 
>     listening to process exit: true
> Fri Sep 15 2017 10:44:45 GMT-0400 (Eastern Daylight Time) [verbose] phantom 1 - spawning worker
> Fri Sep 15 2017 10:44:45 GMT-0400 (Eastern Daylight Time) [verbose] phantom 2 - spawning worker
> Fri Sep 15 2017 10:44:45 GMT-0400 (Eastern Daylight Time) [verbose] phantom 3 - spawning worker
> Fri Sep 15 2017 10:44:45 GMT-0400 (Eastern Daylight Time) [verbose] phantom 4 - spawning worker
> Fri Sep 15 2017 10:44:45 GMT-0400 (Eastern Daylight Time) [notice] https server started on port 443
> Fri Sep 15 2017 10:44:59 GMT-0400 (Eastern Daylight Time) [verbose] got incoming HTTP request 445831349584442aa3467f597d7bc967
> Fri Sep 15 2017 10:44:59 GMT-0400 (Eastern Daylight Time) [verbose] starting export
> Fri Sep 15 2017 10:44:59 GMT-0400 (Eastern Daylight Time) [verbose] parsing input as svg
> Fri Sep 15 2017 10:44:59 GMT-0400 (Eastern Daylight Time) [verbose] phantom - received work, finding available worker
> Fri Sep 15 2017 10:44:59 GMT-0400 (Eastern Daylight Time) [verbose] phantom 1 - starting work
> Fri Sep 15 2017 10:44:59 GMT-0400 (Eastern Daylight Time) [verbose] phantom - found available worker
> Fri Sep 15 2017 10:44:59 GMT-0400 (Eastern Daylight Time) [notice] phantom worker 1 finished work 445831349584442aa3467f597d7bc967 in 219 ms
> Fri Sep 15 2017 10:44:59 GMT-0400 (Eastern Daylight Time) [error] 445831349584442aa3467f597d7bc967 Error: ENOENT: no such file or directory, open 'C:\Windows\system32\tmp\chart.445831349584442aa3467f597d7bc967.svg'

**Comment by cvasseng** [comment]
try `--tmpdir` rather than `--tmpDir` - It's case sensitive.

**Comment by wergeld** [comment]
Changed to `--tmpdir` and still same issue.

**Comment by wergeld** [comment]
This issue is still not resolved.

**Comment by vitalvv** [comment]
I am having the same issue. The service works fine when running from cmd line, but fails on pdf and svg when running from the Task Scheduler.
Version 2.0.2

**Comment by vitalvv** [comment]
I was able to solve the errors by specifying the "Start in" folder in task properties -> actions tab -> edit the action -> then specify the folder, for example C:\highchartsExport\.
The only bug I get with this solution is that the "--tmpdir" option is not used and instead the server simply creates a "tmp" folder in "Start in" option.
