### ISSUE TITLE
Parameter "--host" doesn't seem to influence the listener interface

### ISSUE THREAD

**Issue by anonfriese** [highcharts/node-export-server#82]
Hi there,

I'm in the process of replacing the old java/tomcat server with node-export-server. Unfortunately I can't seem to be able to tell highcharts-export-server to use a different interface than 0.0.0.0 (i.e. all available interfaces) for listening to requests.

I want Highcharts to be able to run in Interface 127.0.1.1, since I potentially might want to run multiple Servers on different Versions later on, which would be hosted on different loopback interfaces (i.E. 127.0.1.1, 127.0.2.1 and so on...)

If I start highcharts-export-server with the following commandline:

 `/opt/nodejs/bin/node /opt/bin/node_modules/highcharts-export-server/bin/cli.js --host 127.0.1.1 --port 8439 --workers 8 --workersLimit 60 --logLevel 4 --logDest /opt/logs/highcharts/`

It doesn't seem to respect the --host; according to netstat it's running on :::8439 ...

In the code for starting the http server ( https://github.com/highcharts/node-export-server/blob/master/lib/server.js#L303 ) I also couldn't find a way to tell node-export-server to use a different interface. It seems to just use the provided Port (which works fine) but no way to specify the interface.

I then tried assigning a Hostname to this interface in /etc/hosts (localhost-1), which I can successfully ping and resolve. Using that instead of the real IP doesn't seem to solve anything either unfortunately...

Versions:
Debian Linux 9.1
NodeJS 6.11.2
Highcharts-Export-Server 2.0.0

**Comment by cvasseng** [comment]
A new version has been pushed to npm (2.0.2) which addresses this.

Please reopen this if you still experience issues.
