### ISSUE TITLE
How to export two charts?

### ISSUE THREAD

**Issue by miniil** [highcharts/node-export-server#83]
Hello 

According to this : https://github.com/highcharts/node-export-server/issues/41

Can you explain me or show me an example how to use Promise or async to take action when all the exports have been completed?

Thank you.

**Comment by cvasseng** [comment]
The gist is to wrap what's in #41 in a promise, and then use `Promise.all` to perform the export.

I added a demo for it here: https://github.com/highcharts/node-export-server/blob/master/tests/module/promises.js

You should be able to copy the `exportCharts` function into your project and use that.

Will consider adding this function as part of the library (`exporter.batchExport`) too.

**Comment by miniil** [comment]
Thanks a lot for your response.

After a long time trying to use this into my project it worked nearly fine.

But I've one problem : how to know wich is the first chart resolved.  I mean, because it's asynchronous, maybe the chart for the second value is resolved first, no?

Thanks for your response.

**Comment by cvasseng** [comment]
When using `Promise.all`, the promises are resolved in sequence.

So the first entry will always be the first chart and so on.

**Comment by cvasseng** [comment]
No problem, glad to help!

Please feel free to reopen this, or submit a new issue if you have any further issues with it.
