### ISSUE TITLE
Callback Function Not Executing

### ISSUE THREAD

**Issue by maggiecelentano95** [highcharts/node-export-server#84]
The documentation for starting your own highcharts export server implies that you can include a javascript file containing a callback function on start-up.

However, when I do this, the callback function is never executed.

How I start the server:
highcharts-export-server -enableServer 1 -callback callback.js

Contents of callback.js:
function(chart){chart.update({title{text:'NewTitle'}})}

Post request sent to the server:
curl -H "Content-Type: application/json" -X POST -d "{\"infile\":\"{series:[{data:[29.9,71.5,106.4]}]}\"}" 127.0.0.1:7801 --output charts.png

The chart in generated, but the title is not set. 

I have tried multiple variations of the content above (e.g. sending full file path, different content in callback.js...) but nothing is working. The only time I can get a callback function to execute is when I actually send the callback argument as a string in the POST request:

curl -H "Content-Type: application/json" -X POST -d "{\"infile\":\"{series:[{data:[29.9,71.5,106.4]}]}\",\"callback\":\"function(chart) {chart.update({title:{text:'New Title'}})}\"}" 127.0.0.1:7801 --output chart.png.

**Comment by cvasseng** [comment]
The `-callback` option is for CLI exports. If you want to do a callback when you POST, you need to use the `callback` POST argument (https://github.com/highcharts/node-export-server#http-server).

**Comment by maggiecelentano95** [comment]
Okay thank you! I had a feeling that sending a callback argument in the POST was perhaps the only way to do it, but it's good to know 100% now.
