### ISSUE TITLE
Running in server mode behind firewall

### ISSUE THREAD

**Issue by vitalvv** [highcharts/node-export-server#85]
I have an issue with running the server behind a firewall.

Lets say the server address is http://devserver and I run an IIS server there, which has PHP code.

I set up the highcharts server to run in SSL mode so I specified the ssl port 1115.

So whenever I try to test the export server at http://devserver:1115 from outside of my LAN I get a timeout error, probably because port 1115 is closed.

I don't really want to open that firewall for the Internet and I can't run the highcharts server on the http://devserver with standard SSL port because I run a secure website at that address.

Is there a way to configure the highcharts server to only accept requests if they are forwarded to let's say http://devserver/highchartsexport ?

What are my options?

Thank you.

**Comment by cvasseng** [comment]
There's no built-in way to do that.

You need to configure the server you're running http://devserver on to redirect /highchartsexport to localhost:1115 (if it's running on the same server).

**Comment by vitalvv** [comment]
Yes, I've tried that but the highcharts server responds with something like "Could not process GET /"

Meaning the request is redirected as a GET.

**Comment by cvasseng** [comment]
The export uses a POST, yes. But you should be able to do a POST redirect in your server config. 

This isn't related to the export server, and I don't really know much about IIS, so I don't know how helpful I can be. 

From a quick look in their docs, it looks like you need to do something like this:
    
    <rewrite>
            <rules>
                <rule name="RewritePost" stopProcessing="true">
                    <match url="OriginalURL" />
                    <conditions>
                        <add input="{REQUEST_METHOD}" pattern="^POST$" />
                    </conditions>
                    <action type="Rewrite" url="DestinationURL" />
                </rule>
            </rules>
     </rewrite>

**Comment by vitalvv** [comment]
Alright thanks! I'll check it out.

**Comment by vitalvv** [comment]
The redirect still will not work, because the request redirects the browser to an address with closed port 
 http://devserver:1115...
I solved my problem by making a php file and then redoing the post file there.
It seems to work.
