### ISSUE TITLE
Two modules that use the same code with highcharts-export-server as module

### ISSUE THREAD

**Issue by miniil** [highcharts/node-export-server#89]
Hi,

Can you help me with my code ?

First I have a module with a function getGraph that use highcharts-export-server as module.

function getGraph (value) {
  const exporter = require('highcharts-export-server');
  return new Promise(function (resolve, reject) {
    try {
      var exportSettings = {
        options: {
          title: {text: ''},
          credits: {enabled: false}, // Permet d'enlever le lien vers le site qui fourni le module
          'yAxis': {
            min: 99.9,
            max: 100,
            plotBands: [{
              from: 99.9,
              to: 100,
              color: '#55BF3B'
            }, {
              from: 99.98,
              to: 99.99,
              color: '#DDDF0D'
            }, {
              from: 99.900,
              to: 99.980,
              color: '#DF5353' // Rouge
            }]
          },
          pane: {
            startAngle: -150,
            endAngle: 150
          },
          'series': [{
            'data': [Number(value)],
            'type': 'gauge'
          }]
        }
      };

      var backbone = {'backbonegraph': ''};

      // Set up a pool of PhantomJS workers
      exporter.initPool();

      // Perform an export
      /*
          Export settings corresponds to the available CLI arguments described
          above.
      */

      exporter.export(exportSettings, function (err, res) {
          // Kill the pool when we're done with it, and exit the application
          if (err) {
            console.log(err);
            exporter.killPool();
            reject('Erreur : ' + err);
          } else {
            exporter.killPool();
            backbone.backbonegraph = base64DataURLToArrayBuffer(res.data);
            resolve(backbone);
          }
      });
    } catch (error) {
      reject('Autre erreur : ' + error);
    }
  });
}

And I have two other modules that call this function about at the same time.
The first call will be ok, but the second one no.
I think it's because of the code exporter.killPool();

How can I avoid this problem?  I add that I can't use an array of promises in my case.

Thanks in advance.

**Comment by tlhe** [comment]
me too

**Comment by cvasseng** [comment]
The pool is global, so if you kill it after the first export, it will be killed forever afterwards.

You should move the init/kill outside of the export function:

```
const exporter = require('highcharts-export-server');

exporter.initPool();

function getGraph(value) {
  return new Promise(function(resolve, reject) {
    try {
      var exportSettings = {
        options: {
          title: { text: '' },
          credits: { enabled: false }, // Permet d'enlever le lien vers le site qui fourni le module
          yAxis: {
            min: 99.9,
            max: 100,
            plotBands: [
              {
                from: 99.9,
                to: 100,
                color: '#55BF3B'
              },
              {
                from: 99.98,
                to: 99.99,
                color: '#DDDF0D'
              },
              {
                from: 99.9,
                to: 99.98,
                color: '#DF5353' // Rouge
              }
            ]
          },
          pane: {
            startAngle: -150,
            endAngle: 150
          },
          series: [
            {
              data: [Number(value)],
              type: 'gauge'
            }
          ]
        }
      };

      var backbone = { backbonegraph: '' };

      // Set up a pool of PhantomJS workers
      exporter.initPool();

      // Perform an export
      /*
        Export settings corresponds to the available CLI arguments described
        above.
      */

      exporter.export(exportSettings, function(err, res) {
        // Kill the pool when we're done with it, and exit the application
        if (err) {
          console.log(err);
          reject('Erreur : ' + err);
        } else {
          backbone.backbonegraph = base64DataURLToArrayBuffer(res.data);
          resolve(backbone);
        }
      });
    } catch (error) {
      reject('Autre erreur : ' + error);
    }
  });
}
```

Then make sure to kill the pool before exiting the application to remove all the phantom processes. 

The best way is to make it into a module like this:

```
// myExportModule.js

const exporter = require('highcharts-export-server');

exporter.initPool();

module.exports.getGraph = function (value) {
....
};

module.exports.kill = exporter.killPool;
```

and then use it as such
```
const export = require('./myExportModule');
export.getGraph(...)
.then((data) => {
  // Do something cool here
})
.catch((e) => {
   console.error(e);
});
```
