### ISSUE TITLE
typeerror 'file' arguments must be a non-empty string

### ISSUE THREAD

**Issue by vtejuf** [highcharts/node-export-server#91]
hi there,
when i start server , there has console 
'TypeError: "file" argument must be a non-empty string'
did i lost some thing? thanks  a lot

**Comment by vtejuf** [comment]
to add:
i followed README then got that error

**Comment by Krishnan-Raghavan** [comment]
did you get a solution for this problem?

**Comment by vtejuf** [comment]
@Krishnan-Raghavan nope, i used chromeheadless instead

**Comment by fsonmez** [comment]
any solutions to this?

**Comment by afbora** [comment]
+
