### ISSUE TITLE
Different characters on windows or on linux

### ISSUE THREAD

**Issue by miniil** [highcharts/node-export-server#93]
Hi,

(it's me again ;) )

I put my code that work well on windows on a centos 7 server.

The code doesn't give any error but the result is different for the characters (title of the chart, numbers, ...).

Here is the good result (node.js on windows) : https://imgur.com/a/B0Zmx
And here is the bad result (node.js on linux centos 7) : https://imgur.com/WSsnYCd

My code pass the res.data to a html page to show a png image.

Thanks for your help.

**Comment by cvasseng** [comment]
Hi,

looks like it may be an issue with fonts - which ones do you have installed on the CentOS server (usually in `/usr/share/fonts`)?

**Comment by cvasseng** [comment]
If you're still having issues with this, please refer to this: https://github.com/highcharts/node-export-server#linux

If it doesn't help you, please feel free to reopen this issue or create a new one.
