### ISSUE TITLE
infile with function doesn't work

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/node-export-server#94]
Using curl, in infile string, an option is defined as a function or a string of a function - I have errors and not a valid chart, however a file is returned.

When trying:
(running in Windows, so " are escaped)
`curl -H "Content-Type: application/json" -X POST -d "{\"infile\":{\"title\": {\"text\": \"Steep Chart\"}, \"series\": [{\"data\": [29.9, 71.5, 106.4]}], \"yAxis\": [{ \"tickPositioner\": \"function(){return: [0, 1, 10, 50, 100];}\" }] }}" 127.0.0.1:7801 -o mychart.png`

I am getting a file with image of the error text: `"Chart input data error: TypeError: undefined is not a constructor (evaluatinh 'f.apply(this,[this.min,this.max])')"`

When trying as a function:
(running in Windows, so " are escaped)
`curl -H "Content-Type: application/json" -X POST -d "{\"infile\":{\"title\": {\"text\": \"Steep Chart\"}, \"series\": [{\"data\": [29.9, 71.5, 106.4]}], \"yAxis\": [{ \"tickPositioner\": function(){return: [0, 1, 10, 50, 100];} }] }}" 127.0.0.1:7801 -o mychart.png`

I am getting a file with text, but with image file extension: `SyntaxError: Unexpected token u in JSON at position 119<br> &nbsp; &nbsp;at Object.parse (native)<br> &nbsp; &nbsp;at parse (C:\node-export-server\node_modules\body-parser\lib\types\json.js:88:17)<br> &nbsp; &nbsp;at C:\node-export-server\node_modules\body-parser\lib\read.js:116:18<br> &nbsp; &nbsp;at invokeCallback (C:\node-export-server\node_modules\raw-body\index.js:262:16)<br> &nbsp; &nbsp;at done (C:\node-export-server\node_modules\raw-body\index.js:251:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (C:\node-export-server\node_modules\raw-body\index.js:307:7)<br> &nbsp; &nbsp;at emitNone (events.js:86:13)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:185:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:974:12)<br> &nbsp; &nbsp;at _combinedTickCallback (internal/process/next_tick.js:80:11)`

**Comment by mingjunz** [comment]
The reason for the exception is: 
the http Content-Type is application/json, so we the server get the http post request, it will use bodyparse to parse the request body, JSON.parse doesn accept the json with javascript function.

**Comment by cvasseng** [comment]
@KacperMadej There's a syntax error in your tick positioner (`:` after return).

Also, the input must be unquoted for it to be interpreted as JavaScript and not JSON.

The below input should work:

        {
          title: {
            text: "Steep Chart"
          },
          series: [
            {
              data: [
                29.9,
                71.5,
                106.4
              ]
            }
          ],
          yAxis: [
            {
              tickPositioner: function(){return: [0, 1, 10, 50, 100];}
            }
          ]
        }

It can be tested by pasting into http://export.highcharts.com

**Comment by KacperMadej** [comment]
@cvasseng I fixed problem with `:` - thank you pointing that out. However, I am still unable to create a chart. Could you give me the `curl` command that will work and will create the chart defined in the first comment?

```
curl -H "Content-Type: application/json" -X POST -d "{\"infile\":{\"title\": {\"text\": \"Steep Chart\"}, \"series\": [{\"data\": [29.9, 71.5, 106.4]}], \"yAxis\": [{ \"tickPositioner\": \"function(){return [0, 1, 10, 50, 100];}\" }] }}" 127.0.0.1:7801 -o mychart.png
```
The above is not producing a correct PNG file :(
![mychart](https://user-images.githubusercontent.com/8960408/32836589-9b307786-ca0a-11e7-80cd-d5ac44dd98e7.png)

Unquoted `-d` argument is throwing me curl errors about unmatched braces and unresolved hosts.

**Comment by cvasseng** [comment]
It's the same as the one you have, but with the options unquoted so that it's treated as JavaScript and not JSON:

` curl -H "Content-Type: application/json" -X POST -d "{\"infile\":\"{title: {text: 'Steep Chart'},series: [{  data: [29.9, 71.5,    106.4  ]}], yAxis: [{tickPositioner: function(){return [0, 1, 10, 50, 100];}}]}\"}" export.highcharts.com -o mychart.png`

**Comment by KacperMadej** [comment]
Great, resolved. Thank you very much 👍 


BTW: Windows PowerShell disappoints - in it this doesn't work

**Comment by ivmdev** [comment]
hi guys, i know this is closed, but i was wondering if you can give me a hand. this is my post:

curl -H "Content-Type: application/json" -X POST -d "{\"infile\":{\"chart\":{\"plotBackgroundColor\": null,\"plotBorderWidth\": null,\"plotShadow\": false,\"type\": \"pie\"},\"exporting\":{\"enabled\": false},\"title\":{\"text\": null},\"tooltip\":{\"enabled\": false},\"credits\":{\"enabled\": false},\"legend\":{\"align\": \"right\",\"verticalAlign\": \"middle\",\"layout\": \"vertical\",\"itemStyle\":{\"fontSize\": \"12px\",\"width\": 200,\"textOverflow\": null}},\"plotOptions\":{\"pie\":{\"size\": 150,\"allowPointSelect\": true,\"cursor\": \"pointer\",\"dataLabels\": {\"formatter\": function() {if (this.y != 0 || this.y != \"\") {return this.y + \"%\";}else {return null;}}},\"showInLegend\": true}},\"series\": [{\"name\": \"Question\",\"colorByPoint\": true,\"data\": [{\"name\": \"Meets all and exceeds some\",\"y\": 5,\"color\": \"#3cb44b\"},{\"name\": \"Meets them all\",\"y\": 38,\"color\": \"#bfef45\"},{\"name\": \"Meets most of them most of the time\",\"y\": 48,\"color\": \"#ffe119\"},{\"name\": \"Only delivers on some\",\"y\": 9,\"color\": \"#f58231\"},{\"name\": \"Regularly underperforms on most\",\"y\": 1,\"color\": \"#42d4f4\"},{\"name\": \"Not applicable\/not relevant\",\"y\": 0,\"color\": \"#e6194B\"},{\"name\": \"Did not ask\",\"y\": 0,\"color\": \"#000000\"}]}]}}" http://localhost:7801 > test.png

Im getting Unexpected token at position 469, i don't really understand why, it is working on your server: export.highcharts.com, but not on mine.

**Comment by xuzju023** [comment]
how can i resolve this problem?
![63d1011fca7f2949fb0550ab75e7616](https://user-images.githubusercontent.com/38324922/98250863-f5002800-1fb2-11eb-8832-0ffaa623d701.png)

**Comment by PaulDalek** [comment]
Hi @xuzju023 

There are few mistakes in the request body. First, you used `infile` two times (one inside another). Secondly, the JSON object of the `infile` shouldn’t be a string. Lastly, setting the `tickPositioner` this way won’t work. To apply it, you can use the `callback` argument. I have used Curl to test the requests to a server. Here is a correct command:

`curl -H "Content-Type: application/json" -X POST -d '{"infile": {"title":{"text":"Steep Chart"},"series":[{"data":[29.9,71.5,106.4]}]},"constr": "Chart", "callback": "function(chart){chart.update({xAxis:[{tickPositioner:function(){return [0,1,10,50,100];}}]});}"}' https://export.highcharts.com/ -o curl.png`

**Comment by xuzju023** [comment]
> `tickPositioner`

got,thx~

**Comment by xuzju023** [comment]
@PaulDalek  
got,thx~
