### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by crapthings** [highcharts/node-export-server#95]
we've found high cpu usage is this relative to node export server ?

![image](https://user-images.githubusercontent.com/1147704/32477935-8ef05cc4-c3bc-11e7-905c-0a732f0bc8b3.png)

https://github.com/ariya/phantomjs/issues/14334

**Comment by crapthings** [comment]
its seems that phantomjs has alot of issues point to cpu load.

what if we switch to chrome headless ?

**Comment by crapthings** [comment]
how about this one 

https://github.com/GoogleChrome/puppeteer

**Comment by crapthings** [comment]
as @gouchaoer said, we can try pass disk cache to phantomjs instance.

https://github.com/ariya/phantomjs/issues/14334#issuecomment-342380989

--disk-cache=[true|false] enables disk cache (at desktop services cache storage location, default is false). Also accepted: [yes|no].
--disk-cache-path specifies the location for the disk cache.

**Comment by cvasseng** [comment]
PhantomJS indeed uses a lot of memory. You can mitigate this somewhat by playing with the pool size/work count options (`--workers` and `--workLimit`) out-of-the-box if you don't want to experiment with `--disk-cache` in Phantom on a fork.

We will be switching to Chrome headless in the future.
