### ISSUE TITLE
Define ACCEPT_HIGHCHARTS_LICENSE in package.json

### ISSUE THREAD

**Issue by CarloMandelli** [highcharts/node-export-server#97]
Hi,
i define **"highcharts-export-server" :"2.0.3"** as dependence in my package.json
I use an automated deployment but i can't set ACCEPT_HIGHCHARTS_LICENSE as enviroment variable on my server directly.
Is there any way to set ACCEPT_HIGHCHARTS_LICENSE in package.json?

**Comment by crapthings** [comment]
yeah how

**Comment by cvasseng** [comment]
You could try setting it in `scripts.preinstall`, something like:
```
{
  "scripts": {
    "preinstall": "export ACCEPT_HIGHCHARTS_LICENSE=1"
  }
}
```

**Comment by sebastianbochan** [comment]
Hi @drmrbrewer,
Due to the christmas time it will take some time until we are able to look into a solution.
Thank you for your patience.

**Comment by h11a** [comment]
Any update on this? I am struggling to get it working.

**Comment by bezerrathm** [comment]
Any solution?

**Comment by igor-sky** [comment]
Still no solution?

**Comment by uddhavb** [comment]
the only way it works for me is creating a script like

"scripts": {
        "build": "ACCEPT_HIGHCHARTS_LICENSE=1 npm install"
        }
It would be really helpful if we could set the env variable somehow so that a simple `npm i` would work

**Comment by alexboss** [comment]
Some feedback provided there https://www.highcharts.com/forum/viewtopic.php?f=9&t=44882&p=163889#p163889 but still no working solution for me :(

**Comment by PaulDalek** [comment]
Hi @alexboss 

Try to set the environment variable directly in the `install` section, like that: `"install": "set ACCEPT_HIGHCHARTS_LICENSE=1 && node ./build.js"`. I tested it on my side and installation is successfully automated.

**Comment by alexboss** [comment]
Thanks for your feedback @PaulDalek . Unfortunately, still doesn't work for me. I will do further investigation and attempts and report here if I manage to fix it.

**Comment by Flexiink** [comment]
the only working solution for us

```
{
  "scripts": {
    "postinstall": "npm run highcharts-licens",
    "highcharts-licens": "export ACCEPT_HIGHCHARTS_LICENSE=1 && node node_modules/highcharts-export-server/build.js"
  }
}
